### ISSUE TITLE
Current master branch failing

### ISSUE THREAD

**Issue by cmluciano** [chef/supermarket#1007]
I am working on a couple of features locally, and it seems like the supermarket build is failing. Just running the controller specs yields the following

https://gist.github.com/cmluciano/2f33494f862db1f5cf24

**Comment by cmluciano** [comment]
Wondering if this is related to me not setting up auth potentially?

**Comment by smith** [comment]
@cmluciano I don't think you need any external auth set up to run the specs. You might want to make sure the state of you DB is OK by doing a `env RAILS_ENV=test rake db:schema:load`.

You could follow along with https://github.com/chef/supermarket/blob/54e70292e1d79e1bd6ff98ff3e192fb42feafff1/.travis.yml and try to reproduce how we run it on Travis, which appeared to work the last time something got on master.

**Comment by cmluciano** [comment]
Ya the dev instructions mention ```bundle exec rake db:setup```, but travis uses ```bundle exec rake db:schema:load```.

Will take a look at that.

**Comment by cmluciano** [comment]
Yep my database seems to have been in a bad state. Thanks!
