### ISSUE TITLE
git links to cookbook repos

### ISSUE THREAD

**Issue by neurogenesis** [chef/supermarket#1009]
As a features request, it would be really helpful to provide links to cookbook repos in git.

When looking at new cookbooks it can be helpful to quickly browse the repo for incompatibilities (like the presence of "sensitive" directives breaking chef 11.10.4, which is the latest version supported by AWS opsworks). It's also a quick way to create a fork and submit a PR for key missing functionality.

Providing a link on the cookbook in the supermarket will ensure people are forking the correct repositories (instead of finding one of several forks).

**Comment by smith** [comment]
Cookbooks which have a `source_url` set in their metadata (see https://docs.chef.io/cookbook_repo.html#metadata-rb) or where the owner has manually set the Source URL in supermarket, contain these links.

If a particular cookbook you follow is missing this you should be able to ask the author to add it.

If this doesn't solve your problem or you had something else in mind, please reopen this issue. Thanks!
