### ISSUE TITLE
Contingent cookbooks fails to show all of them

### ISSUE THREAD

**Issue by tuahk** [chef/supermarket#1010]
When looking for all the cookbooks contingent to apt-cookbook you only see some of them.
https://supermarket.chef.io/cookbooks/apt#dependencies

The last cookbook that I get is jenkins_utils and there are plenty of cookbooks using apt after that.

**Comment by smith** [comment]
@tuahk which browser and OS version are you using? I'm on Chrome/Mac and the last one I see on there is "zotonic", which looks correct.

**Comment by tuahk** [comment]
@smith I use Ubuntu 14.04 and Firefox. I noticed that after loading contingent cookbooks page I just have to resize my browser window, to smaller or bigger, and all the cookbooks show up. For some reason I don't get them all if I just load that page. 

I had same kind of behaviour with Android and Firefox but it seemed random whether it showed all the cookbooks or just some of them.

**Comment by nellshamrell** [comment]
@tuahk I'm going to close this for now, but please let us know if you see this issue again!
