### ISSUE TITLE
Custom image support in addition to Gravatar

### ISSUE THREAD

**Issue by double-z** [chef/supermarket#1012]
As a user I would like to be able to have the option of adding a custom image in place of Gravatar pic and disabling Gravatar support.

**Comment by nellshamrell** [comment]
Is this due to security concerns with using Gravitar?  Or just wanting to be able to have a custom image?

**Comment by stanchan** [comment]
This is primarily due to rendering issues when Gravitar is blocked through a proxy.

**Comment by nellshamrell** [comment]
Labeling as BUG for the issues when Gravitar is blocked through a proxy and FEATURE for allowing custom images.  I'll work on the bug first :)

**Comment by nellshamrell** [comment]
BUG part of this is complete, taking the Bug label off and returning this to the backlog.

**Comment by nellshamrell** [comment]
We're not going to move forward with this at this time, but I greatly appreciate all the input!
