### ISSUE TITLE
Berks install default cookbook version is wrong due missorder in UNIVERSE endpoint

### ISSUE THREAD

**Issue by Maks3w** [chef/supermarket#1016]
Following https://github.com/berkshelf/berkshelf/issues/1415

> @sethvargo said: This is just the nature of depsolving :smile:. If you need a specific requirement, you need to pin it. Otherwise, gecode's algorithm uses a first-find approach (as opposed to other depsolvers which use a best-find algo).

This is because UNIVERSE endpoint should return entries sorted from the up to down, instead apache2 cookbook 1.11.0 version is the first version found.

**Comment by sethvargo** [comment]
I don't really think that is the correct approach, since the Chef Server also returns oldest to newest. You'll get a different resolution. As I said in my response, if you want a specific version series, you should specify that.

**Comment by Maks3w** [comment]
What is weird is a package installer tool returns not old neither new versions.

I don't know any popular tool which don't install the package with the bigger version number by default.

For me is clearly an important issue

**Comment by sethvargo** [comment]
@Maks3w I think you may be conflating issues a bit. Perhaps [my answer here](https://github.com/berkshelf/berkshelf/issues/1416) can help explain things further.

Berkshelf needs to have parity with the Chef Server, or else resolution at runtime could be different than resolution at build time. It would be a really bad experience if Berkshelf resolved cookbook version x.y.z, but then in production the Chef Server used w.x.y. That would be very, very bad. 

As such, we can't just update Supermarket or Berkshelf, but we need to also update the Chef Server's depsolver to have matching parity. I don't disagree with your assessment, but it's not as easy as "just update this thing over here". It's a much larger problem that the community has been trying to solve for some time now.

**Comment by Maks3w** [comment]
Also makes almost useless the dependency resolver from a cookbook to other if you need start to patch every indirect dependency.

supose this:

fooCookbook a require database, database require mysql, database require mysql-gem

`cookbook 'fooCookbook', '~> 1.0'`

but instead you are forcing me to add every dependency in the graph manually in `Berksfile` because the version installed is "random"

**Comment by Maks3w** [comment]
Supermarket UI already sort the version dropdown list.

Also offer a hint about what to add into your Berksfile.

But don't have a note saying `Thanks for install our latest cookbook version, don't forget add all the dependencies into your Berksfile too because we will install old cookbook versions which don't support the latest Ubuntu platform used by you`

`Don't forget, we like to have you up to date with our software, but we can't quarantee we will keep you up to date`

**Comment by sethvargo** [comment]
Hi @Maks3w 

I understand that you are frustrated, but please keep in mind that Berkshelf is an open-source software tool that is run by volunteers. I am sorry the tool is not behaving the way you expect, but please treat the maintainers with respect.

If you feel that Berkshelf is not suiting your needs, you are more than welcome to submit a [Chef RFC](https://github.com/chef/chef-rfc) to start a discussion in the Chef community around the dependency solving problems. I think you will find the resulting conversation insightful.

If you prefer not to use Berkshelf, you can use other tools like librarian or even vendor and version cookbooks yourself using knife.

**Comment by Maks3w** [comment]
I frustrated because you close the issue in Berkshelf repo claiming is an issue in the server side and here now we are blamming to the user now.

I accept your point of install the first version present in the response. But then you accept is incongruent display a dropdown in the UI with the versions sorted but not sort the versions in the API response.

**Comment by sethvargo** [comment]
Hi @Maks3w 

Please take it up with another maintainer. Have a great day! :smile:

**Comment by smith** [comment]
@Maks3w I understand your frustration. I'm going to close this now, and hopefully the following can help you move forward:

* If you're not satisfied with the version that Berkshelf has resolved for a particular cookbook, you should be able to run `berks update` or `berks update $COOKBOOK_NAME` to have Berkshelf attempt to get the latest.
* Open an RFC, as @sethvargo mentioned. While I agree with your point that the ordering makes more sense to be from newest to oldest, the main reason we have it behaving this way is that this is the way that the Chef server behaves. We are making the tradeoff on the side of behaving more like the Chef server instead of behaving "correctly."
* Be more proscriptive in your version pinning. `cookbook "fooCookbook"`, in the Berksfile DSL means "any version of the fooCookbook, I don't care." If you do care, it should be pinned.

Hope that helps and please let me know if you have any more questions or concerns.
