### ISSUE TITLE
Dev Environment PG errors

### ISSUE THREAD

**Issue by cmluciano** [chef/supermarket#1018]
From a fresh dev environment, I am unable to search for anything like cookbooks. I get a rather lengthy error from activerecord. I thought this had to do with me not having a postgresql extension, but it seems that I do have the extensions listed in the readme.

![screen shot 2015-04-13 at 11 36 13 am](https://cloud.githubusercontent.com/assets/4790487/7119065/567c087c-e1d1-11e4-980f-2a8e192c835d.png)

If I perform an empty search, I get all cookbooks back as expected.

cc @smith cause I think I remember you mentioning an extension that I may have forgot.

**Comment by raskchanky** [comment]
@cmluciano I'm guessing you're missing `pg_trgm`

**Comment by cmluciano** [comment]
I feel silly now. I was almost certain that I had this installed. Thanks @raskchanky
