### ISSUE TITLE
admin user cannot manipulate collaborators

### ISSUE THREAD

**Issue by someara** [chef/supermarket#1021]
Admin users cannot manipulate collaborators with the "manage cookbooks" drop down.
They can only transfer ownerships.

It'd be handy to have this available in various scenarios.

-s

**Comment by someara** [comment]
For example, there are tons of cookbooks on the supermarket that have "opscode" as a collaborator.

Logged in as the "Chef" user,  (an admin user), I have no way to update change "opscode" to "chef" without the intervention of the actual maintainer user, or directly manipulating the database.

**Comment by nellshamrell** [comment]
This has been fixed :)
