### ISSUE TITLE
CSRF detected

### ISSUE THREAD

**Issue by cmluciano** [chef/supermarket#1024]
Using mainly defaults for a test kitchen instance of the chef-server cookbook and the supermarket cookbook, I get a CSRF error.

My guess is that it might be a self-signed cert issue. I decided to open an issue to see if anyone has seen this before. Will poke around the logs some more.

http://33.33.33.10/auth/failure?message=csrf_detected&strategy=chef_oauth2
![screen shot 2015-04-17 at 9 26 04 am](https://cloud.githubusercontent.com/assets/4790487/7202826/cec416a2-e4e3-11e4-94fa-630703dfdc7d.png)

**Comment by nellshamrell** [comment]
Hello!

This is, indeed, a self signed cert issue.  Check out https://www.chef.io/blog/2015/04/21/setting-up-your-private-supermarket-server/  (under the "Uploading your first cookbook to Supermarket" heading) for some info on resolving this and let us know if you're still having issues!

**Comment by cmluciano** [comment]
Thanks @nellshamrell I will definitely take a look at the new post. Thank you for your time!

**Comment by nellshamrell** [comment]
You are quite welcome!  Closing this for now, but feel free to re-open if you are still experiencing trouble :)
