### ISSUE TITLE
When clicking a cookbook's CHANGELOG tab, browser header disappears

### ISSUE THREAD

**Issue by miketheman** [chef/supermarket#1026]
Visit https://supermarket.chef.io/cookbooks/datadog
Click "Changelog"
The Changelog takes over the entire view port, and you can no longer scroll up. Clicking another tab will restore the browser to normal state.

Likely has something to do with CSS - but I'm not clear on that yet.

**Comment by cmluciano** [comment]
Seems to have different behavior between cookbooks. For example https://supermarket.chef.io/cookbooks/docker#changelog takes over the view, but you can then scroll up.

**Comment by miketheman** [comment]
It also appears to have some problem with finding the end of the page. While the docker cookbook changelog remains "white background" until the end of the lengthy changelog, the datadog cookbook one does not.
