### ISSUE TITLE
Transferring ownership should not revoke all access to a cookbook

### ISSUE THREAD

**Issue by eherot** [chef/supermarket#1035]
Instead, perhaps after you transfer ownership of a cookbook, you are automatically added as a collaborator?

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by EdHurtig** [comment]
:+1:

**Comment by EdHurtig** [comment]
@eherot Seems like this is the intended functionality according to the method docs.

https://github.com/chef/supermarket/blob/master/app/controllers/collaborators_controller.rb#L73-L82

**Comment by eherot** [comment]
Indeed, that does not appear to actually happen.
