### ISSUE TITLE
omnibus-supermarket `reconfigure` caches the node data, making it impossible to remove or update some configuration settings

### ISSUE THREAD

**Issue by irvingpop** [chef/supermarket#1036]
When you run `supermarket-ctl reconfigure` on the Omnibus Supermarket package,  it uses chef-zero (`chef-client -z`) which writes out a node file to `/opt/supermarket/embedded/nodes/nodename.json`.

On subsequent runs the node file is loaded, which means that reconfigure runs are not stateless.   For example, it's impossible to remove a configuration setting. 

This was fixed in omnibus-ctl 0.3.4: https://github.com/chef/omnibus-ctl/pull/27

**Comment by irvingpop** [comment]
Thanks to @stevendanna for the help!    
it turns out we are pointed at a too-old omnibus-software sha: https://github.com/chef/omnibus-supermarket/blob/master/Gemfile.lock#L3
which gets us a too-old version of omnibus-ctl:  https://github.com/chef/omnibus-software/blob/2e26be554787803214ba9525b6b4214b5c7b6d43/config/software/omnibus-ctl.rb

**Comment by nellshamrell** [comment]
This was fixed with https://github.com/chef/omnibus-supermarket/pull/21
