### ISSUE TITLE
Changes to a user's email address in Chef Server is not reflected in Supermarket DB

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/supermarket#1037]
When a user changes their email address in their Chef Server account that change does not get made in Supermarket's account. So things like Supermarket notifications continue to go to the old email address.

**Comment by nellshamrell** [comment]
I just tested this using a new private Chef Server running Chef 12 and a new private Supermarket server.  Found a few interesting things:

1) There IS an auto-update in Supermarket for when a user's name or email address is changed in Chef Server.
2) However, it only does the autoupdate when the user logs into Supermarket, so in order for this change to show up in Supermarket, the user must log out and log back into Supermarket.

This begs the question of whether we want to do this more often via a cron job.  We COULD have a cron job run anywhere from once an hour to once a day to sync all user information in Supermarket with that user's information in Chef Server, however this could be a heavy load on public Supermarket and hosted Chef.

Thoughts, anyone?

**Comment by nellshamrell** [comment]
After some discussion, it seems like the best solution would be a daily or weekly cron job.

We will likely want to leverage /users?verbose=true API for the chef server that returns all the users, first, last, email.

Will start digging into implementing this.

**Comment by nellshamrell** [comment]
Hmmm...

Gave this some additional thought.  I'm hesitant to call the Chef Server API directly, as that would introduce another dependency on it besides oc-id.  While this is not fatal by any means...it could prove problematic in the future if oc-id is moved out of Chef Server (I don't know of any immediate plans to do so).

I'd rather keep the dependencies on Chef Server encapsulated in oc-id, so I'm going to submit a pull request to oc-id (which lives in the [Chef Server Github repo](https://github.com/chef/chef-server)) to enable it to provide a list of users registered with oc-id (provided the request comes from an authorized source).  Will update here on any feedback I get on that strategy.

**Comment by nellshamrell** [comment]
I've completed a [pull request for oc-id](https://github.com/chef/chef-server/pull/400) and submitted it to Chef Server.  This issue is now on hold pending the merging and release of that pull request.

**Comment by antima-gupta** [comment]
As the login process will move to **Automate Login** that's  we are moving this ticket to **blocked**.
If we will not move login process in  **Automate Login**, then we will follow below approach:

```
# OC-ID:
Once user will login into oc-id and updated the email, then we send the verification mail
And when user will verify the email then only user's email get updated
For updating email it calls `change_email`
1] Need to create a method to call supermarket update email API from `change_email` method in the oc-id Profile controller
2] Will create some signature using user's parameter and send this to authenticate update email API

# Supermarket side:
1] Need create API for update user email
2] A method to verify signature
```
