### ISSUE TITLE
Make it clear how to get a private key

### ISSUE THREAD

**Issue by thommay** [chef/supermarket#1048]
The `manage profile` page doesn't make it obvious how to get a private key to upload stuff to the supermarket.

**Comment by nellshamrell** [comment]
Need clearer indication that this should be done through hosted chef/ the user's chef server

**Comment by nellshamrell** [comment]
https://twitter.com/rmoriz/status/603562523388997633

**Comment by rmoriz** [comment]
my tweet was inspired by https://github.com/priestjim/chef-openresty/issues/20

**Comment by smith** [comment]
We're making some changes in oc-id to make it faster and easier to access and reset your keys. Once these are done there will be one clear place where to do this for both hosted and on-premises Chef server.
