### ISSUE TITLE
Incremental update of out of date gems

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1049]
@irvingpop wisely pointed out that we have some out of date gems in use in Supermarket.  Although we first tried to take the "fix them all at once" approach, we kept seeing spec failures building with each change.  I 100% agree we should update the gems, but I'd like to take more of an incremental approach to lessen the risk of breaking things.

Please refer to @irvingpop's pull request #1042  for guidelines on which gems should be updated, then I'd like to take the approach of updating three or four at a time, getting specs passing, deploying, then building on it with the next gem updates.

**Comment by irvingpop** [comment]
+1

It would be really cool to run `bundle-audit` in CI runs, once we get to a good state.

**Comment by nellshamrell** [comment]
:+1:

**Comment by nellshamrell** [comment]
Concentrate on security issue gems first

**Comment by nellshamrell** [comment]
This was partially solved by #1075, moving back to the backlog for the time being.

**Comment by nellshamrell** [comment]
Definition of Success: We will call this one closed with bundle-audit shows no security risk gems.

**Comment by robbkidd** [comment]
```
~/supermarket ±master [8d2a69d] » be bundle-audit
No vulnerabilities found
```

So we've got that going for us.

**Comment by robbkidd** [comment]
It helps if you update bundle-audit's security vulnerability database. PR incoming to address most of the vulnerabilities reported at Gemnasium.

**Comment by robbkidd** [comment]
Vulnerable gems updated. We still have some that are "out-of-date," but I don't currently consider that a bad thing.

I propose expanding the definition of done given by @nellshamrell above ("We will call this one closed with bundle-audit shows no security risk gems.") to include running `bundle-audit` as part of the test suite.

**Comment by robbkidd** [comment]
Closing now that bundler-audit reports we're clean.
