### ISSUE TITLE
supermarket cookbook missing default attribute

### ISSUE THREAD

**Issue by philicious** [chef/supermarket#1050]
the https://github.com/opscode-cookbooks/supermarket misses default attribute for ['supermarket']['port']
see:
https://github.com/opscode-cookbooks/supermarket/blob/master/recipes/_application.rb#L52

**Comment by nellshamrell** [comment]
The Supermarket Cookbook has been deprecated in favor of the Supermarket Omnibus Cookbook (see https://supermarket.chef.io/cookbooks/supermarket) so we will not be fixing this issue.  Apologies and good luck!
