### ISSUE TITLE
Remove foodcritic from Supermarket

### ISSUE THREAD

**Issue by dhoer** [chef/supermarket#1051]
Foodcritic hasn't kept up with Chef and hasn't had a release for almost a year now.  Either Chef should take ownership of Foodcritic, fork it, or stop supporting it altogether.  There should be no reason for Foodcritic on supermarket to flag sensitive attribute.

**Comment by rmoriz** [comment]
seems like they "just" need to cut a new foodcritic release… 
https://github.com/acrmp/foodcritic/commits/master

**Comment by lamont-granquist** [comment]
We're participating in maintaining foodcritic now, we won't be forking it or abandoning it.

**Comment by rmoriz** [comment]
:+1:

**Comment by dhoer** [comment]
Awesome!

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by dhoer** [comment]
I left `sensitive true` out of my code that had passwords because I didn't want people to think there were issues with my cookbook.  How dumb was that!

**Comment by rmoriz** [comment]
In cases, when you really know that FC reports a false positive, you can "white-list" it:
http://acrmp.github.io/foodcritic/#how_can_i_ignore_a_specific_instance_of_a_warning

**Comment by dhoer** [comment]
@rmoriz Thanks so much for that info.
