### ISSUE TITLE
Download counts considered harmful

### ISSUE THREAD

**Issue by coderanger** [chef/supermarket#1052]
Until someone puts in the time to make download counts not a complete lie, we should hide them in the UI.

**Comment by nathenharvey** [comment]
Unfortunately, the download counts are the [complete truth](https://www.chef.io/blog/2015/01/21/those-pesky-supermarket-download-counts/).  Looking at a single count of downloads is meaningless.

We've been talking about displaying a download score that would work something like this:

    download_score = (number_of_downloads / max_download_count) * 100

That would yield scores that look something like this:

cookbook	|	downloads	|	download score
--------	|	---------	|	---------------
mysql	|	99,817,964	|	100.000
java	|	60,299,205	|	60.409
apache2	|	59,955,488	|	60.065
bacon	|	56,458,583	|	56.562
nginx	|	51,061,571	|	51.155
chef-sugar	|	19,038,649	|	19.073
magic-shell	|	12,238,507	|	12.261
iptables	|	11,281,834	|	11.302
rackspace_monitoring	|	2,277	|	0.002


Would love to hear some feedback on this approach!

**Comment by coderanger** [comment]
That still has no value, it would only mark roughly when the cookbook was released relative to other cookbooks. The underlying problem is that the human-initiated downloads are such a tiny signal in the overwhelming noise that is berks-api downloads et al (which just increase at a somewhat steady rate based on the number of berks-api servers in operation, a number we don't have). As there is no way to fix that without additional data about how a download was initiated all data on the site currently is worthless. At a minimum we should remove it from the UI until new, good data can be created. Given that we can never reconstruct "overall downloads" we should probably at that point move to rolling counts like NPM and PyPI use (per day, per week, per month). But that is all impossible until someone takes the time to totally rebuild the counters system.

**Comment by dblessing** [comment]
Both # of downloads and download score downplay the impact newer cookbooks have. It might lead users to old, unmanaged cookbooks simply because they've been on the Supermarket for years. It has little value other than to mislead.

**Comment by nellshamrell** [comment]
We agree, we will remove download counts until a better quality measurement of cookbooks can be created.

**Comment by nellshamrell** [comment]
Should we have a different way of featuring cookbooks?  I believe that column is currently determined by download count.

**Comment by rmoriz** [comment]
start a "Cookbook of the Week" blog post series?

**Comment by nellshamrell** [comment]
Good thinking, @rmoriz, and I will keep that in mind for the future :)

**Comment by nathenharvey** [comment]
the change has been deployed.

Featured cookbooks are listed here:  https://supermarket.chef.io/cookbooks-directory
