### ISSUE TITLE
Make gzip_static optional in sm cookbook

### ISSUE THREAD

**Issue by iroller** [chef/supermarket#1061]
Cookbook should rely on default build of nginx which doesn't include ngx_http_gzip_static_module.
Nginx cookbook has it off by default: ```node[:nginx][:gzip_static] == 'off'```.
https://github.com/miketheman/nginx/blob/55217a6a078c1aea7bffad4205ae310bcb098d5d/README.md#gzip-module

http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

```
This module is not built by default, it should be enabled with the --with-http_gzip_static_module configuration parameter.
```

**Comment by nellshamrell** [comment]
Hello @iroller, I just wanted to confirm that you are using the https://supermarket.chef.io/cookbooks/supermarket cookbook (which is deprecated)?

**Comment by iroller** [comment]
Hi @nellshamrell , it wasn't deprecated at the moment I posted the issue :)
I'm still using this cookbook, but going to switch to the new one soon. Feel free to close the issue.

**Comment by nellshamrell** [comment]
Thanks so much!
