### ISSUE TITLE
Transfering ownership of a cookbook workflow needs love

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1068]
Transferring ownership of a cookbook is a very tricky process at the moment.  If you put a cookbook up for adoption and someone tries to adopt it you get an e-mail announcing their intent (good).  That e-mail contains their e-mail, but not their username (not so good).  The e-mail contains no link to allow you to easily transfer ownership (also not so good).  If you go to Supermarket and transfer ownership you're presented with a search dialog that searches by username, but not the e-mail that was provided to you (really bad).  You kinda have to guess what their name might be based on their e-mail address.  It might work out for you, but it probably won't.

**Comment by nellshamrell** [comment]
Thank you for reporting this issue.  There are two problems to solve here, as I see it:
1) The email announcing that someone wants to adopt your cookbook absolutely should have the username in it.  That should be simple to add.
2) It should also contain a link to enable easy transfer of ownership.  You may need to log in to Supermarket when you click the link, but it should absolutely direct you to the proper page.
I'm working on these this week :)

**Comment by tas50** [comment]
Sounds good.  Thanks
