### ISSUE TITLE
Mobile view does not contain cookbook names

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1069]
The Supermarket main page displays fairly well on mobile browsers, but for some reason the names of cookbooks are not displayed.  This is on an iPhone 6 with iOS 8.3.  See the attached screenshot.
![img_0023](https://cloud.githubusercontent.com/assets/1015200/8266253/28acbc0c-16d8-11e5-9f49-7559cfdbe398.PNG)

**Comment by nellshamrell** [comment]
Confirmed using an iphone simulator, investigating.
