### ISSUE TITLE
Update dhparam code to utilize the new dhparam LWRP in the OpenSSL cookbook

### ISSUE THREAD

**Issue by kirtfitzpatrick** [chef/supermarket#1080]
Update our code in omnibus that handles dhparams:
https://github.com/chef/omnibus-supermarket/commit/98fdcb804e0b093b7cb38243f5c9532ce2ff6020

to use the new LWRP by @charlesjohnson for dhparams here:
https://github.com/opscode-cookbooks/openssl/commit/0280bdfcfb94ce92e0505e2c4531c205bb556f05

i.e. 

openssl_dhparam '/etc/nginx/ssl/dhparam.pem' do
  generator 2
  key_length 2048
end

**Comment by nellshamrell** [comment]
Fixed with https://github.com/chef/omnibus-supermarket/pull/35
