### ISSUE TITLE
readme updates

### ISSUE THREAD

**Issue by lancepowell** [chef/supermarket#1082]
Would it be possible to have a readme only push without needing to up the cookbook version?

**Comment by nellshamrell** [comment]
Unfortunately no, cookbooks are treated by Supermarket as packaged artifacts - it's not possible with our workflow to update a single file (i.e. the README) without uploading the entire package.  It's an interesting idea, but for now we're going to stay with uploading the entire package and needing to push a new version when something changes.

**Comment by lancepowell** [comment]
Sounds good. WIth the changelog in the email it's simple enough to know now what a cookbook update contains. And with a minor bump in the version it is given with semantic versioning that it is still safe to use. Thanks for looking!

**Comment by nellshamrell** [comment]
You are very welcome!
