### ISSUE TITLE
Single automation user and disable LDAP oc-id auth for Supermarket

### ISSUE THREAD

**Issue by stephenlauck** [chef/supermarket#1088]
I as a customer would like ( in the context of a behind the firewall Supermarket install) to be able to only authenticate one automation use to Supermarket even though I have LDAP auth on my Chef server.

**Comment by stephenlauck** [comment]
* disable user signin and create account
* add supermarket-ctl user create command to create single user
* enable oc-id as usual

**Comment by nellshamrell** [comment]
Hi @stephenlauck!  Have you had a chance to work on this?  If not, no worries, but I will move it from "ready" status to the backlog.

**Comment by AnalogJ** [comment]
Would love to have the ability to disable all authentication and manage cookbook uploads using only one automation account. 

Our inhouse cookbook CI tool manages the version numbers and uploads the cookbooks to a chef-server with a berks-api frontend, but we would love to move straight to supermarket.

**Comment by nellshamrell** [comment]
Although I agree this is a good idea, I'm declaring it not a priority for this quarter and closing this issue.  Thank you all for the input!
