### ISSUE TITLE
source_url and issues_url not taking in Private Supermarket

### ISSUE THREAD

**Issue by amaltson** [chef/supermarket#1110]
I have a metadata file that looks something like:

```ruby
name '<cookbook name>'
description 'Installs/Configures <cookbook name>'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url '<link to local github enterprise>'
issues_url '<link to local github enterprise issues>'
version '0.2.0'

supports 'centos'
supports 'redhat'
supports 'ubuntu'
```

For some reason the `source_url` and `issues_url` don't render in the Private Supermarket.

![no-links](https://cloud.githubusercontent.com/assets/167443/9456032/5c83c45c-4aa0-11e5-88c0-1029e610784d.png)

I've never uploaded a cookbook to the public Supermarket so I'm not sure if this works in general or not. Anyway, just curious. Thanks!

**Comment by nellshamrell** [comment]
It does work in general, not sure why it's not working in private Supermarket, will add this to the backlog to investigate.  Thanks for the report! :)

**Comment by lamont-granquist** [comment]
@nellshamrell @robbkidd are you sure this works right now on the public supermarket when you add an issues_url/source_url to an already existing cookbook that didn't have one?  at least in that use case i've been seeing that the new metadata isn't getting rendered.  not sure about newly created cookbooks that have issues_url/source_url from the start...

**Comment by robbkidd** [comment]
I'll see if I can work up a test case.

**Comment by nathenharvey** [comment]
@lamont-granquist, what are you using to share your cookbook?  stove requires the `--extra-metadata` flag to include the issues_url and source_url

**Comment by lamont-granquist** [comment]
ergh, that's most likely my problem.

**Comment by nellshamrell** [comment]
@lamont-grandquist - has your issue been resolved?

**Comment by lamont-granquist** [comment]
yep

**Comment by amaltson** [comment]
@nathenharvey @nellshamrell I use knife supermarket, am I missing something there?
