### ISSUE TITLE
Adoption Email Issues

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1116]
@nathenharvey reported an issue with the adoption email when we received one for the old Supermarket cookbook:

looks like the adoption email is broken... 

The "supermarket" link points to http://srv/supermarket/releases/7d653ad5d7619f037dd94b28b0fd91aafcd50bbd/cookbooks/supermarket

This should be fixed.

**Comment by mattray** [comment]
I assume it's the same issue, but my email link received this morning went to 
http://opt/supermarket/embedded/service/supermarket/cookbooks/pxe_dust

**Comment by nellshamrell** [comment]
A fix for that is in master and will be deployed as soon as I resolve an issue with our deploy scripts :)

**Comment by nellshamrell** [comment]
Fix has just been deployed!
