### ISSUE TITLE
search dialog for web browsers

### ISSUE THREAD

**Issue by timurb** [chef/supermarket#1120]
For many sites it's quite handy to do search right from address bar in a browser -- you type `github.com`, hit TAB and you can type a string to search on the site.

For Supermarket it is missing but would be great to have this.

**Comment by nellshamrell** [comment]
I think this is a great idea.  It will be awhile before the Chef Supermarket team can get to this feature, but I would absolutely welcome it as a contribution from anyone in the community!

**Comment by smith** [comment]
Chrome detects this on sites using [OpenSearch](http://www.opensearch.org/Documentation/Developer_how_to_guide). Here's an example implementation for Rails: https://gist.github.com/fred/2539565

If you want to add it to your own Chrome instance on your machine, you can follow these instructions: http://www.makeuseof.com/tag/create-custom-search-engines-google-chrome/, using `https://supermarket.chef.io/cookbooks?q=%s` for the URL. Other browsers let you do similar things.

**Comment by nellshamrell** [comment]
Thank you again!  We've been doing some year end clearing of issues and have decided not to proceed forward with this one at this time.  If this continues to be an issue for you, however, please feel free to re-open this pull request!
