### ISSUE TITLE
Adding a new contributor to a cookbook gives a 404

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1122]
On the cookbook page when you select "add collaborator" and give a user name you get a 404 on the post.

**Comment by nellshamrell** [comment]
Hi @tas50,

I just attempted to add a collaborator to one of my Supermarket cookbooks and it seems to work fine.  I have a few questions
1) Can you link me to the cookbook you are attempting to add a collaborator too?
2) Are you seeing this error when you are adding a collaborator to a cookbook that you are the owner of?
3) Are you attempting to add a collaborator as an admin user on public Supermarket?

Thanks!

**Comment by tas50** [comment]
I'm attempting to add myself to yum-fedora using my account which is an admin on the public supermarket.

**Comment by nellshamrell** [comment]
TY, investigating further.

**Comment by nellshamrell** [comment]
I was able to replicate this locally, and this is the error I received.  Continuing to investigate.
![screen shot 2015-09-15 at 4 39 16 pm](https://cloud.githubusercontent.com/assets/813007/9892932/65548fb0-5bc8-11e5-89ee-ebd50243500f.png)

**Comment by nellshamrell** [comment]
According to the code's current behavior, admin Supermarket users are not allowed to add collaborators to repos they do not own.  This is NOT, however, the intended behavior.  Fixing.

**Comment by nellshamrell** [comment]
This line is the key: https://github.com/chef/supermarket/blob/master/app/authorizers/collaborator_authorizer.rb#L18
