### ISSUE TITLE
Sharing a cookbook as admin fails

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1124]
Now that my account on supermarket has been set as an admin I'm having odd issues sharing a cookbook.  I'm attempting to release a new firefox cookbook, but it's failing at the moment:

knife cookbook site share firefox -o .
Generating metadata for firefox from /var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chef-firefox-build20150916-85958-t5wfk3/firefox/metadata.rb
Making tarball firefox.tgz
ERROR: Authentication failed due to an invalid public/private key pair. If you have changed your keys recently try logging out and logging back in to Supermarket.

I attempting to download my key again, but even with the fancy new key it fails

**Comment by tas50** [comment]
Working now after reset in manage.

**Comment by nellshamrell** [comment]
:+1:
