### ISSUE TITLE
(chef_oauth2) Authentication failure! csrf_detected

### ISSUE THREAD

**Issue by lylianmeyemezu** [chef/supermarket#1128]
Hi, i am setting a private supermarket as described in https://www.chef.io/blog/2015/04/21/setting-up-your-private-supermarket-server/

when i try to autorize supermarket application, i got the errror 
I, [2015-09-18T14:15:37.933123 #11454]  INFO -- : (chef_oauth2) Callback phase initiated.
E, [2015-09-18T14:15:37.933530 #11454] ERROR -- : (chef_oauth2) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

Regards

**Comment by nellshamrell** [comment]
Hi @lylianmeyemezu - what version of Chef Server are you using?

**Comment by nellshamrell** [comment]
And what version of the Supermarket package?

**Comment by nellshamrell** [comment]
One final question - what is the content of your /etc/opscode/chef-server.rb file on your Chef server?

**Comment by lylianmeyemezu** [comment]
Hi,
Sorry for the delay.
Chef Version: 12.4.1
supermarket              2.0.2-alpha.0
oc_id['applications'] = {
  'supermarket' => {
    'redirect_uri' => 'https://ec2-54-77-131-145.eu-west-1.compute.amazonaws.com/auth/chef_oauth2/callback'
  }
}
oc_id['administrators'] = ['sd2_chefadmin','lmeyemezu','rbertrand','lbethune']

regards

**Comment by nellshamrell** [comment]
TY!   And no problem on the delay :)

One more question, what is the output of /etc/opscode/oc-id-applications/supermarket.json on your Chef server?

It should be something like:
{
  "name": "supermarket",
  "uid": "134324",
   "secret": "11243123",
    "redirect_uri": "https://supermarket-hostname/auth/chef_oauth2/callback"
}

If it is not, try running sudo chef-server-ctl reconfigure, then look at the output of the file again.  Those are the tokens you will need to use for Supermarket to be able to authenticate using oc-id.

Let me know how it goes!

**Comment by lylianmeyemezu** [comment]
Hi,
I've found a workaround in https://github.com/chef/supermarket/issues/1005
1. Go to the supermarket site.
2. Click "sign in"
3. Get redirected to the "authorize this application" page.
4. Click 'Yes'
5. Seems to be working.
Regards

**Comment by nellshamrell** [comment]
Glad it's resolved for you!
