### ISSUE TITLE
Feature: Specify Github Enterprise url 

### ISSUE THREAD

**Issue by RLIndia** [chef/supermarket#1130]
Currently there is no option to specify Github Enterprise URL in order to manage profiles. By default it goes to Github.com. Some feature can be added to specify the url of github to be used with supermarket.

**Comment by nellshamrell** [comment]
Related #867

**Comment by jbruettcva** [comment]
What's the status of this request?  we are about to deploy internal Supermarket and Github Enterprise.  This would be super useful.

**Comment by tas50** [comment]
This would be a useful addition. Add a new config for github_url and default it to https://github.com

**Comment by antima-gupta** [comment]
This feature covered in this PR[#2232](https://github.com/chef/supermarket/issues/2232)
