### ISSUE TITLE
Case-sensitivity in Curry::RepositoryMaintainersWorker

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1149]
Found in the Sidekiq logs:

```
WARN: {"class"=>"Curry::RepositoryMaintainersWorker",
              "args"=>[],
              "error_message"=>"Validation failed: Email can't be blank",
              "error_class"=>"ActiveRecord::RecordInvalid",
              ...}
WARN: Validation failed: Email can't be blank
WARN: /opt/supermarket/embedded/service/supermarket/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/validations.rb:57:in `save!'
...
/opt/supermarket/embedded/service/supermarket/app/workers/curry/repository_maintainers_worker.rb:21:in `perform'
```

As a review [`Curry::RepositoryMaintainersWorker`](https://github.com/chef/supermarket/blob/2.1.0-alpha.0/app/workers/curry/repository_maintainers_worker.rb) polls GitHub repositories registered as to-be-monitored by Curry, pulls the repo's `MAINTAINERS.toml`, and if present parses the maintainers file for GitHub user names of people designated as maintainers. It looks up Supermarket Users by GitHub username found in `MAINTAINERS.toml` and associates those Supermarket Users with Curried repositories.

Because the `MAINTAINERS.toml` is user-entered data _and_ data-structure, the worker's current logic only handles the maintainer user data if entered fairly specifically.

## Case-Sensitivity No. 1: the "GitHub" key in the TOML

The worker expects `toml[people][person]['GitHub']` with that very specific capitalization of 'GitHub'. The GitHub key for people has been entered in a variety of capitalizations over the various Curried repositories. The [worker's TOML GitHub lookup](https://github.com/chef/supermarket/blob/2.1.0-alpha.0/app/workers/curry/repository_maintainers_worker.rb#L55) should deal with the various capitalizations. A possibly-dirty solution could be:

```ruby
  def github_user(name)
    people[name]['GitHub'] || people[name]['github'] || people[name]['Github']
  end
```

## Case-Sensitivity No. 2: the GitHub username

The worker [looks up Supermarket Users by the GitHub username](https://github.com/chef/supermarket/blob/2.1.0-alpha.0/app/workers/curry/repository_maintainers_worker.rb#L46) found in a repo's `MAINTAINERS.toml`. This is a case-sensitive query to the database and will fail to find the User if the case of the username in the TOML does not match the case of the username stored in the User's github-associated Account record. It will also fail to find the User if they have not associated their GitHub account with their Supermarket account.

In either case of being unable to find the person, a User record is returned with all attributes set to `nil`. This is what triggers the `ActiveRecord::RecordInvalid` error logged above. The worker probably needs a guard around finding people and moving on when not found.

### Potentially Larger Issue

Because GitHub usernames are not case-sensitive, we should consider down-casing the storage of it and any lookups of it.

## Break up the band?

A more invasive change than—and in addition to—those described above might be considered: dispatch a separate worker for each Curried repository. The current implementation of a single pass over a collection of repositories means that a failure in processing a single repository—likely because Curry is relying on human input—means the entire job for all repos must be retried which will fail again on the first problematic repository. The repos that follow the problematic one miss out. A worker to process per repository would also ease troubleshooting because the repository in question could be found in the worker's args.

**Comment by robbkidd** [comment]
@nellshamrell @thommay I'd appreciate a read on my assessment here. Thanks!

**Comment by thommay** [comment]
Yeah, the parsing is very specific to the `MAINTAINERS.toml` I wrote for chef/chef. 

I think the dirty approach to part 1 is probably fair enough - if you don't manage to get one of those three, you probably don't deserve to have maintainers :)

+1 to downcasing the github username.

We (you :) ) should definitely dispatch a worker for each repo; we've got a lot of repos curried now!

**Comment by robbkidd** [comment]
Related: a count of the variant capitalizations of 'GitHub' across Curried repos:

```
> counts
=> {"Github"=>2, "GitHub"=>26, "github"=>320}
```

**Comment by nellshamrell** [comment]
Can we use a case insensitive regex?  i.e. /github/i

**Comment by robbkidd** [comment]
Maybe? Case No 1 involves indexing into the data structure returned by the Toml parsing.

(Also, it occurs to me that I should have spread these cases across 3 issues. Sorry for jamming them together just because they're all in the same worker.)

**Comment by robbkidd** [comment]
In light of adopting DCO, closing this issue since Curry will soon be deprecated.
