### ISSUE TITLE
chef server not generating oc_id info for supermarket

### ISSUE THREAD

**Issue by brendon-martino** [chef/supermarket#1158]
I'm following this guide:
http://irvingpop.github.io/blog/2015/04/07/setting-up-your-private-supermarket-server/

After 'chef-server-ctl reconfigure', you should find the OAuth2 data in /etc/opscode/oc-id-applications/supermarket.json
{
  "name": "supermarket",
  "uid": "0bad0f2eb04e935718e081fb71e3b7bb47dc3681c81acb9968a8e1e32451d08b",
  "secret": "17cf1141cc971a10ce307611beda7f4dc6633bb54f1bc98d9f9ca76b9b127879",
  "redirect_uri": "https://supermarket.mycompany.com/auth/chef_oauth2/callback"
}

However, chef-server-ctl reconfigure does not create that json, nor the directory.
There are no errors on output. Full output here:
https://gist.github.com/brendon-martino/adb81a54f5db9974e0a9

The chef server is fully functional as expected, otherwise. It is in an HA cluster, but is the only frontend server (+2 backends, and an elb). 

```
cat /opt/opscode/version-manifest.txt  | grep chef-server
chef-server 12.2.0
```

The supermarket server was stood up manually from rpm (I can't use the supermarket omnibus cookbook until I get the oc_id info).

I also don't see any errors in the logs (/var/log/opscode/*)

Any idea what could be wrong, else where to look for clues?

**Comment by brendon-martino** [comment]
This is the code that *should* be outputting what I need:

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/oc_id.rb#L161

#Take the existing oc_id.applications (with only a redirect_uri), ensure they
#exist in the database, and dump their data to /etc/opscode/oc-id-applications.
node['private_chef']['oc_id']['applications'].each do |name, app|
     oc_id_application name do
        redirect_uri app['redirect_uri']
          only_if { is_data_master? }
      end
end


I'm guessing it has something to do with the guard that defines: is_data_master? ...

**Comment by brendon-martino** [comment]
Just to prove that this was the issue, I commented out line:
https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/oc_id.rb#L165

in the local cookbook on the chef-server: /opt/opscode/embedded/cookbooks/private-chef/recipes/oc_id.rb

And reran: ```chef-server-ctl reconfigure```

And this worked. It created the oc-id-applications directory.

So now, I just need to figure out *why* the *is_data_master?* value was not set as I expected it.

**Comment by robbkidd** [comment]
@brendon-martino What's the topology set to in `/etc/opscode/chef-server.rb`? That's apparently [what determines](https://github.com/chef-cookbooks/enterprise-chef-common/blob/0.5.1/libraries/helpers.rb#L41) if a chef server node `is_data_master?` or not.

**Comment by brendon-martino** [comment]
```topology 'ha'
```

**Comment by brendon-martino** [comment]
It's a HA cluster. Do you know where that fact is documented?

**Comment by robbkidd** [comment]
Er, which fact?

**Comment by brendon-martino** [comment]
Nevermind, I see it in the code...I'm wondering if we need to change anything on teh chef-server config side now...

**Comment by brendon-martino** [comment]
I think this is the problem: https://github.com/chef-cookbooks/enterprise-chef-common/blob/0.5.1/libraries/helpers.rb#L67

**Comment by robbkidd** [comment]
That would be the problem if you are trying to add an application by making the edits and reconfigure on a frontend node. I suspect it may be a matter of following the steps from the blog post—under the "oc-id setup on your Chef Server"—on the chef server node that acts as the primary backend server.

**Comment by brendon-martino** [comment]
Yeah, I just realized that. I think I was doing this on the wrong server. The backend primary is the correct one.  I'll re-try it on that server and should be successful. 

Thanks.

**Comment by robbkidd** [comment]
:+1:

**Comment by nellshamrell** [comment]
Hi Brendon!  Did this get straightened out for you?

**Comment by nellshamrell** [comment]
Closing this, @brendon-martino if this is still a problem please let us know and we will re-open.
