### ISSUE TITLE
Dependencies tab of a cookbook appears to only show for current version

### ISSUE THREAD

**Issue by drenalin23** [chef/supermarket#1159]
Using the rsyslog cookbook as an example of this bug.  If you look at version 3.0.0 of rsyslog, you'll see it is dependent on compat_resources.  If you use the pull down menu to switch to 2.2.0, it will continue to say it is dependent on compat_resources (even on page reload) - but in reality the source code for the 2.2.0 branch does not specify a dependency on compat_resources.

https://supermarket.chef.io/cookbooks/rsyslog/versions/2.2.0#dependencies

This leads to a confusing user experience.

**Comment by robbkidd** [comment]
Confirmed. I see the behavior as described. Will investigate. Thanks!

**Comment by robbkidd** [comment]
@drenalin23 Thanks for reporting this. I believe we have this fixed in the PR linked. Fix will be deployed to production this week.

**Comment by drenalin23** [comment]
Verified fixed from my tests!  Thank you for fixing.
