### ISSUE TITLE
CLI support for publishing tools

### ISSUE THREAD

**Issue by vinyar** [chef/supermarket#1166]
Bug: 
At the moment Supermarket API does not support publishing tools.

Solution:
It would be great if there was a `knife supermarket` command to share tools. Either via tag or subcommand. 

Also, since tools are unlikely to have metadata.rb, there should be a set of flags to add `source url`, `issues` and supported platforms, or a json that can carry relevant data.

**Comment by robbkidd** [comment]
@vinyar Could you provide an example of the command you wish you had? 

Like, "if only I could type `[       ]` and have my new tool appear in a supermarket!"

**Comment by Naveen2015** [comment]
I can upload cookbook to supermarket using UI, but cannot find similar command line to upload into Tools. Can you provide the syntax.

**Comment by Naveen2015** [comment]
I can upload cookbook to supermarket using command line, but cannot find similar command line to upload tools into supermarket. Can you provide the syntax.

**Comment by vinyar** [comment]
@robbkidd 
I would be ok with anything similar to below
* `knife supermarket share my_cookbookortool name_of_cookbookortool -tool
* `knife supermarket share my_cookbookortool name_of_cookbookortool tool
* `knife supermarket share my_cookbookortool name_of_cookbookortool -type tool
* `knife supermarket share my_cookbookortool name_of_cookbookortool -type tool -info_file 'c:\trash\my_info.rb'

my_info.rb can contain a file similar to metadata.rb found in cookbooks, where source, 
supports, source_url, issues_url, etc.. can be specified.

With the last example, the default value for the `-tool` parameter would be cookbook, unless otherwise specified. 

Possibly via tag:
Related issue: https://github.com/chef/knife-supermarket/issues/18

**Comment by nellshamrell** [comment]
This is a good idea, we will triage this (along with other work in our backlog) with our Product Owner in Q1.

**Comment by nellshamrell** [comment]
So it turns out that we do not keep artifacts of tools in Supermarket, we simply link to the Github repo for a tool.  Closing this for now, but we will keep the idea of having tools be artifacts and providing a CLI way of interacting with them in mind.

**Comment by vinyar** [comment]
I see. In that case, can we provide a way to populate that reference via CLI?

Presently, there is no way to add a tool or a reference to the tool via CLI. That means the tool publishing portion of the workflow can not be automated.

**Comment by robbkidd** [comment]
Would a curl command to post to the same URL that the form posts to work?

**Comment by vinyar** [comment]
Sorry, was on a PTO.
Sure, that'll work. I'll reopen the issue, but if that's in error, please feel free to re-close, i wont be offended :+1:

**Comment by vinyar** [comment]
We'll probably need CLI support for compliance profiles as well

**Comment by robbkidd** [comment]
Yes. That's an area that needs requirements fleshed out.

**Comment by misheska** [comment]
+1 We want to publish compliance profiles via Chef Delivery. Also we want the ability to use SSH URLs in github from Chef Compliance. InSpec makes a great drop-in replacement for tools like Sensu, and the only thing hindering its adoption here is that it's not easy to access compliance profiles in non-public GitHub repos or with our on-premis Supermarket.

**Comment by tas50** [comment]
I'm going to close this out at this point. The tools section is showing little value so we won't be investing in making it easier to publish these tools.
