### ISSUE TITLE
Cluster setup documentation

### ISSUE THREAD

**Issue by iroller** [chef/supermarket#1169]
Is there a recommended way of multiple nodes setup install for supermarket?

Is configuring s3 bucket for cookbooks enough?

**Comment by nellshamrell** [comment]
Hi @iroller!

Here is a link to some slides of a  presentation I gave on setting up a private Supermarket http://www.slideshare.net/NellShamrell/a-supermarket-of-your-own-running-a-private-chef-supermarket

Could you clarify what you mean by "multiple setup install"?  Are you thinking of an HA Supermarket setup?

**Comment by iroller** [comment]
Hi @nellshamrell . I've already found this one: https://docs.chef.io/supermarket.html#scale-out-and-ha, that answers my questions. Thanks!

**Comment by nellshamrell** [comment]
Glad to hear!  Feel free to reach out with any more questions :)
