### ISSUE TITLE
There should be a search option for Chef Partner Cookbooks

### ISSUE THREAD

**Issue by mattray** [chef/supermarket#1177]
It would be very helpful to be able to filter the search options to find Chef Partner Cookbooks. This should be available as a fixed URL, so people can link to the listing.

In support of ROAD-73 (Display quality metrics for each cookbook on the Supermarket)
![screenshot 2015-12-03 15 43 28](https://cloud.githubusercontent.com/assets/330023/11604284/5cbc3872-9ab0-11e5-922d-51003f14cc95.png)

**Comment by smith** [comment]
Is there any metadata about a cookbook that would let supermarket determine this? Right now given a cookbook on disk or on supermarket or github, how would I go about determining whether or not it is a Chef Partner Cookbook?

**Comment by nathenharvey** [comment]
@smith see also https://github.com/chef/supermarket/issues/1175
