### ISSUE TITLE
supermarket service user should be a system user

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1179]
The `supermarket` user created during the omnibus install should be a system user so that, among other reasons, it lives in the uid space that won't conflict with humans.

Possibly to address at same time: 
- `supermarket` user creation fails if `supermarket` group already exists.
- as a system user, set shell to `/bin/false`

**Comment by tas50** [comment]
This would be a solid security improvement worth investigating.

**Comment by tas50** [comment]
Fix merged
