### ISSUE TITLE
Memory corruption when using rails console on supermarket VMs

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1183]
Seeing a lot of these when attempting to use rails console on VMs with the supermarket omnibus package installed:

*** Error in `ruby': malloc(): memory corruption: 0x00007f5919aee010 ***

**Comment by nellshamrell** [comment]
This appears to be related to the 2.1.4 release, as I confirmed it does not happen in the 2.1.3 release.  Investigating further.

**Comment by nellshamrell** [comment]
NOTE: This only happens when there is actually data in the db, it does not happen when entering console without any data in the DB.

```
irb(main):001:0> User.all
=> #<ActiveRecord::Relation [#<User id: 1, first_name: "Nell", last_name: "Shamrell", created_at: "2015-12-15 22:35:29", updated_at: "2015-12-15 22:35:29", company: nil, roles_mask: nil, email: "nshamrell@chef.io", jira_username: nil, irc_nickname: nil, twitter_username: nil, public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQE...", install_preference: nil>]>
^C
*** Error in `ruby': malloc(): memory corruption: 0x00007fbd8bb1d010 ***
```

**Comment by nellshamrell** [comment]
Managed to get a full stack trace:

https://gist.github.com/nellshamrell/ae6b2e391496029290ed

**Comment by nellshamrell** [comment]
Something I noticed - with 2.1.4 we upgraded to Ruby 2.2.3

Yet, the backtrace shows the error coming from Ruby 2.2.0

**Comment by nellshamrell** [comment]
Might be related to our use of https://github.com/brianmario/yajl-ruby

**Comment by robbkidd** [comment]
Ruby 2.2.0 is probably a reference to Ruby 2.2.x's ABI version. Like
1.9.3's ABI version was 1.9.1 which confused folks to no end.

**Comment by robbkidd** [comment]
I see libpthread in that stack. That's something that was patched in Ruby
trunk and 2.2-dev since Ruby 2.2.3. That's also the patch I shimmed in to
omnibus-software's Ruby {2.1.7,2.2.3} to fix RHEL5, but only patched for
RHEL5.

**Comment by nellshamrell** [comment]
I tried downgrading to 2.2.2...got a different error when using console, but similar.
```
irb(main):001:0> User.all.
^C
^C
irb(main):002:0> User.all
=> #<ActiveRecord::Relation []>
^C
irb(main):004:0> ^C
^C
^C
irb(main):004:0> User.first
=> nil
*** Error in `ruby': free(): corrupted unsorted chunks: 0x0000000005fc59b0 ***
```
