### ISSUE TITLE
Increase visibility of adoption process by notifying followers when cookbook goes up for adoption

### ISSUE THREAD

**Issue by btm** [chef/supermarket#1184]
#1031 added the available for [adoption page](https://supermarket.chef.io/available_for_adoption), but you have to go off into the weeds to find it. (Under the temporary announcements drop down, or go off to 'Cookbooks' and scroll down to the bottom).

I've looked and I don't think these things happen currently:
* email followers when a cookbook is put up for adoption
* include a cookbook available for adoption notification in the cookbook activity on the home page
* include adopted cookbook events in the available_for_adoption page for 3-6 months.
* put dates on the available_for_adoption page that show when a cookbook was made adoptable both in date and time since date.

**Comment by nellshamrell** [comment]
@loganmeetsworld Feel free to ping me about this one when you are ready to work on it :)

**Comment by nellshamrell** [comment]
Things I think we can implement:
1) Emailing followers when cookbook put up for adoption
2) When cookbooks are put up for adoption, show this in the dashboard of followed cookbooks activity
3) Change adoptable cookbooks list to be chronological
4) Put date a cookbook was put up for adoption on the adoptable cookbooks page

**Comment by loganmeetsworld** [comment]
My current plan is to break this out into three different parts and take the following steps: 
1. Emailing followers when a cookbook goes up for adoption ✅
2. Adding `up_for_adoption_since` to the Cookbook model and replacing the `up_for_adoption` boolean currently in the model, handling these migrations. 
3. Refactoring out the `update` controller action into `update` and `adopt` actions in Cookbook. This will make all logic surrounding updating and putting up for adopting clearer and will work well with the cookbook/tools and the existing polymorphic path infrastructure.

**Comment by robbkidd** [comment]
![i love this plan](https://cloud.githubusercontent.com/assets/517302/15436807/a3e95abc-1e91-11e6-8938-c2f0505435ad.gif)

I love this plan. I'm excited to be a part of it.
