### ISSUE TITLE
Add delegated (un|re)subscribe methods to Curry::Repository?

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1192]
In troubleshooting curried repositories and their repo webhook subscriptions, it has been fiddly on the console to iterate over a collection of `Curry::Repository` objects and "manually" instantiate a `Curry::RepositorySubscriber` for each to deal with the subscription. An idea arises: because the subscriber only needs to know about a repo, add `subscriber`, `subscribe!`, `unsubscribe!`, and `resubscribe!` methods to `Curry::Repository`.

`repo.subscriber`—maybe a private method—would instantiate a `Curry::RepositorySubscriber` and the action methods would delegate to the same method in `subscriber`.

This would result in a curried repository knowing that it _can_ subscribe to things, but not how with the logic still over in the subscriber class.

**Comment by nellshamrell** [comment]
That sounds good an OO-friendly :)

**Comment by robbkidd** [comment]
In light of adopting DCO, closing this issue since Curry will soon be deprecated.
