### ISSUE TITLE
fieri feature documentation

### ISSUE THREAD

**Issue by fhanson** [chef/supermarket#1198]
Please document the configuration params required for a working example of the fieri feature.

**Comment by robbkidd** [comment]
Thanks for the report, Franklin. Cookbook quality metrics measurement—of which fieri is a part—is on the supermarket team's roadmap for the next few months (Q1 2016).

**Comment by nellshamrell** [comment]
Fieri is now a part of Supermarket, will be updating the Supermarket docs on how to configure Fieri

**Comment by nellshamrell** [comment]
Brief outline of configure Fieri:  

1) Add fieri to the ['supermarket_omnibus']['config']['features'] attribute.
```
['supermarket_omnibus']['config']['features'] = "tools,github,announcement,fieri"
```
2) Add the following Fieri attributes:
```
['supermarket_omnibus']['config']['fieri_key'] = "#{random string you generate}"
['supermarket_omnibus']['config']['fieri_supermarket_endpoint'] = "#{your_supermarket_url}"
['supermarket_omnibus']['config']['fieri_results_endpoint'] = "#{your_supermarket_url}/api/v1/cookbook-versions/evaluation"
```
3) Reconfigure your supermarket 
```
(your-supermarket-node) $ sudo supermarket-ctl reconfigure
```
4) And restart the supermarket services
```
(your-supermarket-node) $ sudo supermarket-ctl restart
```

**Comment by nellshamrell** [comment]
Verifying those, then submitting a pull request to docs.chef.io
