### ISSUE TITLE
Not authorized after logging in via Chef Server

### ISSUE THREAD

**Issue by SolverDude** [chef/supermarket#1200]
We're running chef server 12.0.3, and I've followed the instructions on the blog post to install supermarket on its own vm.

that looked to go well, and after it's up and i click 'Sign in', I'm taken to chef server for logging in.
After i do that, I land on a page listed 'Authorized Applications' with one entry, Analytics.  No buttons here.

Irving's earlier blog post referenced the page i expected to see about asking to authorize use of supermarket app.

When i try api access via knife supermarket, i get 'Could not find user <user>' (w my login).

Our chef server is HA setup with vm frontends load-balanced via bigip and physical servers for backend with failover.  I have NOT restarted the backend server, but i did the reconfigure as suggested (that's how i got the json with the secrets, etc).  The frontends WERE restarted after their reconfigure.

I'm a bit stumped on how to continue on my own.  Help!

**Comment by nellshamrell** [comment]
Hello @SolverDude (great github name, btw!),

I'm sorry you are experiencing that issue and I am investigating now.  I will update you by EOD if not before :)

**Comment by SolverDude** [comment]
Sure thing, Nell.  Thanks!  Fingers crossed it's trivial.  :-)

**Comment by nellshamrell** [comment]
Hello again!

Do you have the same oc-id settings in the chef-server.rb on all chef servers in the cluster?  And have you done a cluster-wide reconfig?

**Comment by SolverDude** [comment]
we have two frontends and one master backend (with an inactive non-master).  all have the same chef-server.rb.  All had chef-server-ctl reconfigure done.  I didn't push it to the idle non-master backend yet.

Both frontends were restarted after their reconfigure.  The backend wasn't restarted.

**Comment by nellshamrell** [comment]
At this time, I'll ask you to open a Support ticket so that we can further troubleshoot there.  Thanks for reporting this issue!

**Comment by SolverDude** [comment]
roger that!  Ticket https://getchef.zendesk.com/hc/en-us/requests/7793
