### ISSUE TITLE
How to organize private S3 storage for cookbooks

### ISSUE THREAD

**Issue by iroller** [chef/supermarket#1203]
So Supermarket is setting a public access for all uploaded cookbooks. (This is an odd default btw. I bet many people have no idea about it. Could make S3_PRIVATE_OBJECTS true by default.)

To make cookbooks private I can make a policy for s3 bucket that limits it to a specific IP range where my private supermarket is located. This way only supermarket can upload/download cookbooks.

After that I need berkshelf to be pointed at my private supermarket and being able to download cookbooks. Berks commands are executed from developer's computers which can be located all over the world (not in the IP range I provided).

How do I let developers download the cookbooks from private supermarket/amazon s3 without making them public? I'd appreciate any suggestions.

**Comment by nellshamrell** [comment]
Hello @iroller!

My first instinct is to suggest that your devs use a VPN, and that you add the VPN's address to your S3 policy.  I'm consulting with some of my fellow engineers on whether there is a better way and will update you shortly.

**Comment by nellshamrell** [comment]
Using a VPN or Proxy appears to be the general consensus.  Will that work for you or were you looking for a different solution?

**Comment by nellshamrell** [comment]
(Also, apologies for the delay in answering, I was out sick much of last week and the other Supermarket Engineer was in all day trainings)

**Comment by iroller** [comment]
Hi @nellshamrell ,

As an easier solution we have just switched to a local storage for cookbooks for now. Setting it all up with S3 being private seems to be too complex.

Thanks!
