### ISSUE TITLE
Unable to update an existing recipe

### ISSUE THREAD

**Issue by jessp01** [chef/supermarket#1221]
Hello,

When running:
\# knife cookbook site share -o /var/chef/cookbooks kaltura applications --user kaltura --server https://supermarket.chef.io -k ~/.chef/kaltura.pem -VV

I get:
```
Making tarball kaltura.tgz
DEBUG: Executing tar -czf kaltura.tgz kaltura
DEBUG: ---- Begin output of tar -czf kaltura.tgz kaltura ----
DEBUG: STDOUT: 
DEBUG: STDERR: 
DEBUG: ---- End output of tar -czf kaltura.tgz kaltura ----
DEBUG: Ran tar -czf kaltura.tgz kaltura returned 0
DEBUG: Signing: method: post, path: /api/v1/cookbooks, file: #<File:0x000000019918c0>, User-id: kaltura, Timestamp: 2016-02-04T16:30:25Z
ERROR: Error uploading cookbook kaltura to the Opscode Cookbook Site: lexical error: invalid char in json text.
                                       <html>  <head><title>301 Moved 
                     (right here) ------^
. Increase log verbosity (-VV) for more information.
DEBUG: 
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/yajl-ruby-1.2.0/lib/yajl.rb:37:in `parse'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/yajl-ruby-1.2.0/lib/yajl.rb:37:in `parse'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/json_compat.rb:56:in `from_json'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife/cookbook_site_share.rb:94:in `do_upload'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife/cookbook_site_share.rb:67:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife.rb:492:in `run_with_pretty_exceptions'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife.rb:174:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/application/knife.rb:135:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/bin/knife:25:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/knife:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/knife:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `<main>'
```

Up until now, I always used --server http://community.opscode.com but I Googling I got some results indicating it has changed to https://supermarket.chef.io

I also looked here:
https://docs.chef.io/api_cookbooks_site.html and tried passing:
--server https://supermarket.chef.io/api/v1/cookbooks

they all result in the same outcome.

Would appreciate any assistance.

Thanks,

PS
Apologies if this is the wrong place to report it, if so, kindly point me to the right place.

**Comment by nellshamrell** [comment]
Hi @jessp01!

Thanks for reporting this!  What happens if you do not specify a server with that command?  It defaults to http://supermarket.chef.io

**Comment by jessp01** [comment]
Hello Nell,

# knife cookbook site share -o /var/chef/cookbooks kaltura applications --user kaltura  -k ~/.chef/kaltura.pem -VV

Results in the same outcome, i.e:
Making tarball kaltura.tgz
DEBUG: Executing tar -czf kaltura.tgz kaltura
DEBUG: ---- Begin output of tar -czf kaltura.tgz kaltura ----
DEBUG: STDOUT:
DEBUG: STDERR:
DEBUG: ---- End output of tar -czf kaltura.tgz kaltura ----
DEBUG: Ran tar -czf kaltura.tgz kaltura returned 0
DEBUG: Signing: method: post, path: /api/v1/cookbooks, file: 
#<File:0x000000022be858>, User-id: kaltura, Timestamp: 
2016-02-07T16:41:06Z
ERROR: Error uploading cookbook kaltura to the Opscode Cookbook Site: 
lexical error: invalid char in json text.
                                        <html>  <head><title>301 Moved
                      (right here) ------^

DEBUG:
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/yajl-ruby-1.2.0/lib/yajl.rb:37:in 
`parse'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/yajl-ruby-1.2.0/lib/yajl.rb:37:in 
`parse'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/json_compat.rb:56:in 
`from_json'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife/cookbook_site_share.rb:94:in 
`do_upload'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife/cookbook_site_share.rb:67:in 
`run'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife.rb:492:in 
`run_with_pretty_exceptions'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/knife.rb:174:in 
`run'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/lib/chef/application/knife.rb:135:in 
`run'
/usr/local/rvm/gems/ruby-1.9.3-p545/gems/chef-11.12.2/bin/knife:25:in 
`<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/knife:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/knife:23:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in 
`<main>'

Can you perhaps take a look at the logs at your end to understand why it 
fails? As you can see, I am making the request in verbose mode but still 
not getting anything I see as helpful to understand the cause.

Thanks,


May the source be with you,

Jess Portnoy

Kaltura Connect Virtual Summits 2015 - now on VOD! [connect.mediaspace.kaltura.com]

**Comment by nellshamrell** [comment]
Hello...

**Comment by nellshamrell** [comment]
Ah, sorry, now I see the hidden output in your previous comment.  Taking a look.

**Comment by nellshamrell** [comment]
Thanks for the info.  What does the metadata.rb file look like in the cookbook you are trying to upload?  I think there might be something in it that isn't converting to json properly.

**Comment by jessp01** [comment]
Hi Nell,

See below. The exact same as the last version, apart from the version bounce to 25.0

```
maintainer       "Jess Portnoy, Kaltura, Inc."
maintainer_email "jess.portnoy@kaltura.com"
license          "AGPLv3+"
description      "Installs and configures Kaltura"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))

version          "25.0"



supports 'centos'
supports 'redhat'
suggests 'nfs'
suggests 'mysql'
```

Thanks,

**Comment by nellshamrell** [comment]
Hi @jessp01!  I'm wondering if we might be having some difficulties with your credentials.  Do you have time sometime this week for a quick video call?  That way I can watch the logs (we do not currently have log aggregating, unfortunately, it is something that is on our list) while you get the failure when sharing that cookbook.  I'm available after 2 PM Pacific Time all this week.

**Comment by nellshamrell** [comment]
@jessp01 - would you like to have a video call to troubleshoot your credentials?

**Comment by nellshamrell** [comment]
Closing this issue, @jessp01 if you continue to have this problem feel free to re-open this :)
