### ISSUE TITLE
Unable to search on mobile

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1226]
@cwebberOps reported that he cannot search for a cookbook via mobile.  

"There is no UI button and hitting the "search" keyboard key doesn't do anything"

![image](https://cloud.githubusercontent.com/assets/813007/12996005/ab7a2be8-d0e0-11e5-87b0-afbcf30b0b08.png)

**Comment by robbkidd** [comment]
Works on my Android. No UI button, but the 🔍 on the keyboard submitted the search form and got results.

![screenshot_2016-02-11-20-20-47](https://cloud.githubusercontent.com/assets/517302/12996409/80d0551c-d0fd-11e5-969d-1c615dde6749.png)

**Comment by robbkidd** [comment]
Apparently search didn't work in mobile Safari. Returning for us to consider during next triage.

**Comment by jlosito** [comment]
Any chance at revisiting this? I can confirm that it doesn’t work in Firefox on iOS.

**Comment by tas50** [comment]
This is fixed in 4.0
