### ISSUE TITLE
host attribute doesn't pick up custom value from fqdn attribute

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/supermarket#1232]
When a user wants to use a CNAME for their Supermarket server then they correctly configure `node.set['supermarket_omnibus']['config']['fqdn']` in the wrapper cookbook. However, when `supermarket-ctl reconfigure` gets run the [host attribute](https://github.com/chef/omnibus-supermarket/blob/2.3.3/cookbooks/omnibus-supermarket/attributes/default.rb#L324) is not getting set to the new value from the custom `fqdn` attribute.

```
$ jq '.supermarket.fqdn, .supermarket.host' /etc/supermarket/supermarket-running.json
"supermarket-test.lxc"
"8383-supermarket.lxc"
```

This causes problems especially when logging in because the Supermarket redirect url that gets passed to OC-ID is the original FQDN of the Supermarket server instead of the custom CNAME.

You can see in the screenshot below that the `redirect_uri` points to `8383-supermarket.lxc` when it should point to `supermarket-test.lxc`.

![screen shot 2016-02-24 at 4 36 49 pm](https://cloud.githubusercontent.com/assets/430911/13302020/b9f9dc38-db15-11e5-8048-afda2ed5f398.png)

This can be worked around by setting `node.set['supermarket_omnibus']['config']['host']` to the CNAME FQDN and running `supermarket-ctl reconfigure`.

Please make sure that the [host attribute](https://github.com/chef/omnibus-supermarket/blob/2.3.3/cookbooks/omnibus-supermarket/attributes/default.rb#L324) properly picks up a custom value for the `fqdn` attribute.

**Comment by nellshamrell** [comment]
Ran into this today myself and I definitely feel your pain.  Will get to this as soon as possible.
