### ISSUE TITLE
"Recently Updated" cookbooks list should only list recently shipped

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1244]
Right now if you edit a cookbooks metadata on supermarket it shows up as being recently updated at https://supermarket.chef.io/cookbooks-directory

It seems like what people would really care about on this page is new cookbooks that have shipped.  We should only be showing a cookbook as being updated when the author ships a new version.  Adding issues URL or something like that shouldn't trigger it to the front page for everyone to see.

**Comment by nellshamrell** [comment]
To reproduce:
1) Go to a cookbook you own on Supermarket
2) Click on "Details" in the right hand pane
3) Add/remove/edit the source_url or issues_url
4) Head to https://supermarket.chef.io/cookbooks-directory and you will see that cookbook listed in the "Recently Updated" column

Desired behavior:
1) Go to a cookbook you own on Supermarket
2) Click on "Details" in the right hand pane
3) Add/remove/edit the source_url or issues_url
4) Head to https://supermarket.chef.io/cookbooks-directory and you will NOT see that cookbook listed in the "Recently Updated" column
5) Make a change to the cookbook on your workstation and upload a new version (incrementing the version number)
6) Head to https://supermarket.chef.io/cookbooks-directory and you will see that cookbook listed in the "Recently Updated" column

We should only show a cookbook in the "Recently Updated" column if a new version has been released.

**Comment by nellshamrell** [comment]
@tas50 if anything in the above comment looks amiss please let me know

**Comment by nellshamrell** [comment]
Did some research on this.  

The column that looks like this: 
![screen shot 2016-04-21 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/813007/14725335/421be354-07d0-11e6-84c9-5eb21a984b7f.png)

Is coded in the [cookbooks/directory view](https://github.com/chef/supermarket/blob/master/src/supermarket/app/views/cookbooks/directory.html.erb)

We use the @recently_updated_cookbooks instance variable
![screen shot 2016-04-21 at 2 50 56 pm](https://cloud.githubusercontent.com/assets/813007/14725410/a6b88362-07d0-11e6-83a9-b8018fd3b9c8.png)

This variable is set in the [CookbooksController](https://github.com/chef/supermarket/blob/master/src/supermarket/app/controllers/cookbooks_controller.rb)
<img width="560" alt="screen shot 2016-04-21 at 2 53 16 pm" src="https://cloud.githubusercontent.com/assets/813007/14725440/ce977668-07d0-11e6-91d7-18c85d4caa8d.png">

Which uses a scope from the [Cookbook Model](https://github.com/chef/supermarket/blob/master/src/supermarket/app/models/cookbook.rb)
<img width="956" alt="screen shot 2016-04-21 at 2 54 20 pm" src="https://cloud.githubusercontent.com/assets/813007/14725482/01230340-07d1-11e6-89a4-3740322c8c28.png">

We need to change that scope (or how we use it) to show only cookbooks who have had new versions published (a cookbook has many cookbook_versions).
