### ISSUE TITLE
"full" logoff using /id redirecting to supermarket URL instead chef-server URL

### ISSUE THREAD

**Issue by dfduarte** [chef/supermarket#1249]
Hello there!

I'm using a local Supermarket+Chef-Server installation (installed using the RPM, due to some omnibus installer bugs), and I've configured everything manually.

Everything works well, Cookbooks are shared with success and ok, but there is a little issue that is annoying me a lot:

When the user go to logout link, he disconnects from Supermarket, and the interfaces gives the option to do a "total logoff", by clicking on a link that redirects to https://chef.server.youserver.com/id, and going to logoff on this OAUTH2 screen. The problem here, is that interface is not working properly, and the "/id/ link shown is redirecting to the supermarket url (supermarket.youserver.com/id), instead of chef-server.

There is something specific to set up on supermarket.rb, or something else?

**Comment by robbkidd** [comment]
@dfduarte Is this banner the "total logoff" option you mean?

<img width="1169" alt="screen shot 2016-03-22 at 5 35 49 pm" src="https://cloud.githubusercontent.com/assets/517302/13968721/9e052600-f054-11e5-9e4d-8e4fb42a4533.png">

**Comment by dfduarte** [comment]
Yeay, that's right @robbkidd

**Comment by robbkidd** [comment]
OK. The [link the banner presents](https://github.com/chef/supermarket/blob/master/app/views/pages/welcome.html.erb#L7) defaults to `https://api.chef.io/id` unless [overridden by some environment variables](https://github.com/chef/supermarket/blob/master/app/helpers/custom_url_helper.rb#L37): `ENV['CHEF_SERVER_URL']` and/or `ENV['CHEF_IDENTITY_URL']`. If you've configured things manually, you could set these in the `.env` file at the root of the web app. (I am not sure where that root is on your host if you have not used the omnibus package.)

**Comment by dfduarte** [comment]
@robbkidd Thank you so much man, it worked!

I don't have realized that the chef_identitiy_url parameter on /var/opt/supermarketet/etc/env is intended for this configuration. (Actually, this is not well documented, so I didn't found so much about this problem). Yeay, I know... The installation is focused on cookbook or omnibus, but anyway...

**Comment by robbkidd** [comment]
I am intrigued by the omnibus installer bugs you ran into if you are interested in opening an issue about them. We're working on improving the docs which, as you say, are at first focused on customizing the cookbook install of the omnibus package. 

Glad you've got it working! :confetti_ball:
