### ISSUE TITLE
Investigate API

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1276]
To see if there is a way to add/remove collaborators

**Comment by jvrplmlmn** [comment]
@nellshamrell what was the output of this issue?

**Comment by nellshamrell** [comment]
We concluded that there is not a way to do this at this time and we won't be looking into adding it within the next 6 months.

**Comment by nellshamrell** [comment]
We would, of course, be willing to revisit this if we get feedback from users on the need and workflows the feature would support
