### ISSUE TITLE
Empower Curry to maintain the collaborators on a cookbook mapped to a Curried repository

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1277]
Curry already knows about a project's maintainers and their GitHub logins from a project's MAINTAINERS.toml. Currently, Curry uses this to assign new pull requests to project maintainers. This is a feature request to add to Curry the management of cookbook collaborators based on entries in the MAINTAINERS.toml. This would require a new association between a Cookbook and a Curry::Repository

**Comment by robbkidd** [comment]
Discussed today as a feature that could be useful in the administration of a cookbook and keeping the maintainers documentation up-to-date. Currently needs vetting by @nathenharvey and some more pondering around what's it look like now / what will it look like when it's done.

**Comment by nellshamrell** [comment]
@nathenharvey, could you weigh in?

**Comment by robbkidd** [comment]
In light of adopting DCO, closing this issue since Curry will soon be deprecated.
