### ISSUE TITLE
Troubleshoot Javascript specs

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1282]
I've been receiving reports of rake spec:javascripts failing and suspect it may be due to changes in XCode with El Capitan on Mac OS X.  Troubleshoot.

**Comment by robbkidd** [comment]
Coincided with the omnibus consolidation.

**Comment by robbkidd** [comment]
```
INFO [karma]: Karma v0.10.10 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket qEhVcaX2NP5lWaoHntDE
.
PhantomJS 1.9.8 (Linux): Executed 1 of 1 SUCCESS (0.81 secs / 0.508 secs)
```

... means our [one JavaScript spec](https://github.com/chef/supermarket/blob/master/src/supermarket/spec/javascripts/application/flashSpec.js) _is_ being run and tested in Travis. The test is prefaced with scary warnings. And the tests don't run on Mac dev environments.

JS specs were not run in Travis until the app/omnibus consolidation and me thinking that they ought to be. Working on a solution to the warnings in Travis and _working_ on Macs.
