### ISSUE TITLE
CCLA Issue

### ISSUE THREAD

**Issue by echohack** [chef/supermarket#1288]
Hello,

I noticed that the CCLA on supermarket mentions a Schedule A and Schedule B but we don’t list these in the CCLA itself. The CCLA is based off the Apache CCLA, and should probably include these at the end:

https://www.apache.org/licenses/cla-corporate.txt
```
Schedule A

   [Initial list of designated employees.  NB: authorization is not
    tied to particular Contributions.]

Schedule B

   [Identification of optional concurrent software grant.  Would be
    left blank or omitted if there is no concurrent software grant.]
```

According to legal at Chef we should include both of these in the Supermarket CCLA.

**Comment by robbkidd** [comment]
I am assuming this is for organizations printing a hard copy of the CCLA.

For electronic signatures through the Supermarket, Schedule A is implemented as the CCLA administrators for an organization inviting the "designated employees" to join their CCLA via Supermarket web form.

Still keep Schedule B?

**Comment by echohack** [comment]
@robbkidd Yes keep BOTH Schedule A and Schedule B

**Comment by robbkidd** [comment]
OK. A multi-step plan:

* Review [the content](https://supermarket-staging.chef.io/ccla-signatures/agreement) having been appended to the body of the CCLA in Staging.

* If that looks good, I will make the same content change in [production](https://supermarket.chef.io/ccla-signatures/agreement).

* Then I'll submit a PR making the same content change to [the seed file responsible for putting the current CCLA into the database](https://github.com/chef/supermarket/blob/master/src/supermarket/db/seeds/ccla/body.md).

**Comment by echohack** [comment]
I took at look at the proposed change and this looks correct! I think will cause less confusion for our customers! Thank you!!!

**Comment by robbkidd** [comment]
[Production CCLA body](https://supermarket.chef.io/ccla-signatures/agreement) updated.
