### ISSUE TITLE
Research mounting Fieri as a Rails Engine

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1294]
https://github.com/chef/fieri

**Comment by robbkidd** [comment]
Totally doable. Possibly-reusable-spike in branch https://github.com/chef/supermarket/tree/fieri-as-engine

Fieri has two parts:
- web end point for Supermarket to say "hey, here's a new cookbook version to evaluate"
- a worker to do the evaluation

### Why to make fieri a Rails Engine:

😞  Currently, deploying fieri involves a whole separate cookbook to deploy web services, Sidekiq worker processor, and Redis to a separate host. Comms between Supermarket and separate Fieri are beset—especially in private installs—with problems with FQDN resolution and additional SSL cert needs.

😃  Implementing fieri as a Rails engine that is included ("mounted") within Supermarket removes all the additional deployment and operational effort of a separate codebase.

* Included in Supermarket as a gem, a fieri Rails engine automatically becomes a part of the existing omnibus package.
* No additional deployment needs to provide a load balancer, web server, or SSL cert for a separate web service. The fieri web endpoints become endpoints in already running Supermarket web hosts.
* Automatically uses Supermarket's configured Sidekiq workers and Redis The fieri worker becomes just another job in the Sidekiq job processor already deployed as part of Supermarket.
* Scaling Supermarket web/worker tier also scales Fieri web/workers.

### operational concerns

* disk requirements - Fieri requires temporary disk space to untar and then foodcritic a cookbook tarball, flaws in fieri cleaning up after itself could fill a partition
* running foodcritic on Supermarket web nodes opens web nodes to security vulnerabilities in foodcritic - could be slightly mitigated by deployment/configuration changes that specify which services to run on which nodes. e.g. web nodes have [Sidekiq disabled](https://github.com/chef/supermarket/blob/master/omnibus/cookbooks/omnibus-supermarket/attributes/default.rb#L226) and worker nodes have web services disabled [1](https://github.com/chef/supermarket/blob/master/omnibus/cookbooks/omnibus-supermarket/attributes/default.rb#L99) [2](https://github.com/chef/supermarket/blob/master/omnibus/cookbooks/omnibus-supermarket/attributes/default.rb#L198)

**Comment by robbkidd** [comment]
We have decided to do this for the reasons above. Being worked on #1303.
