### ISSUE TITLE
Markdown Syntax highlighting for specific language not being honored

### ISSUE THREAD

**Issue by aaronblythe** [chef/supermarket#1302]
Appears that language specific markdown is not rendering properly on SuperMarket.

Example:

It you compare the markup generated from the README.md https://github.com/bmhatfield/chef-ulimit you will see the resource as `ruby` code with highlighting.

    ```ruby 
    ...
    ```

In Supermarket (https://supermarket.chef.io/cookbooks/ulimit#readme) currently this shows the `ruby` instead of rendering the code as ruby.  Then highlighting the code as opposed to displaying a code block.

https://help.github.com/articles/creating-and-highlighting-code-blocks/ in the section on `Syntax highlighting` there is is some discussion on how the language specific code highlighting should work.

**Comment by aaronblythe** [comment]
Looks like you can continue to use Red Carpet and just set to render GFM.

http://stackoverflow.com/questions/15687599/ruby-markdown-interpreter-with-syntax-similar-to-github-flavored-markdown

**Comment by robbkidd** [comment]
Related to other issues that boil down to "Supermarket's Markdown renderer is not GitHub-flavored." Closing this issue and rolling it up under #1321.
