### ISSUE TITLE
Add ability to disable calls to 3rd parties in view rendering

### ISSUE THREAD

**Issue by galenemery** [chef/supermarket#1305]
In airgapped/secure environments, calls out to 3rd parties are not allowed.  As it stands right now, supermarket attempts to reach out to several sites, including googleapis.com and others (https://github.com/chef/supermarket/blob/master/src/supermarket/app/views/layouts/application.html.erb#L17-L22)

Can we get the ability to turn these calls on/off so Supermarket can run error-free inside of secured environments?

**Comment by robbkidd** [comment]
Some options:

1. Wrap the [layout's inclusion of Font Awesome and Montserrat fonts](https://github.com/chef/supermarket/blob/master/src/supermarket/app/views/layouts/application.html.erb#L17-L20) in a feature flag (e.g. `ROLLOUT.active?(:use_cdns)`). Disable the feature and the site uses a standard web font and many icons disappear from the UI.
    * advantages: 
        * simple code
    * disadvantages:
        *  icons disappear from the UI (platform icons will still appear), unsure of how much information is being conveyed with only icons 
2. Package the Montserrat and Font Awesome fonts and associated CSS styling into the web app **and only use those**
    * advantages:
        * simple code, some of which is optionally already [available as a gem](https://github.com/bokmann/font-awesome-rails)
        * airgapped users get to see all the icons
    * disadvantages:
       * maintenance burden (small) of another gem dependency or of vendoring assets and keeping them up-to-date
       * Supermarkets for users that have access to the internet will be busy serving up assets that are probably already cached in the users' browsers from a CDN
3. Package the Montserrat and Font Awesome fonts and associated CSS styling into the web app **and wrap their use in a feature flag that toggles whether to retrieve them from a CDN**
    * advantages:
        * reduced web request load on Supermarket from users who aren't air-gapped
        * airgapped users get to see all the icons, too
    * disadvantages:
        * maintenance burden (small) of vendoring assets and keeping them up-to-date
        * along with the branching logic of a feature flag to decide which set of assets to use

**Comment by nathenharvey** [comment]
The ideal solution I'd like to see is:

1.  Package everything.
1.  Notify when upstream packages change.
1.  Update package from upstream.
1.  Push change through our change pipeline.

I'd like to recommend a time-boxed exploration of this issue to see what can be accomplished in a day or less.  Of @robbkidd's options above, number 3 is probably the best initial implementation.

**Comment by nellshamrell** [comment]
Possible first steps:
Include font awesome gem, serve up font ourselves, consider not using custom font

Possible second steps:
Make switchable flag on whether to use font from a CDN or not.

**Comment by robbkidd** [comment]
This plus a `bundle install` got me working in the research spike, but not thoroughly tested/vetted.

```diff
diff --git a/src/supermarket/Gemfile b/src/supermarket/Gemfile
index 3612d13..31e8f9d 100644
--- a/src/supermarket/Gemfile
+++ b/src/supermarket/Gemfile
@@ -61,6 +61,7 @@ gem 'sass-rails',   '~> 4.0.4'
 gem 'sass-globbing'
 gem 'compass-rails'
 gem 'uglifier',     '~> 2.7'
+gem 'font-awesome-rails'

 group :doc do
   gem 'yard', require: false
* Unmerged path src/supermarket/Gemfile.lock
diff --git a/src/supermarket/app/assets/stylesheets/appheader.scss b/src/supermarket/app/assets/stylesheets/appheader.scss
index 7781618..c834b20 100644
--- a/src/supermarket/app/assets/stylesheets/appheader.scss
+++ b/src/supermarket/app/assets/stylesheets/appheader.scss
@@ -36,8 +36,6 @@
   width: rem-calc(55);
   z-index: 1;

-  &:before { display: block; margin-top: rem-calc(43); }
-
   &:visited { color: adjust-lightness($concrete, 10%); }
   &:hover { color: adjust-lightness($concrete, 20%); }
 }
diff --git a/src/supermarket/app/assets/stylesheets/application.css.scss b/src/supermarket/app/assets/stylesheets/application.css.scss
index 8caa92f..402bf0d 100644
--- a/src/supermarket/app/assets/stylesheets/application.css.scss
+++ b/src/supermarket/app/assets/stylesheets/application.css.scss
@@ -6,6 +6,7 @@
 *= require normalize
 *= require foundation
 *= require select2
+*= require font-awesome
 *
 * Supermarket Styles
 *
diff --git a/src/supermarket/app/views/layouts/application.html.erb b/src/supermarket/app/views/layouts/application.html.erb
index 1bfaa81..33c2d94 100644
--- a/src/supermarket/app/views/layouts/application.html.erb
+++ b/src/supermarket/app/views/layouts/application.html.erb
@@ -15,7 +15,6 @@
     <link rel="apple-touch-icon" href="<%= image_url('apple-touch-icon.png') %>"/>
     <%= stylesheet_link_tag "application", media: "all" %>
     <% unless Rails.env == 'test' %>
-      <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" %>
       <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Montserrat:400,700" %>
     <% end %>
     <%= csrf_meta_tags %>
```

**Comment by nellshamrell** [comment]
Testing and vetting :)

**Comment by nellshamrell** [comment]
Well, that gets rid of one of them, but we are still calling out to 
//fonts.googleapis.com/css?family=Montserrat:400,700"
'google_analytics'

Spiking on adding in a config flag for those.

**Comment by robbkidd** [comment]
Yea. That's the font that I wonder if the use of it in the design is worth the complexity of vendoring it and a feature flag to serve it up ourselves or from a CDN. In my dev environment, the site didn't look dramatically different when I just removed that Montserrat line.

**Comment by nellshamrell** [comment]
Should we still have the feature flag for google analytics?

**Comment by robbkidd** [comment]
We sort of do already. Hidden in [the partial for Google Analytics](https://github.com/chef/supermarket/blob/master/src/supermarket/app/views/application/_google_analytics.html.erb#L1), it only includes GA content if there is a `GOOGLE_ANALYTICS_ID` set in the environment.

**Comment by nellshamrell** [comment]
After discussion and consultation with our style guidelines...we're going to add in a feature flag for the Montserrat font.  This feature flag should only be used in air-gapped environments.  This means that what would normally be Montserrat WITHOUT the feature flag will now instead be the default font WITH the feature flag.  Appearance will be slightly different in air gapped in environments, but still completely legible.  Outside of an air gapped environment, the Supermarket fonts will be in compliance with style.chef.io.
