### ISSUE TITLE
Quality Metrics: A user can see quality metrics on all cookbook versions on Supermarket

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1309]
As a user
When I access Supermarket
And view a cookbook version
I see a “Quality” tab
I do not see a “Foodcritic” tab
When I click on the tab
When the cookbook version has results
I see a list of metric results
When the cookbook version does not have results
I see a message “No results found”

- [ ] Change Foodcritic tab to Quality tab
- [ ] Remove checkbox/red x that shows whether a cookbook version has passed food critic from the Quality tab

**Comment by loganmeetsworld** [comment]
Should we add to these checkboxes anything about showing the message “No results found” and removing the nil part since every user will see this tab?

**Comment by loganmeetsworld** [comment]
Something like
- [ ] Remove qualification that Foodcritic must be present in order to see the tab, add a message if there are no Foodcritic results in the content of the tab.
