### ISSUE TITLE
Quality Metrics: An admin can see whether the number of collaborators >= 1 as a quality metric

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1311]
As an admin user
When I log into Supermarket
And view a cookbook version
And I click on the “Quality” tab
And the number of collaborators is >=1
Then I see that the “Number of collaborators” metric has passed
When the number of collaborators <=1
Then I see that the metric has failed

- [x] Add logic to determine total number of collaborators
- [x] Research interface (api calls?) between Fieri and Supermarket to determine whether this metric has passed
- [x] Expand Supermarket's api to cooperate with Fieri - maybe add additional API client
- [x] Research how to incorporate collaborator results into results record stored for a cookbook version
- [x] Incorporate collaborator results into results record stored for a cookbook version
- [x] When total number of collaborators passes, show happy message
- [x] When total number of collaborators fails, show failure message

**Comment by nathenharvey** [comment]
This is the quality metric associated with this feature.  https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/quality-metrics/qm-002-collaborators.md

**Comment by nellshamrell** [comment]
High level architecture for determining whether a new cookbook version passes the collaborator metric:

Supermarket calls Fieri::Jobs#create
Fieri::Jobs#Create calls FoodCriticWorker (formerly known as CookbookWorker)
Fieri::Jobs#Create calls CollaboratorWorker
Fieri::CollaboratorWorker calls Supermarket::API::Metrics
Supermarket::API::Metrics returns number of Collaborators
Fieri::CollaboratorWorker posts result of metric back to Supermarket
Supermarket updates the CookbookVersion record with:
  Collaborator_failure: (whether it passed the collaborator metric check)
  Collaborator_feedback: (Success or failure message, wording TBD)
The CookbookVersion#show view will show the quality tab
The quality tab view will show the Foodcritic feedback and Collaborator Feedback

**Comment by loganmeetsworld** [comment]
API metrics controller location for interfacing with Fieri: https://github.com/chef/supermarket/blob/master/src/supermarket/app/controllers/api/v1/metrics_controller.rb
