### ISSUE TITLE
"requiretty" in sudoers breaks "supermarket-ctl make-admin"

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1314]
Issue Summary:

If "/etc/sudoers" has "Defaults requiretty", as is the default for RHEL/Centos, the "supermarket-ctl make-admin" command will fail with the "sudo: sorry, you must have a tty to run sudo" error because make-admin.rb has sudo embedded in its code. This happens even while logged in as the root user.

Expected Results:
```
# id
uid=0(root) gid=0(root) groups=0(root)

# supermarket-ctl make-admin demo
demo was not found in Supermarket.  Make sure the user exists in Supermarket before making it an admin.
```

Actual Results:
```
# supermarket-ctl make-admin demo

sudo: sorry, you must have a tty to run sudo
```

Repro Steps (if possible):
```
# echo "Defaults    requiretty" >> /etc/sudoers
# supermarket-ctl make-admin demo

sudo: sorry, you must have a tty to run sudo
```
Request for Developers:

I simply removed the "sudo" command in the following line of code and it fixed the problem. I was able to login as the root user and run the "make-admin" command even when "requiretty" was set because sudo was no longer being used.

[https://github.com/chef/supermarket/blob/master/omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/make-admin.rb#L10](https://github.com/chef/supermarket/blob/master/omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands/make-admin.rb#L10)

```
# grep command_text /opt/supermarket/embedded/service/omnibus-ctl/make-admin.rb
  command_text = "cd /opt/supermarket/embedded/service/supermarket && RAILS_ENV=\"production\" env PATH=/opt/supermarket/embedded/bin bin/rake user:make_admin user=\"#{username}\""
  shell_out = Mixlib::ShellOut.new(command_text)

# id
uid=0(root) gid=0(root) groups=0(root)

# grep requiretty /etc/sudoers
Defaults    requiretty

# supermarket-ctl make-admin demo
demo was not found in Supermarket.  Make sure the user exists in Supermarket before making it an admin.
```

**Comment by nathenharvey** [comment]
This was created from [TRI-160](https://chefio.atlassian.net/browse/TRI-160)

**Comment by robbkidd** [comment]
Investigating adding a guard to our ctl commands to check that the command is being run _as the supermarket user_ instead of root. Just in case a ctl command writes out a file—like a log—so that it remains writeable by the service account. If files get written out as root without permissions for the supermarket user, I've seen Rails apps get very cranky when next they attempt to do a thing.

Something along the lines of:
