### ISSUE TITLE
curry fell over on chef/chef

### ISSUE THREAD

**Issue by btm** [chef/supermarket#1317]
it looks like Curry hasn't been watching chef/chef since October 2015? I guessed that from looking at closed PRs that have the "Signed CLA" label.

The first commit to the supermarket repo was 2013-10-16, curry was turned on some time thereafter.  It was [announced 2014-06-23](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process/).

Curry most recently used the "Signed CLA" label. I believe we manually used the "CLA Verified" label at one point in the past.

[is:merged -label:"Signed CLA" -label:"CLA Verified" created:>2014-06-23 
](https://github.com/chef/chef/issues?utf8=%E2%9C%93&q=is%3Amerged+-label%3A%22Signed+CLA%22+-label%3A%22CLA+Verified%22+created%3A%3E2014-06-23+) yields 657 results.

[is:merged -label:"Signed CLA" -label:"CLA Verified" created:>2015-10-01](https://github.com/chef/chef/issues?utf8=%E2%9C%93&q=is%3Amerged+-label%3A%22Signed+CLA%22+-label%3A%22CLA+Verified%22+created%3A%3E2015-10-01+) yields 467 results.

The numbers are likely less daunting once you exclude our employees, e.g. from @stevendanna:

```
> git shortlog --since="1 Oct 2015" -sne | egrep -v '(opscode.com|getchef.com|chef.io)'  | wc -l
      77
```

I have access to "Configure Curry" on supermarket and I've triggered "Evaluate Repository" for chef/chef, which says "Curry is now evaluating all open Pull Requests on chef/chef." I think we need to manually ask Curry to run against all *merged* PRs since 2013-10-16 (or whatever date we deem is when we started using Curry as the official check for CLAs) that have been merged to chef/chef and tag them as it normally would. Then we need to manually review.

It's important we find a better (faster) way to detect this happening in the future too.

**Comment by nellshamrell** [comment]
Is this now fixed, or is this still an issue for you?

**Comment by btm** [comment]
I guess we didn't post-mortem.

1) how do we make sure curry doesn't silently get hung up again?
2) did @robbkidd find / resolve any commits with questionable CLA status?

**Comment by robbkidd** [comment]
In light of the move to DCO, we're closing this issue because Curry will be deprecated soon.
