### ISSUE TITLE
Markdown comments are being rendered when consumed by Supermarket

### ISSUE THREAD

**Issue by awilson-cloudpassage** [chef/supermarket#1319]
Steps to reproduce:

Put these comments in a README file:

    

Github does not render them, but Chef Supermarket now does, and it's rendering them as H1s because of the #.

@jjasghar

**Comment by robbkidd** [comment]
Related to other issues that boil down to "Supermarket's Markdown renderer is not GitHub-flavored." Closing this issue and rolling it up under #1321.
