### ISSUE TITLE
Quality Metrics: An Admin can see a metric that a normal user cannot

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1335]
As an admin user
When I log into Supermarket
And view a cookbook version
And I click the "Quality" tab
Then I can see a hidden metric

As a non-admin user
When I log into Supermarket
And view a cookbook version
And I click the "Quality" tab
Then I cannot see the hidden metric
- [ ] Research how we use rollout and whether we can use it to show or not show a metric  
- [ ] Implement way to hide metrics from regular users, but show to admin users

**Comment by robbkidd** [comment]
Possibly implement in conjunction with "published to Supermarket" quality metric as a low-hanging fruit metric to only show to admins.

**Comment by nellshamrell** [comment]
I did some research on this, and I think we have approached the point where we need to refactor from storing metric results in the cookbook version to using a separate metrics table (so we can more easily mark certain metrics as public and some as admin only).

## What the system does now

Currently, we store both the foodcritic and collaborator method results in the cookbook_version table:

![img_1054](https://cloud.githubusercontent.com/assets/813007/18494733/fd6d8f9a-79cc-11e6-8d7e-ab5334bba2df.JPG)

And this is what the current workflow looks like for running metrics after a user uploads a cookbook

![img_1055](https://cloud.githubusercontent.com/assets/813007/18494749/1f2c76d2-79cd-11e6-9473-a8499acda012.JPG)

## What a refactor would look like

I scoped out a refactor for this, and it is fortunately not as complicated as I thought it was.

I propose we create two new tables - one for quality metrics, and one for metrics results.  They would look like this:

![img_1056](https://cloud.githubusercontent.com/assets/813007/18494764/411a9f76-79cd-11e6-9817-caf1fcb61c5b.JPG)

And then the only part of the workflow that changed would be storing the metric results in Supermarket's DB, how we run them would not have to change.

![img_1057](https://cloud.githubusercontent.com/assets/813007/18494777/56838daa-79cd-11e6-90fd-da42f2cc30f7.JPG)

This would necessitate a migration to move the current metric data out of the cookbook version records and into the metrics results records, but that is doable and should be straightforward to test with a snapshot of our DB.

@robbkidd, what do you think?

**Comment by nellshamrell** [comment]
And I don't know why it turned the images sideways, but if you click on them it will open a new tab with them in the correct orientation.

**Comment by nathenharvey** [comment]
👍

**Comment by nellshamrell** [comment]
- [ ] Add new quality metric - Supermarket cookbook must exist
- [ ] Add new field to QualityMetric table - admin_only (or something similar)
- [ ] Update new quality metric to be viewable only by admins
- [ ] Update cookbook views to only display admin_only metric if the user logged into supermarket is an admin
- [ ] Profit!  (Wait a minute...this is open source...)
