### ISSUE TITLE
private supermarket: having a .docx file in root of cookbook supresses changelog from appearing on supermarket GUI

### ISSUE THREAD

**Issue by JackChance** [chef/supermarket#1341]
I've seen this in 2 cookbooks that have a sizable docx manual in their root folder. One of them has an earlier version in our Supermarket, and the version from before the .docx was added does have a changelog tab

**Comment by nellshamrell** [comment]
Hi @JackChance!

I just attempted to replicate this, but haven't been able to so far.

This is what I did:
1) Spin up a new private Supermarket
2) Create a cookbook WITHOUT a docx in it
3) Add a CHANGELOG.md to that cookbook
4) Upload the cookbook to the private supermarket - verify that the changelog shows
5) Add a .docx to the cookbook
6) Increment the version and upload the cookbook to the private Supermarket again
7) Checked whether the CHANGELOG.md was there - it was.

The only way the changelog tab will show is if the cookbook's current version has a CHANGELOG.md file in it.  Could you verify that this CHANGELOG.md file is in both cookbooks you are seeing this with?

Thanks!

**Comment by nellshamrell** [comment]
@JackChance, thanks again for reporting this.  Unfortunately, I have not been able to replicate what you are seeing.  If you continue to see this, please free free to re-open this issue.
