### ISSUE TITLE
Configuration name mismatch between Docs and supermarket.rb

### ISSUE THREAD

**Issue by hynd** [chef/supermarket#1346]
Hello!

The Supermarket docs list a bunch of configurables using a supermarket.rb (vs the JSON file the omnibus cookbook uses - i went with the .rb since it makes use of the same method i'm using to deploy Delivery): https://docs.chef.io/config_rb_supermarket.html
For example, putting something like this in /etc/supermarket/supermarket.rb:
```supermarket['chef_oauth2_verify_ssl'] = false```

Fails when i run `supermarket-ctl reconfigure` with the following:
```
================================================================================
Recipe Compile Error in /var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/recipes/default.rb
================================================================================

Chef::Exceptions::ImmutableAttributeModification
------------------------------------------------
Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'

Cookbook Trace:
---------------
  /var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/libraries/config.rb:10:in `load_or_create!'
  /var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/recipes/config.rb:24:in `from_file'
  /var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/recipes/default.rb:20:in `from_file'

Relevant File Content:
----------------------
/var/opt/supermarket/cache/cache/cookbooks/omnibus-supermarket/libraries/config.rb:

  3:
  4:  # Manages configuration
  5:  class Supermarket
  6:    module Config
  7:      def self.load_or_create!(filename, node)
  8:        create_directory!(filename)
  9:        if File.exist?(filename)
 10>>         node.from_file(filename)
 11:        else
 12:          # Write out the new file, but with everything commented out
 13:          File.open(filename, 'w') do |file|
 14:            File.open(
 15:              "#{node['supermarket']['install_directory']}/embedded/cookbooks/omnibus-supermarket/attributes/default.rb", 'r'
 16:            ).read.each_line do |line|
 17:              file.write "# #{line}"
 18:            end
 19:          end
```

If i define the .rb settings in a slightly different way (eg; `default['supermarket']['chef_oauth2_verify_ssl'] = false`) it works fine, but doesn't match up with the docs (or consistent with Chef Server, Chef Delivery etc).

Is the supermarket.rb a supported method of configuration?  Would it be safe to change it to behave like the other products?

**Comment by robbkidd** [comment]
Hi! Thanks for the feedback! I'm sorry for the delay in responding to this issue.

It has been the Supermarket team's standard to customize settings through `supermarket.json` and leave `supermarket.rb` as is. This is how the `supermarket-omnibus-cookbook` implements customizations and also allows for users to write their own wrappers around the `chef-ingredient` cookbook which expects to write customizations to the JSON file.

We'll investigate making customization consistent with other Chef products, for the foreseeable future, we intend to keep the current customization path via JSON.
