### ISSUE TITLE
Make foodcritic output less verbose

### ISSUE THREAD

**Issue by loganmeetsworld** [chef/supermarket#1348]
It would be nice if the Foodcritic criticism output was a little neater on the page. It would be great to trim the temporary work directory from the start of the path given in the output, reducing the noise in the feedback. For example, this: 
`FC005: Avoid repetition of resource declarations: /tmp/cook/dbb1ab441e2236a1faffddb7/docker/libraries/docker_service_manager_sysvinit_debian.rb:5
`
would be cleaner as this: 
`FC005: Avoid repetition of resource declarations: docker/libraries/docker_service_manager_sysvinit_debian.rb:5`

**Comment by robbkidd** [comment]
Brain dump background:

`/tmp/cook/dbb1ab441e2236a1faffddb7` came from previous versions of fieri with a hard-coded `/tmp/cook/`+`#{sidekiq_job_id}/` path for the working directory in which foodcritic would work on a cookbook. Latest fieri figures out [an appropriate work directory](https://github.com/chef/supermarket/blob/master/src/fieri/app/models/cookbook_artifact.rb#L77-L84) based on [the platform's `Dir.tmpdir` value plus the Sidekiq job id](https://github.com/chef/supermarket/blob/master/src/fieri/app/models/cookbook_artifact.rb#L21).

**Comment by robbkidd** [comment]
It's possible that this could be fixed in a new release of foodcritic, which seems to be a better place to fix this sort of thing.

**Comment by robbkidd** [comment]
After discussion with @nellshamrell, we've come to the conclusion that this trimming of the path to evaluated files would be best implemented in [foodcritic](https://github.com/acrmp/foodcritic) instead of Supermarket.

**Comment by nellshamrell** [comment]
Just discussed - we are not ultimately going to do this in Foodcritic, but do this in Supermarket :)
