### ISSUE TITLE
Deprecate knife supermarket repo with instructions on using the internal one in Chef

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1355]
Consider announcing this on Discourse as well

**Comment by nellshamrell** [comment]
Things that would be helpful in the discourse post:

- What has changed
- What versions of Chef have changed this
- Example of knife.rb that can use knife cookbook site commands to upload to a private Supermarket
- Show at least one knife supermarket command and the equivalent knife cookbook site command

**Comment by nellshamrell** [comment]
Steps to announcing this on discourse:
Upgrade a workstation to use Chef 12.11.18 (check if Chef DK has this version - if not, ping me and we will upgrade only the Chef client on your workstation)
Uninstall the knife supermarket gem
Verify that a knife[:supermarket] = some private supermarket is in your knife.rb
Try running knife supermarket commands with your private supermarket
Then try running the same commands using knife cookbook site, rather than knife supermarket, verify that they get the same results (things come and go from the correct supermarket)
If it does not work in Chef 12.11.18, try using Chef 12.12.13

**Comment by loganmeetsworld** [comment]
Found bug and opened issue in chef/chef: [#5088](https://github.com/chef/chef/issues/5088). Writing this documentation and publishing it on discourse is waiting a successful merge of this PR: [#5091](https://github.com/chef/chef/pull/5091).

**Comment by nellshamrell** [comment]
Waiting on new version of Chef to be released with Chef PR #5091 before continuing on this.

**Comment by robbkidd** [comment]
chef/chef#5091 was released in [Chef version 12.13.30](https://github.com/chef/chef/blob/master/CHANGELOG.md#v121330-2016-08-05)

**Comment by tas50** [comment]
All done
