### ISSUE TITLE
Add Cloudwatch integration for Supermarket Prod Hosts to Slack

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1356]
Currently alerts only go to email, which we are much less likely to see that an immediate Slack alert.  We should add an integration with Chef's internal slack so that we see alerts much sooner.

**Comment by loganmeetsworld** [comment]
Resources for investigating implementing this: 
(helpful step by step blog) http://ashiina.github.io/2015/06/cloudwatch-lambda-slack/
(aws docs) https://aws.amazon.com/blogs/aws/new-slack-integration-blueprints-for-aws-lambda/
(zapier) https://zapier.com/zapbook/amazon-cloudwatch/slack/

**Comment by tas50** [comment]
Ops is handling this all now so we can close this out.
