### ISSUE TITLE
Display {chef|ohai}_version for a cookbook

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1379]
We now include a chef_version metadata item on later releases of Chef 12.  If that data is present we should surface it on the Supermarket. It would be really helpful to allow people to [...] see it on the cookbook pages.

@robbkidd updated: Moved the search aspect of this feature to #1407.

**Comment by robbkidd** [comment]
Look into whether `chef_version` and `ohai_version` are foodcritic rules these days.

**Comment by tas50** [comment]
They aren't, but they should be

**Comment by nellshamrell** [comment]
Also display in search results.
