### ISSUE TITLE
Make current owner a collaborator when transferring doesn't work

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1380]
There seems to be some sort of failure condition when transferring cookbooks with the "make current owner a collaborator" checkbox enabled. I've transferred a few that had just the one owner without issue, but when I transfer a cookbook with a large number of owners and the new owner is already a collaborator it seems to fail. I'm not sure exactly what the condition is without creating some fake cookbooks, but under certain conditions it seems to fail.

**Comment by tas50** [comment]
So update on this one. It doesn't matter who is currently a collaborator. It seems like it might only be an issue for us Supermarket admins. When I transfer ownership and check the box instead of the original owner becoming a collaborator my user becomes a collaborator.

Original state:
Heavy Water is owner

State after transferring ownership to Chef and checking the box:
Chef owns, I'm a collaborator

**Comment by robbkidd** [comment]
Yep. The login of the transfer assumes that the person performing the transfer is the owner.

 The [controller action for transferring ownership](https://github.com/loganmeetsworld/supermarket/blob/ff095eb2e6166f2650b315930654f8879fb024eb/src/supermarket/app/controllers/transfer_ownership_controller.rb#L21) passes `current_user` in to the `Cookbook#transfer_ownership` method as the `initiator`. Inside `#transfer_ownership`, it is [assumed that the `initiator` is the owner](https://github.com/chef/supermarket/blob/master/src/supermarket/app/models/cookbook.rb#L161-L163).
