### ISSUE TITLE
How to merge git repo with private super market?

### ISSUE THREAD

**Issue by abhi-paul** [chef/supermarket#1383]
Hi Shamrell,
first of all thanks for sharing blog about private supermarket, it's was in-details and very helpful. 
If i am not wrong private super market is the pretty face of git repo, is it necessary to maintain two repo one for git repo & another for private supermarket or else there is a way we can merge the process so that once committed from git also same cookbook will be shared in private supermarket as well?
@nellshamrell

**Comment by robbkidd** [comment]
Hi @abhi-paul !

> is it necessary to maintain two repo one for git repo & another for private supermarket

If you mean "maintain two [source code control] repos," no. A cookbook's code is developed in a single code repository.

> once committed from git also same cookbook will be shared in private supermarket as well?

Yes, there is a process for that.

Think of Supermarket as an artifact repository where versioned builds of a cookbook are published and shared. Once cookbook code is updated in git, you should also update the version number of the cookbook (in `metadata.rb`), tag the git commit with this version number, and publish the cookbook code at that commit to your private Supermarket with `knife supermarket` or [`stove`](https://github.com/sethvargo/stove).

**Comment by abhi-paul** [comment]
then i have execute following two steps,
1. tag and commit cookbook related changes into the git, (using stove does it possible if yes how?any doc r there? or any other way are there then stove to do so?)
2.publish the cookbook at private supermarket 
any blogs are there for this?

**Comment by robbkidd** [comment]
Stove's README is a good place to start.

If you run `stove` in the root directory of a cookbook, it does the following by default:

* creates a tag in the git repo for the version number found in `metadata.rb`
* pushes that tag to the repo's origin remote
* creates a tarball of the cookbook (with some items—like tests—excluded because they're not needed in production)
* uploads that versioned tarball to the public Supermarket

Because you are using a private Supermarket, you can override where stove publishes the cookbook:

```
$ stove --endpoint https://your-private-supermarket.example.com/api/v1
```

**Comment by abhi-paul** [comment]
thanks @robbkidd for this understanding, I will try out this "stove".
I have one general question like, does every commit needs to  be published into the supermarket or only the tagged version? which is the best practice? Does "stove" support other version control as well?

**Comment by robbkidd** [comment]
> does every commit needs to be published into the supermarket or only the tagged version? which is the best practice?

Only the tagged version. Supermarket is a release artifact repository. Cookbooks in a Supermarket are versioned and released artifacts.

Cookbook authors may develop many changes to the code base of a cookbook. The authors would decide when it is appropriate to release a batch of changes—enhancements, bug fixes, etc—according to their users' needs.

Consumers of a cookbook generally would like to receive only releases, not every change that occurs to a cookbook's code.

Increasing the version number—ideally according to [semantic versioning](https://chef-community.github.io/cvp/)—represents a release of the cookbook. Publishing the cookbook release to a Supermarket (public or private) is a message about the cookbook's readiness to be used. Commits are development changes; a version tag plus a publish to a Supermarket is a release.

> Does "stove" support other version control as well?

No, but also yes.

No, `stove` does not know how to version tag a code change in a source control tool other than git.

Yes, `stove` can perform the publish to a Supermarket step of the release workflow without creating the version tag by using the command line switch `--no-git`. If a cookbook is under version control in a tool other than git, the team maintaining that cookbook will need to perform the version tagging some other way appropriate for that tool.

**Comment by abhi-paul** [comment]
How Chef's Private Supermarket is different from GitLab
@robbkidd @nellshamrell

**Comment by abhi-paul** [comment]
folks any update on my previous post, Key advantage of Chef's Supermarket over GitLab?

**Comment by robbkidd** [comment]
Supermarket is an artifact repository specialized for storing versioned cookbook tar files with an API for client-side dependency resolution.

GitLab is a source code control system.

You would use an artifact repository _in addition_ to a source code control system.

The advantages of using an artifact repository over source code management when declaring cookbook dependencies:

- communication between authors and consumers about the readiness of code
    - an artifact repository is the place where code can be found that has reached what the authors consider releasable quality
- ability to discover new released artifacts
    - a private Supermarket allows teams within an organization to search and discover cookbooks written by other teams within the organization
    - helps code reuse with the org
- efficient dependency resolution
    - an artifact repository provides an API for listing all available released versions so that a client can perform dependency resolution

**Comment by abhi-paul** [comment]
thank you very much!!! @robbkidd for this level of clarification. It is crystal clear now, thanks again.
