### ISSUE TITLE
Set up log aggregation with Supermarket prod hosts

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1388]

**Comment by robbkidd** [comment]
Tinkered with a manual install of the sumologic collector on staging instance this morning.

Brain dump of thoughts below that I reckon we can promote up to a TODO list on this issue as they gel.

Rails logging (customizing `config.log*` in [application config](http://guides.rubyonrails.org/configuring.html#rails-general-configuration)):

* remove timestamp from Rails output (a within-milliseconds stamp is applied by runit's logging)
* include a request uuid—`config.tags = [ :uuid ]`—to mark which entries go together (a problem with multiple unicorn workers interleaving their entries in the log output)
* remove ANSI colors in production `config.colorize_logging = false`

**Comment by robbkidd** [comment]
Collaborating with JB on using internal cookbook to install and configure filebeat for log shipping.

**Comment by tas50** [comment]
Closing this out as Ops has taken over all maint of Supermarket.
