### ISSUE TITLE
How private supermarket are secure?

### ISSUE THREAD

**Issue by abhi-paul** [chef/supermarket#1397]
Lets say, on **VM1 chef-server** is installed and **VM2 private supermarket** is installed now there are two workstation ->W1&W2. How will private supermarket **validate/authenticate** the workstation/user before SHARE any cookbook into the private supermarket?
It is assumed that workstations configuration files know about the private supermarket address into the knife.rb file.
@nellshamrell @robbkidd

**Comment by robbkidd** [comment]
> How will private supermarket validate/authenticate the workstation/user before SHARE any cookbook into the private supermarket?

Permission to publish to a private or public Supermarket is solely about user credentials. 

### Authentication (part 1)

A user must have an account in the Chef Server. The user can log in to the private Supermarket with the username and password of their Chef Server account. At this point, Supermarket has a copy of the user's public key retrieved from the Chef Server during oauth authentication.

### Authorization

Once a user is _authenticated_ to Supermarket, they are _authorized_ to publish new cookbook versions for:

* any cookbook that does not yet exist
* any cookbook that they own
* any cookbook that they have been added as a collaborator by the cookbook's owner (or an admin)

### Authentication (part 2)

The Supermarket API endpoint and client tools for publishing cookbook versions—`knife supermarket` and `stove`—require the user's private key that matches the public key in the Chef Server (and cached in Supermarket). This is the `client_key` setting in `knife.rb`.

### What about service accounts?

This probably leads to a question about how a CI pipeline is allowed to publish cookbooks. The CI pipeline will need to have an associated user and the user's credentials (at least the private key) available in the CI workspace to run the client commands to publish.

**Comment by abhi-paul** [comment]
thnaks @robbkidd
