### ISSUE TITLE
README.md file's table content not fetching properly into the Private Supermarket GUI

### ISSUE THREAD

**Issue by abhi-paul** [chef/supermarket#1403]
README.md file's table content is written by following guideline mentioned on this link [(https://help.github.com/articles/organizing-information-with-tables/)] but even though it is coming as follows in supermarket GUI
![2016-08-05_231719](https://cloud.githubusercontent.com/assets/19556128/17445478/cafac4e8-5b62-11e6-8a7c-bd07ca988a91.jpg)
@robbkidd @nellshamrell

**Comment by robbkidd** [comment]
@abhi-paul Yep. Supermarket's Markdown renderer is not GitHub-flavored. It seems that many users reasonably expect that Supermarket will render READMEs like GitHub does. We have an issue open for that: #1321. I'm going to close this one and have added a note to #1321 to confirm tables render like or at least similarly as at GitHub.

**Comment by abhi-paul** [comment]
then for time being is there any other way to represent table in supermarket?
@robbkidd

**Comment by robbkidd** [comment]
@abhi-paul Update:

After some testing of our current Markdown parsing/rendering settings, I'm pretty sure we _do_ render tables correctly.

Judging by your screenshot, there is probably a syntatic issue:

![2016-08-05_231719](https://cloud.githubusercontent.com/assets/19556128/17445478/cafac4e8-5b62-11e6-8a7c-bd07ca988a91.jpg)

Make sure that each row has the same number of columns. I note that there are 4 headers—Key, Type, Description, Default—but only 2 cells containing hyphens in the next row.

Here is my test table from the markdown in a README:

## Works

### Code

```
| Key | Type | Description | Default |
| --- | ---- | ----------- | ------- |
| `['a_key']` | String | This is an attribute named "a_key" | `foo` |
```

### GitHub's Render

| Key | Type | Description | Default |
| --- | ---- | ----------- | ------- |
| `['a_key']` | String | This is an attribute named "a_key" | `foo` |

### Supermarket's Render

![a table](https://cloud.githubusercontent.com/assets/517302/17562132/65dc6e52-5ef7-11e6-96c4-3a35923566ca.png)

## Doesn't Work

And I was able to replicate the problem you see with your table by making the second row contain only two columns.

### Code
```
| Key | Type | Description | Default |
| --- | ---- |
| `['a_key']` | String | This is an attribute named "a_key" | `foo` |
```

### GitHub's Render

| Key | Type | Description | Default |
| --- | ---- |
| `['a_key']` | String | This is an attribute named "a_key" | `foo` |

### Supermarket's Render

![nope not a table](https://cloud.githubusercontent.com/assets/517302/17562372/a0c38f22-5ef8-11e6-8d2e-81608f80aa87.png)
