### ISSUE TITLE
Make chef_version/ohai_version available in search form?

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1407]
@tas50 wrote on #1379:

> We now include a chef_version metadata item on later releases of Chef 12. If that data is present we should surface it on the Supermarket. It would be really helpful to allow people to search for Chef 12 only cookbooks [...].

This issue will track what searching for cookbooks based on `chef_version` and/or `ohai_version` through the web user interface.

**Comment by nellshamrell** [comment]
Will not do this for now, but willing to revisit in the future.
