### ISSUE TITLE
Add support for an alternative authentication mechanism

### ISSUE THREAD

**Issue by ckehoe** [chef/supermarket#1408]
We run our cookbooks through a combination of packer and chef zero but would like to use a private Supermarket to manage our cookbook dependencies. Based on the documentation user authentication is only possible using a chef server. https://github.com/chef-cookbooks/supermarket-omnibus-cookbook#attributes. We would like to see support added for alternative authentication methods such as LDAP, Active Directory, or local auth files.

**Comment by robbkidd** [comment]
Thanks for the feedback @ckehoe!

You are correct; authenticating users in Supermarket requires a Chef Server (specifically, a service named `oc-id` within Chef Server). The oauth negotiation includes a user's public key stored in the Chef Server. API requests to Supermarket use this key pair for authentication. It is totally possible to run a small Chef Server that is itself configured to authenticate users against LDAP or Active Directory. Baking authentication directly into Supermarket is not on our roadmap.
