### ISSUE TITLE
CSS `cursor: default` on body

### ISSUE THREAD

**Issue by pdf** [chef/supermarket#1424]
The setting of `cursor: default` on body at:

https://github.com/chef/supermarket/blob/c3aa5369f7c88c2ff206809dd814325c3428e609/src/supermarket/vendor/assets/stylesheets/foundation.css#L51

causes the 'default' (ie - arrow) cursor to be used everywhere, even on text elements where the `text` cursor is expected (at least on Chrome and Firefox).  I don't know how this fits into the Foundation workflow, but this should probably be `cursor: auto` (or unset).

**Comment by pdf** [comment]
> Just to confirm, is the text cursor you are expecting the I-beam one in the image below?

Indeed, in CSS that would be `cursor: text;`, though the browser determines when it should be displayed with the default `cursor: auto;`.

I don't really understand why there'd be a desire to override standard behaviour for mouse cursors on every element by default.  I can certainly understand why it would be desirable for some niche elements, but mouse over any text on this page and you'll see the standard, expected behaviour.

Makes it seem like selection is disabled, and makes selecting text more error-prone for no benefit that I can discern.

**Comment by robbkidd** [comment]
From my quick read of Foundation, the framework does cursor overrides to provide the option to use custom cursors. And several people commented there about a better default being `auto`. We'll put this on the backlog for triage.

**Comment by pdf** [comment]
@robbkidd looks like a fix was merged a couple of years ago: zurb/foundation-sites#5638

Is Supermarket just using a very old Foundation, or was this been reverted?  I'm not sure where I'd look for this upstream now, since the code has evolved since then.

**Comment by robbkidd** [comment]
Foundation was vendored in this code base in Spring 2014, so we're using a pretty old version.

**Comment by robbkidd** [comment]
A quick fiddle with [`body` in our `structure.scss`](https://github.com/chef/supermarket/blob/c3aa5369f7c88c2ff206809dd814325c3428e609/src/supermarket/app/assets/stylesheets/structure.scss#L22-L25) has me thinking we can set cursor to `auto` there separate from an effort to upgrade Foundation.

**Comment by pdf** [comment]
:+1: thanks for the quick turn-around.

**Comment by robbkidd** [comment]
@pdf Thankfully it was an easy fix! Thanks again for your feedback!
