### ISSUE TITLE
Release 2.8.29 (2016-10-10) results in HTTP 500s for cookbook downloads

### ISSUE THREAD

**Issue by bwerthmann** [chef/supermarket#1448]
json at https://supermarket.chef.io/api/v1/cookbooks/chef_handler looks right:

> {"name":"chef_handler","maintainer":"chef","description":"Distribute and enable Chef Exception and Report handlers","category":"Other","latest_version":"https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/2.0.0","external_url":"https://github.com/chef-cookbooks/chef_handler","source_url":"https://github.com/chef-cookbooks/chef_handler","issues_url":"https://github.com/chef-cookbooks/chef_handler/issues","average_rating":null,"created_at":"2011-05-16T23:24:08.000Z","updated_at":"2016-09-16T19:17:28.807Z","up_for_adoption":null,"deprecated":false,"versions":["https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/2.0.0","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.4.0","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.3.0","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.2.0","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.9","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.8","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.6","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.5","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.4","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.2","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.1.0","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.0.8","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.0.6","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.0.4","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.0.2","https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.0.0"],"metrics":{"downloads":{"total":35227223,"versions":{"1.0.0":1269912,"1.0.2":1269918,"1.0.4":1270037,"1.0.6":1270314,"1.0.8":1278388,"1.1.0":1271802,"1.1.2":1270077,"1.1.4":1083916,"1.1.5":1168172,"1.1.6":6497094,"1.1.8":413222,"1.1.9":3301197,"1.2.0":7260979,"1.3.0":2812507,"1.4.0":3679465,"2.0.0":110230}},"followers":92,"collaborators":6}}

...but when I try to GET https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.4.0, HTTP 500 is returned and:
```
$ curl -vi https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.4.0
*   Trying 52.25.131.193...
* Connected to supermarket.chef.io (52.25.131.193) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.chef.io
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET /api/v1/cookbooks/chef_handler/versions/1.4.0 HTTP/1.1
> Host: supermarket.chef.io
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Date: Mon, 10 Oct 2016 19:09:13 GMT
Date: Mon, 10 Oct 2016 19:09:13 GMT
< Server: nginx/1.8.1
Server: nginx/1.8.1
< Status: 500 Internal Server Error
Status: 500 Internal Server Error
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< X-Request-Id: f966a29c-c56a-4702-b212-0ba5cf3da46e
X-Request-Id: f966a29c-c56a-4702-b212-0ba5cf3da46e
< X-Runtime: 1.007250
X-Runtime: 1.007250
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< Content-Length: 57
Content-Length: 57
< Connection: keep-alive
Connection: keep-alive

<
* Connection #0 to host supermarket.chef.io left intact
{"message":"undefined method `failure' for nil:NilClass"}
```

The first failure I detected was it at 13:53:07 Eastern Time.

**Comment by kjhangiani** [comment]
same as #1447

**Comment by bwerthmann** [comment]
http://status.chef.io/incidents/tkvw761v4ckk

**Comment by nellshamrell** [comment]
We have rolled back the change on Supermarket prod, it should be working as expected now.

**Comment by bwerthmann** [comment]
Looks goos to me. Thanks!

```
$ curl -vi https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.4.0
*   Trying 54.186.205.146...
* Connected to supermarket.chef.io (54.186.205.146) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.chef.io
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> GET /api/v1/cookbooks/chef_handler/versions/1.4.0 HTTP/1.1
> Host: supermarket.chef.io
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Cache-Control: max-age=0, private, must-revalidate
Cache-Control: max-age=0, private, must-revalidate
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Date: Mon, 10 Oct 2016 19:38:31 GMT
Date: Mon, 10 Oct 2016 19:38:31 GMT
< ETag: W/"77b5de3ac92f843ebb51a1aa6071fff3"
ETag: W/"77b5de3ac92f843ebb51a1aa6071fff3"
< Server: nginx/1.8.1
Server: nginx/1.8.1
< Status: 200 OK
Status: 200 OK
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< X-Request-Id: 7ddaba82-7dd6-4b73-9e79-33b7a7a44d93
X-Request-Id: 7ddaba82-7dd6-4b73-9e79-33b7a7a44d93
< X-Runtime: 0.016007
X-Runtime: 0.016007
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< Content-Length: 406
Content-Length: 406
< Connection: keep-alive
Connection: keep-alive

<
* Connection #0 to host supermarket.chef.io left intact
{"license":"Apache 2.0","tarball_file_size":6642,"version":"1.4.0","average_rating":null,"cookbook":"https://supermarket.chef.io/api/v1/cookbooks/chef_handler","file":"https://supermarket.chef.io/api/v1/cookbooks/chef_handler/versions/1.4.0/download","quality":{"foodcritic":{"failed":false,"feedback":""},"collaborator":{"failed":false,"feedback":"passed the Collaborators Metric with 6 collaborators."}}}
```
