### ISSUE TITLE
Fix issues with 2.8.29

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1450]
Yesterday's release of 2.8.29 did not go terribly well.

The main problem was in this view https://github.com/chef/supermarket/blob/2.8.29/src/supermarket/app/views/api/v1/cookbook_versions/_cookbook_version.json.jbuilder#L7-L18

Some cookbooks had foodcritic metrics, but not collaborator num metrics, probably due to being uploaded prior to the introduction of the collaborator metric.

Additionally, because this release involved a destructive migration, it was very difficult to roll back.

## Fix plan
- [x] Add iterator to json builder view, show only metrics that the cookbook version has
- [ ] Add "down" migration to rollback migration changes around quality metrics if needed

### Supermarket with local DB
- [x] Create test environment
- [x] Install prev. Supermarket version (prev. to 2.8.29)
- [x] Create cookbook, make sure has both foodcritic and collaborator_num results (all_metrics)
- [x] Create cookbook with no metrics (upload cookbook, then delete foodcritic and collaborator_num metric results) (no_metrics)
- [x] Create cookbook with only foodcritic metric result (upload cookbook, then collaborator_num metric result) (fc_only_metric)
- [x] Create cookbook with only collaborator_num metric result (upload cookbook, then delete foodcritic result) (collab_only_metric)

- [x] verify berks install all_metrics
- [x] verify berks install no_metrics
- [x] verify berks install fc_only_metric
- [x] verify berks install collab_only_metric

For each cookbook, verify curl works as expected (i.e. with curl -i https://supermarket.chef.io/api/v1/cookbooks/apt/versions/2_6_1)

 - [x] verify curl with all_metrics
 - [x] verify curl with no_metrics
 - [x] verify curl with fc_only_metric
 - [x] verify curl with collab_only_metric

- [x] Upgrade to new release

- [x] verify berks install all_metrics
- [x] verify berks install no_metrics
- [x] verify berks install fc_only_metric
- [x] verify berks install collab_only_metric

For each cookbook, verify curl works as expected (i.e. with curl -i https://supermarket.chef.io/api/v1/cookbooks/apt/versions/2_6_1)

 - [x] verify curl with all_metrics
 - [x] verify curl with no_metrics
 - [x] verify curl with fc_only_metric
 - [x] verify curl with collab_only_metric

### Supermarket with external DB
- [x] Create test environment
- [x] Install prev. Supermarket version (prev. to 2.8.29)
- [x] Create cookbook, make sure has both foodcritic and collaborator_num results (all_metrics)
- [x] Create cookbook with no metrics (upload cookbook, then delete foodcritic and collaborator_num metric results) (no_metrics)
- [x] Create cookbook with only foodcritic metric result (upload cookbook, then collaborator_num metric result) (fc_only_metric)
- [x] Create cookbook with only collaborator_num metric result (upload cookbook, then delete foodcritic result) (collab_only_metric)

- [x] verify berks install all_metrics
- [x] verify berks install no_metrics
- [x] verify berks install fc_only_metric
- [x] verify berks install collab_only_metric

For each cookbook, verify curl works as expected (i.e. with curl -i https://supermarket.chef.io/api/v1/cookbooks/apt/versions/2_6_1)

 - [x] verify curl with all_metrics
 - [x] verify curl with no_metrics
 - [x] verify curl with fc_only_metric
 - [x] verify curl with collab_only_metric

- [x] Upgrade to new release

- [x] verify berks install all_metrics
- [x] verify berks install no_metrics
- [x] verify berks install fc_only_metric
- [x] verify berks install collab_only_metric

For each cookbook, verify curl works as expected (i.e. with curl -i https://supermarket.chef.io/api/v1/cookbooks/apt/versions/2_6_1)

 - [x] verify curl with all_metrics
 - [x] verify curl with no_metrics
 - [x] verify curl with fc_only_metric
 - [x] verify curl with collab_only_metric

**Comment by robbkidd** [comment]
As an addendum, 2.8.30 is the version produced by [the fix](https://github.com/chef/supermarket/pull/1452) merging to master. 

### Staging with 2.8.29

```
> curl https://supermarket-staging.chef.io/api/v1/cookbooks/alteryx-server/versions/0.11.4 | jq
{
  "message": "undefined method `failure' for nil:NilClass"
}
```

### Staging with 2.8.30

With an older cookbook version which only has the foodcritic metric result.

```
> curl https://supermarket-staging.chef.io/api/v1/cookbooks/alteryx-server/versions/0.11.4 | jq
{
  "license": "Apache 2.0",
  "tarball_file_size": 54924,
  "version": "0.11.4",
  "average_rating": null,
  "cookbook": "https://supermarket-staging.chef.io/api/v1/cookbooks/alteryx-server",
  "file": "https://supermarket-staging.chef.io/api/v1/cookbooks/alteryx-server/versions/0.11.4/download",
  "quality_metrics": [
    {
      "name": "Foodcritic",
      "failed": false,
      "feedback": ""
    }
  ]
}
```
