### ISSUE TITLE
/icla-signatures gives me a 404

### ISSUE THREAD

**Issue by elthariel** [chef/supermarket#1458]
Hi,

I'm trying to sign the ICLA agreement. I got myself an account (lta) on the supermarket and linked this very account to it, but `https://supermarket.chef.io/icla-signatures` gives me a 404.

Am I doing something wrong ? is this feature disabled or is it a bug ?

Regards,
Lta.

**Comment by robbkidd** [comment]
@elthariel The Individual/Corporate Contributor License Agreement (CLA) process was deprecated on October 1 and replaced with a [Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) process. You are no longer required to sign the CLA at the Supermarket site. Instead, each commit contributed via a pull-request should have a line reading "Signed-off-by: Your Name <youremail@example.com>" appear in the comment message.

What links brought you to the CLA site? We may have missed some in the transition.

**Comment by elthariel** [comment]
2 things brought me to this url:
 - Reading the routes.rb in this repo
 - A link from here: https://blog.chef.io/2014/06/23/changes-to-the-contributor-license-agreement-process/

**Comment by robbkidd** [comment]
Ah. Yes. The routes still exist in this codebase, but the public Supermarket site has the CLA feature flag flipped to disabled now that we're using DCO. That blog post has been superseded by https://blog.chef.io/2016/09/19/introducing-developer-certificate-of-origin/.

**Comment by elthariel** [comment]
Thanks for the reply and sorry folks !

**Comment by robbkidd** [comment]
No worries! Thanks for your interest in getting involved!
