### ISSUE TITLE
Investigate Foodcritic Stack Too Deep error with a cookbook

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1459]
We are seeing this error:

<img width="782" alt="screen shot 2016-10-21 at 2 08 18 pm" src="https://cloud.githubusercontent.com/assets/813007/19611753/01ae7428-9798-11e6-9206-b0bb7eb4084f.png">

Whenever [this cookbook](https://supermarket.chef.io/cookbooks/opennms) is uploaded.

The cookbook upload itself is not being affected, but we do not get a foodcritic metric result from Fieri (though we do get a Collaborator metric result)

**Comment by robbkidd** [comment]
Having reviewed, opting to close as a foodcritic issue. Will re-open investigation if the error occurs again.
