### ISSUE TITLE
[Request] Standalone Supermarket - Without ChefServer

### ISSUE THREAD

**Issue by dfduarte** [chef/supermarket#1461]
Hello there,

As a feature request (if this space is appropriate for that), would be good have a specific Supermarket setup to be used without Chef-Server.

I know that Supermarket depends on some features of Chef server (like the key authentication and the specific OAUTH2 server from it), but sometimes in specific environments, the ChefServer is not specfically necessary, or it's under used and could be replaced for something more simple, ou excluded from the project.

Is already there a way to make it with the current Supermarket config, or this feature request makes sense?

**Comment by eric-tucker** [comment]
I believe this is already on their roadmap according to the readme:

https://github.com/chef/supermarket#setting-up-auth

NOTE: Authentication currently requires a live chef server running oc-id. **We are working on a solution which would allow a developer to run the authentication locally, stay tuned.**

That being said, this is long overdue.  I believe Chef Zero on server is the way to go.  This allows easier versioning of chef resources using git mechanisms and eliminates a single point of failure requiring authentication mechanisms that must be transmitted in a secure manner to servers for bootstrapping.

Continuing to require Chef Server for running a private Supermarket seems like a short sighted decision that leaves those of us who have moved on form Chef Server with no options.

**Comment by robbkidd** [comment]
@nathenharvey Thoughts on alternate authentication sources for private supermarkets?

**Comment by robbkidd** [comment]
Because this is about alternate authentication sources, maybe consider in relation to the discussion about SAML-based auth #1437.

**Comment by tas50** [comment]
Closing this out since this isn't the direction we're moving. Supermarket is getting tighter integration with Automate.
