### ISSUE TITLE
Disallow viewing the supermarket while not logged in for private supermarkets

### ISSUE THREAD

**Issue by tanner-bruce** [chef/supermarket#1468]
We are moving towards a private supermarket, and I would like to disallow users from browsing or downloading cookbooks from the supermarket if they are not logged in.

Is this possible at this time? If not, what would be a recommended approach for this?

**Comment by robbkidd** [comment]
@nathenharvey Do you have thoughts on this feature request for private supermarkets?

**Comment by nathenharvey** [comment]
@tanner-bruce one of the primary goals of the Supermarket is to help build the community of practice around automation with Chef.  To do so, the Supermarket is meant to be a clearinghouse for all of the cookbooks, tools, plugins, and compliance profiles that are suitable for sharing within the community.

Completely preventing access to the Supermarket is therefore not a concern of the Supermarket.  You should handle this requirement at a different level.

The public Supermarket, https://supermarket.chef.io, is available to anyone with a connection to the Internet.  There are many private Supermarkets deployed by companies that are using Chef that are not accessible to anyone except those within in the company.  This is achieved by installing the Supermarket on a private network.

I believe this is that solution you are looking for:  deploy the Supermarket to a network that allows only appropriate people access.
