### ISSUE TITLE
Implement "Cookbook lists a source address for repository" metric

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1475]
https://github.com/chef-cookbooks/cookbook-quality-metrics/blob/master/quality-metrics/qm-005-source-url.md

**Comment by robbkidd** [comment]
Covered by [Foodcritic rule FC065](http://www.foodcritic.io/#FC065). This rule is enabled by default in a Supermarket installation.

Can we leverage the already implemented Foodcritic Pass/Fail metric for QM005 source URL? Or is there some other user experience needed?

**Comment by nathenharvey** [comment]
FC065 is sufficient!
