### ISSUE TITLE
Bug Reporting

### ISSUE THREAD

**Issue by towster** [chef/supermarket#1483]
So I want to report bug with something in the supermarket but there is no way to submit it directly to the author. The only way I found to submit any bugs in the market is here. I know this is not really the correct location but you can consider it a feature request to get the ability to submit directly to the recipe author.

So here is my bug:
cron-delvalidate (0.1.3) fails on AIX when using "\*/1" for the hour. It should be changed to simply "\*" which has the same meaning.

**Comment by robbkidd** [comment]
The ability exists already to find the place to open issues with a cookbook, but the cookbook author must declare where that place is in the issues_url field in the cookbook metadata.

In this case, [the author](https://supermarket.chef.io/users/ellekrout) appears to have [a GitHub profile](https://github.com/ellekrout), but does not at the time I'm writing this have the `cron-delvalidate` cookbook source code in [a public repository](https://github.com/ellekrout?tab=repositories).

**Comment by nellshamrell** [comment]
Hello again, @robbkidd is correct, we unfortunately cannot do much about this without a source code repo.  I suggest attempting to contact the cookbook author directly - should the author have any questions about updating, they are free to reach out to us.
