### ISSUE TITLE
Field in profile management page are confusing

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1485]
The current design of the fields in the manage profile page makes it so you can't see what the fields are for unless you remove the content from the field. There's no name for each field. It makes sense when you initially create your profile since the fields are empty, but if you go to update something it's rather confusing.

<img width="862" alt="screen shot 2016-12-01 at 2 55 53 pm" src="https://cloud.githubusercontent.com/assets/1015200/20816259/4a7e7af0-b7d6-11e6-8ac3-705efcf6b51b.png">

**Comment by robbkidd** [comment]
There are tooltips. 😬

**Comment by robbkidd** [comment]
@tas50 How about ...?

![screen shot 2016-12-02 at 10 24 00 am](https://cloud.githubusercontent.com/assets/517302/20839161/7eba131c-b879-11e6-84a4-a387f973b295.png)

**Comment by tas50** [comment]
Would it be empty by default now?

**Comment by robbkidd** [comment]
Updated #1486 with screenshots of empty and filled-in fields.
