### ISSUE TITLE
Supermarket shows the wrong user icons in the cookbook feed

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1509]
In the cookbook release feed when a contributor releases a cookbook we're displaying the icon of the owner and not the user that shipped it.

<img width="876" alt="screen shot 2016-12-30 at 10 29 18 pm" src="https://cloud.githubusercontent.com/assets/1015200/21576333/94d09046-cedf-11e6-990e-e5fc2624d69c.png">

In this example I'm being given the icon for chef-cookbooks and sous-chefs depending on what cookbook I'm shipping.

This screenshot is from https://supermarket.chef.io/dashboard

**Comment by robbkidd** [comment]
I wonder if the owner information is still useful in the feed. People may pay more attention to a cookbook's owner than keeping track of a cookbook's collaborators.

Maybe a more better content for an activity event would be:

> <chef's avatar> Chef's cookbook __rsyslog__ had a v5.1.0 release by <Tim's avatar> Timothy Smith

**Comment by robbkidd** [comment]
This is related to [the fix](https://github.com/chef/supermarket/pull/1293) for #965 where the activity feed was reporting that a cookbook's owner had released a new version when it was really a collaborator. The fix seems to have [left the avatar to display as the cookbook owner's while displaying the name of the person publishing the version](https://github.com/chef/supermarket/pull/1293/files#diff-0727a69a91c2b7e8e0dcf69328b22e0bR21).

**Comment by robbkidd** [comment]
@tas50 As one of the few people who notice and comment on the Supermarket event feed, what are your thoughts about the longer format event:

> 👩‍🍳 Chef's cookbook rsyslog had a v5.1.0 release by 🤦‍♂️ Timothy Smith

**Comment by tas50** [comment]
That would make a lot more sense

**Comment by davidalpert** [comment]
@tas50 @robbkidd I might suggest:

> 👩‍🍳 Chef: rsyslog v5.1.0 released by 👱 Timothy Smith

That keeps the maintainer's avatar and name left-aligned but places the cookbook name and new version number as the next-most important detail as one scans left-to-right.

**Comment by robbkidd** [comment]
@davidalpert I'm down with that, too. 👍

**Comment by davidalpert** [comment]
apologies for the triple commit notice. amended it twice to remove a typo and add my DCO.
