### ISSUE TITLE
supermarket s3 cookbook storage only works for "US Standard" bucket regions

### ISSUE THREAD

**Issue by Stromweld** [chef/supermarket#1520]
when configuring internal supermarket server to use s3 for storage uploads work for buckets in on default region but downloads fail when supermarket tries to connect to wrong url for endpoint specific buckets. See chat thread below.

stromweld [3:11 PM] 
I just tried building a private supermarket server with cookbooks stored in S3. When trying to run berks I’m getting an error when it tries to download the cookbooks from our private supermarket server.

E, [2017-01-10T15:05:12.887448 #8512] ERROR -- : Actor crashed!
OpenURI::HTTPError: 301 Moved Permanently (Invalid Location URI)

coderanger [3:12 PM] 
Okay, fix the URL?

stromweld [3:12 PM] 
Anybody else run into this issue? I also get this when trying to download the cookbook from private supermarket directly:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Bucket>code-chef-supermarket-uswest2-nativex</Bucket>
<Endpoint>
code-chef-supermarket-uswest2-nativex.s3.amazonaws.com
</Endpoint>
<RequestId>03666C5283B89105</RequestId>
<HostId>
MH+vVoWcktgTjYQYddsUblCfcnDj83u7+kyQ3z5E9WHcjTXwqrqt9Y1TUkF7cvVEtsMKCdKUmq8=
</HostId>
</Error>

[3:13]  
Berksfile has the correct supermarket url and is able to get the index and lists which packages it’s going to use and install, but then fails when trying to fetch them.

coderanger [3:14 PM] 
Supermarket has the wrong S3 URL

[3:14]  
Or has the default, which would be east1

stromweld [3:17 PM] 
in the docs it just mentions changing access_key_id, s3_bucket, secret_access_key attributes.

[3:18]  
upload to the private supermarket worked without error and I can see objects in the S3 bucket.

[3:19]  
https://docs.chef.io/install_supermarket.html#external-cookbook-storage

coderanger [3:22 PM] 
I can't say for sure without digging in to the code but it seems very likely either Supermarket doesn't correctly support non-east1 buckets (easy to do by accident) or you need to set a different base URL somewhere

[3:22]  
I would try making the bucket in east1 for testing at least

stromweld [3:25 PM] 
is berks trying to download from S3 directly or is supermarket downloading it from S3 and then fulfilling the berks request? The bucket is private and only the user I have configured in the supermarket attribute has read/write access to the bucket.

coderanger [3:26 PM] 
That isn't related, the error is quite clear

stromweld [3:26 PM] 
So if supermarket is handing back the S3 URL and berks then tries downloading it directly from my workstatiion that would make sense why it’d fail.

coderanger [3:26 PM] 
it's that the bucket is being accessed using the wrong name

[3:27]  
This usually happens when some code assumes you can access S3 via `https://s3.amazonaws.com/$bucketname`

[3:27]  
That URL format unfortunately only works for buckets in us-east1

tensibai [3:30 PM] 
Strange, I had understood the global naming restriction was for this use case (but I'm quite tired lately)

coderanger [3:31 PM] 
@tensibai Long ago it used to handle it internally for you

[3:31]  
But no longer

[3:31]  
Probably because it ruined the whole point of regions

[3:32]  
i.e. if us-east1 was down, you were down even if the bucket was elsewhere

tensibai [3:32 PM] 
Hope the public access from cname still works or I'll have an angry customer soon

coderanger [3:33 PM] 
Yep, that works as per always

stromweld [3:33 PM] 
ok I’ll try making it in us-east-1 and test.

[3:33]  
thanks for the help

coderanger [3:33 PM] 
It just automatically maps the cname to the correct region for you, preserving isolation

tensibai [3:34 PM] 
Great, as the bucket name is a cname pointing to a cname pointing to some s3 url I can't remember right now ;)

coderanger [3:34 PM] 
For example in this case

[3:34]  
`code-chef-supermarket-uswest2-nativex.s3.amazonaws.com is an alias for s3-us-west-2-w.amazonaws.com.`

tensibai [3:35 PM] 
And I'll be sleeping in a few, so better not start the night with a question :p

tensibai [3:40 PM] 
Good night/evening/morning everyone ;)

stromweld [3:51 PM] 
@coderanger You are correct. Recreating the bucket in US Standard vs US-WEST-2 worked and fixed the issue.

coderanger [3:52 PM] 
@stromweld I would check for/file a bug against Supermarket

[3:52]  
Probably just an oversight somewhere, easy to forget that trick with S3 URL formatting

stromweld [3:52 PM] 
will do thanks

**Comment by robbkidd** [comment]
Might this be related to #1307?

**Comment by Stromweld** [comment]
yeah looks like they are related.

**Comment by pwelch** [comment]
Looks like #1307 was merged in awhile back. Closing this for now. 

Please reopen if this is still an issue.
