### ISSUE TITLE
Link to Supermarket API docs is broken

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1526]
(Pasted from an internal JIRA ticket)

The link to the supermarket API docs from the Cookbooks Directory is broken (on this page: https://supermarket.chef.io/cookbooks-directory).

The issue was raised on the chef-web-docs GitHub.
https://github.com/chef/chef-web-docs/issues/329

Please let me know when it is finished so I can clear the GitHub Issue.

Thanks, Kimberly

**Comment by robbkidd** [comment]
The Supermarket API doc used to link to `https://docs.chef.io/api_cookbooks_site.html` but [this page was renamed](https://github.com/chef/chef-web-docs/commit/245d488fac82319f29bd8cd1ca92cd75382fa9e0) to `https://docs.chef.io/supermarket_api.html` back in November in a much needed cleanup.

PR incoming for a fix to the link.
