### ISSUE TITLE
QM011 - Contributing doc

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1532]

**Comment by nellshamrell** [comment]
Initial idea for a workflow:

User uploads a cookbook version to Supermarket
Supermarket calls Fieri through FieriNotifyWorker#perform
Fieri calls each metric through MetricsRunner#perform
MetricsRunner#perform calls Supermarket for the cookbook version's cookbook api response (this includes the source_url, if the cookbook version has one)
Fieri then uses this source_url info to call the Github Contents URL (GET repos/owner/repo/contents/CONTRIBUTING.md)
If the CONTRIBUTING.md file is present, Fieri indicates the metric has passed
If the CONTRIBUTING.md file is not present, Fieri indicates the metric has failed
Fieri POSTs the result back to Supermarket
Supermarket enters a new metric result for the cookbook version in the Supermarket DB.

**Comment by nellshamrell** [comment]
Fieri
- [ ] Add ContributingWorker to Fieri
- [ ] Contributing Worker - extract source url from cookbook_json
- [ ] Contributing worker - call Github API through Octokit to determine whether CONTRIBUTING.md file is present in repo
- [ ] if present, pass metric.  if not present, fail metric
- [ ] post result to Supermarket
- [ ] Add call to ContributingWorker from MetricsRunner worker

Supermarket
- [ ] Add Contributing metric to DB
- [ ] Add method to QualityMetrics controller for Fieri to Post to
- [ ] QualityMetrics controller method should create new MetricResult for the relevant cookbook version
