### ISSUE TITLE
QM014 - Version tags

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1534]

**Comment by nellshamrell** [comment]
Fieri
- [ ] Add VersionTagWorker to Fieri
- [ ] VersionTagWorker calls Github API, look for version tag that matches cookbook version
- [ ] if there is a tag that matches the cookbook version, metric passes
- [ ] if there is not a tag that matches the cookbook version, metric fails
- [ ] post result to Supermarket
- [ ] add call to VersionTagWorker in MetricsRunner Worker
- [ ] Add error handling for when a source_url is invalid

Supermarket
- [ ] Add Version Tag Metric to DB
- [ ] Add method to QualityMetrics controller for Fieri to Post to
- [ ] QualityMetrics controller method should create new MetricResult for the relevant cookbook version

**Comment by nellshamrell** [comment]
We can access a list of tags on a repo with this method 

```ruby
octokit.tags('chef/supermarket')
```
