### ISSUE TITLE
doc update for running quality metrics in dev environment

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1536]

**Comment by robbkidd** [comment]
@nellshamrell Do you think is the right number of ways to run a quality metric? Too many? Missed some?
 
+ Write Rspec Tests in Fieri
+ Run from a Rails console within Fieri development environment
+ Run from a Rails console within Supermarket development environment
+ Run with a Rake command within Supermarket development environment
+ Run a development instance of Supermarket and upload a cookbook

**Comment by nellshamrell** [comment]
I would perhaps nix the Fieri development environment one and focus on the ways you can run it in the Supermarket development environment.  I think that would make the documentation a little simpler, though we can of course always add running them from the Fieri development environment if needed.
