### ISSUE TITLE
supermarket zlinux platform icon isn't transparent

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1541]
It's the only one with white

3rd from the right:

<img width="516" alt="screen shot 2017-02-03 at 10 00 07 am" src="https://cloud.githubusercontent.com/assets/1015200/22586990/93146e66-e9f7-11e6-8260-0ad038c6b52f.png">

**Comment by robbkidd** [comment]
Tricksy hobbitses.

**Comment by tas50** [comment]
Not going to worry about this one at this point
