### ISSUE TITLE
Make API items limit number a configurable value

### ISSUE THREAD

**Issue by juliandunn** [chef/supermarket#1542]
We are working on an integration with a partner where they need the ability to batch download cookbooks. In order to do so we would like to raise the limit on the # of cookbooks downloadable at one time from 100 to something like 10000.

As per discussion with @robbkidd it appears that Supermarket [hardcodes the limit to 100](https://github.com/chef/supermarket/commit/6c93304f22e29b2d6e0606131ce07a853fe59015#diff-f9df768289fd6bf1c359ddab5b920e25R5) right now.

**Comment by robbkidd** [comment]
After some code spelunking and operational hand-wringing with @juliandunn, @nathenharvey, and @nellshamrell, we've concluded that the least risky change would be to make the API item limit a configurable value. It's a relatively small change, brings a slight improvement (removing a hard-coded magical number), and can be changed in production environments to tune to a Supermarket's needs versus resources without requiring a new release of code.
