### ISSUE TITLE
[QUESTION] What is the markdown rendering engine of supermarket?

### ISSUE THREAD

**Issue by pantocrator27** [chef/supermarket#1554]
I try to author my README.md so that it will be rendered appropriately by Supermarket.  I end up comparing the markdown rendered by GitHub with the markdown rendered by Supermarket and they are different.  I would like to know what is the rendering engine for Supermarket so that I can avoid surprises when uploading cookbooks to Supermarket.

**Comment by robbkidd** [comment]
Supermarket currently uses [Redcarpet](https://github.com/vmg/redcarpet) for [markdown rendering](https://github.com/chef/supermarket/blob/d4928e24aef4e36f997e3103ceca878f18df507d/src/supermarket/app/helpers/markdown_helper.rb).
