### ISSUE TITLE
ability to upload old versions of cookbooks

### ISSUE THREAD

**Issue by kplimack** [chef/supermarket#1555]
In order to upload an older version of a cookbook that I will require until some deps get updated, its a PITA to have to delete all the releases and then upload them in order.  please add a flag so I can get around this constraint.

**Comment by kplimack** [comment]
I had some mistakes in my population script. This works, however there is no way to delete a single version of a cookbook

**Comment by robbkidd** [comment]
You can remove a single version:

```
$ knife supermarket unshare "my_apache2_cookbook/versions/0.10.0" --supermarket-site https://supermarket.your.org
```

See the `unshare` command at the bottom of [the knife supermarket doc](https://docs.chef.io/plugin_knife_supermarket.html).

**Comment by kplimack** [comment]
Thanks.
