### ISSUE TITLE
Missing name on the cookbook releases feed

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1576]
I believe that @smurawski released the Windows cookbook, but the cookbook feed just has a blank name for who released the cookbook.

![screen shot 2017-03-29 at 9 37 23 am](https://cloud.githubusercontent.com/assets/1015200/24465834/6eaefe10-1463-11e7-97a5-104f5fc644cc.png)

**Comment by robbkidd** [comment]
Sneaky @smurawski does not have a first name or last name set. Seems like we should display the username when the full name is blank.

**Comment by smurawski** [comment]
If they are required fields, they should be mandatory :)

**Comment by robbkidd** [comment]
I dunno about required. It's just the account information Supermarket gets from the associated Chef Server. In public Supermarket's case, that's Hosted Chef. The simplest thing for Supermarket to do is display the first and last name of the publishing user or, if that's blank, use the username.

**Comment by smurawski** [comment]
Just messing with you @robbkidd

**Comment by robbkidd** [comment]
Found the problem. The activity feed calls `User#name` which should show either the first + last name or the username. The choice between first + last name or username was not checking for whether the first and last name strings were empty, only falsey. `" "` is truthy. So, PR opened to make that check for the _presence_ of a first or last name, else return the username.
