### ISSUE TITLE
Paperclip version shipped in the RPM packages is out of date

### ISSUE THREAD

**Issue by silverbadge** [chef/supermarket#1587]
The RPMs available on https://downloads.chef.io/supermarket/2.9.30 have an old version of Paperclip ruby gem. This is causing S3_URLS_EXPIRE to be set as an absolute time value instead of a time period in seconds for the link to expire. Paperclip version >= 5 sets the correct method arguments (expires_in) instead of (expires) see http://www.rubydoc.info/github/marcel/aws-s3/AWS%2FS3%2FS3Object.url_for for more details

**Comment by robbkidd** [comment]
@silverbadge Thanks for reporting this! It's fortuitous that you've said something as now you can provide some feedback for us as a Supermarket user who also uses S3!

We've had [a PR that incidentally upgrades Paperclip](https://github.com/chef/supermarket/issues/1411) open for a while. We have held off merging so far because of the possible breakage: folks using S3 must add a previously-not-required env var `S3_REGION` for the newer AWS sdk required by newer Paperclip. In that branch, if `S3_REGION` isn't given, Supermarket doesn't start.

Do you have any feedback on [the plan proposed there for a release including that upgrade](https://github.com/chef/supermarket/pull/1411#issuecomment-247656774)?

**Comment by silverbadge** [comment]
It would be great to get [This PR](https://github.com/chef/supermarket/pull/1411#issuecomment-247656774) merged! It looks like it will not only fix the this issue here but also the one you mentioned re S3 bucket region. Thanks @robbkidd for highlighting it.

**Comment by robbkidd** [comment]
@silverbadge As an S3 user, do you think the startup (or rather _not_ startup) behavior described there is acceptable? Specifically, the next major version of Supermarket _will not_ start the web service without all four (or none) of the required S3 environment variables set.

I'm baking a sample RPM to double-check my expectations about how the services would let you know something is awry. I'll report back here what the observable behavior of `NOPE, not gonna start like that` is at the moment.

**Comment by dgubb** [comment]
@robbkidd sounds pretty reasonable to have the web page fail if the 4 variables aren't set providing it errors in a helpful way

**Comment by robbkidd** [comment]
@dgubb Wunderbar. I shared more [details about what failure looks like](https://github.com/chef/supermarket/pull/1411#issuecomment-291882671) to end users and administrators over on the PR. I'd love it if you could weigh in there with feedback.

**Comment by robbkidd** [comment]
Supermarket Staging updated to v3.0.0 that includes the Paperclip upgrade in #1411. Received only the new expected chef runtime errors.

Catching the missing `s3_region` setting:
```
Supermarket::Config::IncompleteConfig
-------------------------------------
Got some, but not all, of the required S3 configs. Must provide none or all of ["s3_bucket", "s3_access_key_id", "s3_secret_access_key", "s3_region"] to configure cookbook storage in an S3 bucket.
```

And then catching that we've got `.`s in our bucket name and the s3_domain_style was not set to `:s3_path_url`:
```
Supermarket::Config::IncompatibleConfig
---------------------------------------
Incompatible S3 bucket settings. If the bucket name contains periods, the bucket must be in us-east-1 and the domain style must be :s3_path_url.
Amazon recommends against periods in bucket names. See: https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
```

We'll let 3.0.0 stew for a bit in Staging over the weekend—Friday releases are bad, m'kay—and release it next week (or a 3.0.0+ version with fixes for bugs that arise).

**Comment by robbkidd** [comment]
[Supermarket 3.0.0](https://downloads.chef.io/supermarket/stable/3.0.0) released today!
