### ISSUE TITLE
is there a way to bulk-add-collaborator group ?

### ISSUE THREAD

**Issue by kplimack** [chef/supermarket#1594]
i have a ton of cookbooks that I uploaded as myself, but now I need my CI system to do the uploading and it does not have permission.  it is a possible to bulk update a ton of cookbooks and add a collab group?  are there any files I can add to a repo to do this, like collaborators.rb or the like ?

**Comment by kplimack** [comment]
maybe some way to update it via the DB ?

**Comment by kplimack** [comment]
@robbkidd ?

**Comment by robbkidd** [comment]
Neither the web UI nor the API have much in the way of bulk operations. Something can probably be done from the Rails console to transfer the ownership of a collection of cookbooks. The console command would depend a lot on what sort of filter criteria could be used to determine which cookbooks get a new owner.

**Comment by kplimack** [comment]
@robbkidd thanks for your quick reply.  I would like to xfer ownership of everything to a group called 'committers' under my 'admin' user.

**Comment by robbkidd** [comment]
@kplimack Are you in the [Chef Community Slack](http://community-slack.chef.io/)? Our wrestling with getting you working could probably happen faster there. We try to keep the GitHub issues to bugs and feature requests, though we can circle back to update this thread with a solution once we find one.

**Comment by robbkidd** [comment]
### :sparkles: Mischief Managed ✨ 

Right now, ownership transfer is the simplest and most reliable solution to getting a CI pipeline user to be able to publish new cookbook versions of existing cookbooks. Performing the transfer action on a number of cookbooks today requires going through the Rails console of the Supermarket. 

:warning: There Be Dragons 🐉  on the console, though, so if you find yourself needing to do something like this in bulk, seek help from your Chef support or find us in the [Chef Community Slack](http://community-slack.chef.io/).

**Comment by mattlqx** [comment]
What's the purpose of `make-admin` if it doesn't allow the user to bypass collaborator/owner permissions? This is the first piece of info that I'm finding about permissions and ownership on a private Supermarket, it'd be really handy if this topic were laid out better in official docs.

**Comment by robbkidd** [comment]
@mattlqx I have just gone and looked, too, and yea, there's not much about the admin role in the docs beyond [the `make-admin` command](https://docs.chef.io/ctl_supermarket.html#make-admin). The quick version here is that an admin Supermarket user can perform _some_ management actions on a cookbook without being the cookbook's owner. An admin user will see the "Manage Cookbook" menu in the web interface:

![manage cookbook](https://cloud.githubusercontent.com/assets/517302/25534770/e8a08a84-2c02-11e7-982c-04bd7a815cce.png)

But admins cannot publish new versions or unshare previously published versions of a cookbook without transferring ownership or adding themselves as collaborators. If one human is going to assert the power to tinker with something owned by another human, they'll need to be transparent about it.

**Comment by mattlqx** [comment]
That's fair enough. In that case, an accessible bulk add-collaborator function would be very useful and preserve that intent.

**Comment by robbkidd** [comment]
That's great to hear! Thanks for the feedback. Would you be willing to describe a bit of the problem or pain you feel without the feature at https://feedback.chef.io ? We're trying out using the feedback site to capture feature requests and ideas while keeping the GitHub Issues scoped to bugs and work-in-flight.

**Comment by lehn-etracker** [comment]
> That's fair enough. In that case, an accessible bulk add-collaborator function would be very useful and preserve that intent.

I had exact same challenge today and wanted to share my workaround:

```ruby
# this will add user gitlab as collaborator to all cookbooks maintained by all users
def add_gitlab_collaborator
  # get gitlab user object
  u_gitlab = User.search('gitlab').first
  # add gitlab user to all cookbooks as collaborator
  User.all.each do |u|
    next if u == u_gitlab
    puts "Checking all Cookbooks of User #{u.name}"
    u.collaborated_cookbooks.each do |c|
      # puts "Checking Cookbook #{c.name}"
      next if c.collaborator_users.include? u_gitlab
      puts "Adding User #{u_gitlab.name} as collaborator to #{c.name}"
      c.collaborator_users.push u_gitlab
      c.save
    end
  end
end
```

run function within supermarket console:
```bash
su - supermarket -s /bin/bash supermarket-ctl console
# now we are within irb console
# paste function from above and run with
add_gitlab_collaborator
```

That's it!
