### ISSUE TITLE
Upgrade to Rails 5.1

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1606]
From [the Rails 5.1 announcement](http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/):
> As per our maintenance policy, the release of Rails 5.1 means that bug fixes will only apply to 5.1.x, regular security issues to 5.1.x and 5.0.x, and severe security issues to 5.1.x, 5.0.x, and 4.2.x. This means 4.x and below will essentially be unsupported!

- [x] upgrade to Rails 5.0
- [x] upgrade to Rails 5.1

**Comment by pwelch** [comment]
When we upgrade to Rails 5.2, we should consider moving to [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html)

**Comment by btm** [comment]
Supermarket was upgraded to 5.1 and 5.2 in https://github.com/chef/supermarket/pull/1867 and released in [3.3.26](https://discourse.chef.io/t/supermarket-3-3-26-released/17368) in July 2020.
