### ISSUE TITLE
Search does not work on Safari Mobile (iOS)

### ISSUE THREAD

**Issue by rmoriz** [chef/supermarket#1609]
- open Safari on iOS (latest, 10.3.2)
- go to https://supermarket.chef.io/
- tap on Search
- enter search term e.g. "hostname"
- press "Search"

nothing happens.

Same behaviour: Chrome for iOS (58.0.3029.113), Firefox Focus

**Comment by robbkidd** [comment]
Thanks for the report, @rmoriz. 

It's a known issue that not many have reported caring about. I'll link this up with the known issue #1226 and close this as a duplicate.

**Comment by tas50** [comment]
This is fixed in 4.0
