### ISSUE TITLE
Issue with private chef supermarket OAuth authentication

### ISSUE THREAD

**Issue by sameerakalgudi** [chef/supermarket#1612]
Hi Everyone,
I'm trying to set up a supermarket, these are the version am using 
**Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36**
The configuration on chef servers are:
**/etc/opscode/chef-server.rb** 
oc_id['administrators'] = ["sam"]
oc_id['applications'] ||= {}
oc_id['applications']['supermarket'] = {
  'redirect_uri' => 'my.supermarket.com/.fqdn/auth/chef_oauth2/callback'
}
**/etc/opscode/oc-id-application/supermarket.json**
{
  "name": "supermarket",
  "uid": "uid",
  "secret": "secretkey",
  "redirect_uri": "my.supermarket.com.fqdn/auth/chef_oauth2/callback"
}
On supermarket 
**/etc/supermarket/supermarket.rb**
{
  "features": "tools, gravatar, collaborator_groups",
  "chef_server_url": "chefserverurl",
  "chef_oauth2_app_id": "appid",
  "chef_oauth2_secret": "secret id",
  "chef_oauth2_verify_ssl": false
}
I'm able to redirect from supermarket to the chef server for login,after login I get an error saying 

> **Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method**
![image](https://cloud.githubusercontent.com/assets/22880082/26549996/59052722-4499-11e7-9435-b0d3406dc5ec.png)

And I tried to authorized application but when I click on authorized application I get this:
![image](https://cloud.githubusercontent.com/assets/22880082/26550039/8b88fef8-4499-11e7-9189-1c9eec54feaa.png)

But i can find my application in the application page
![image](https://cloud.githubusercontent.com/assets/22880082/26550063/a7560a4a-4499-11e7-9561-6aeec764da0c.png)

So could anyone please guide me through this. It would be really helpful.

Thanks :)

**Comment by robbkidd** [comment]
Is `https://ip-172-31-31-60.us-west-2.compute.internal.fqdn` the URL you visit in your browser to get to the private Supermarket?

I'm 97.6% confident this error is caused by a mismatch between the fully-qualified domain name you enter into the browser to get to the Supermarket, the FQDN the Supermarket is told to serve as, and the FQDN for the Supermarket's `redirect_uri` in the Chef Server's `oc-id` applications list. All must match for there to be trust between them.

**Comment by sameerakalgudi** [comment]
Hi @robbkidd 
https://ip-172-31-31-60.us-west-2.compute.internal.fqdn is the FQDN of my supermarket, but I use a different URL to access my supermarket in the browser.

Is It necessary to use FDQN only in the redirect URI?? Because if i change the FQDN URL with the browser access URL even than I get the error.

**Comment by sameerakalgudi** [comment]
Hi @robbkidd
I have changed the configuration in the chef-server, But also I'm getting the same error.

![e1](https://cloud.githubusercontent.com/assets/22880082/26570863/5574f6e0-4530-11e7-9c66-ae42307d1739.PNG)
![e2](https://cloud.githubusercontent.com/assets/22880082/26570866/55a58fbc-4530-11e7-9424-e11dd8e38adb.PNG)
![e3](https://cloud.githubusercontent.com/assets/22880082/26570867/55d60264-4530-11e7-8a1f-ed0441fa9ed6.PNG)



I'm uploading the same screenshots
Please guide me.

Thanks :)

**Comment by fernandoaleman** [comment]
@sameerakalgudi Did you ever get this issue fixed? I am encountering the same error now. The supermarket and Chef server were working fine a week ago, but today I am getting the same errors you described above.
