### ISSUE TITLE
Error Uploading Cookbook to Supermarket.

### ISSUE THREAD

**Issue by srirammageswaran** [chef/supermarket#1613]
When i try to upload cookbook i get an exception 

ERROR: Tarball has contents that are not what they are reported to be

knife supermarket share cookbook_name -VV -o . --supermarket-site https://XXXXXXXX.YYYYY.com

Knife Supermarket gem version in 0.3.0.

Thanks ,
Sriram Mageswaran

**Comment by robbkidd** [comment]
@srirammageswaran 

> ERROR: Tarball has contents that are not what they are reported to be

This is an error coming from the file handler within Supermarket. When it validated the uploaded gzipped tar file, it found that the file type of the actual contents did not appear to be a gzipped tarball.

Some things to try:
+ Use the latest [ChefDK](https://downloads.chef.io/chefdk).
+ Do not use the `knife-supermarket` gem separately; the gem was deprecated when the `supermarket` commands were added directly to `knife` in core Chef v12.11.19
+ Try publishing the cookbook with a different client, like [`stove`](https://github.com/sethvargo/stove)

<details><summary>stove example</summary><p>
```
stove --no-git --endpoint https://XXXXXXXX.YYYYY.com/api/v1 --path </path/to/cookbook_name>
```
</p></details>

**Comment by robbkidd** [comment]
@srirammageswaran Did you try some of the options offered above? I'll be closing this issue in a couple days unless there is some more information to troubleshoot with.
