### ISSUE TITLE
Unable to upload latest version of cookbook

### ISSUE THREAD

**Issue by amimanda** [chef/supermarket#1617]
Recently I have uploaded cisco_imc_cookbook v0.9.1, but since it was showing some quality issues so I have added some more data in metadata.rb file. Also incremented the version to 0.9.2 in metadata.rb. Now when I am trying to share the cook it is failing with error "Version has already been taken"
Cookbook url : https://supermarket.chef.io/cookbooks/cisco_imc_cookbook/
I have tried to unshare the cook book and re-share but nothing seems to be working for me. Kindly help on this issue as soon as possible.

**Comment by robbkidd** [comment]
@amimanda Are you still having trouble uploading cisco_imc_cookbook v0.9.2 to the public Supermarket? I've confirmed that a 0.9.2 does _not_ currently exist for the versions to conflict and the [version bump change you made in source](https://github.com/CiscoUcs/cisco_imc_cookbook/commit/8a1b14c6eea8dcb8f401740cd8fa7a4f1c33b41b) looks correct.

**Comment by amimanda** [comment]
@robbkidd Yes, I am still facing the issue. Here I have pasted what I see when I run the 
knife supermarket command.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>**knife supermarket share "cisco_imc_cookbook" "Operating Systems & Virtualization" --verbose**
INFO: Using configuration from /Users/amimanda/Documents/Code/chef-repo/.chef/knife.rb
INFO: Validating ruby files
INFO: Validating templates
INFO: Syntax OK
Generating metadata for cisco_imc_cookbook from /var/folders/6c/jft0k9zj5ydf4q2c4rhhh5f80000gn/T/chef-cisco_imc_cookbook-build20170616-65583-1958u3y/cisco_imc_cookbook/metadata.rb
Making tarball cisco_imc_cookbook.tgz
**ERROR: Version has already been taken**

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by robbkidd** [comment]
@amimanda

+ In what directory are you running the command?
+ Where is the cisco_imc_cookbook directory relative to where you are running the command?
+ What is the current commit id of the cisco_imc_cookbook git repo?

**Comment by amimanda** [comment]
@robbkidd 
I have tried to run the command from the following folders:
1. chef-repo
2. chef-repo/cookbook
3. chef-repo/cookbook/cisco_imc_cookbook

Last commit to github : https://github.com/CiscoUcs/cisco_imc_cookbook/tree/402a4334ceeb63e3bfa90fcde410373f773e907b

**Comment by amimanda** [comment]
@robbkidd 
Is there any other information you are looking from my end?
Also, please let me know if you want me to try out something on my side. 
In case a meeting will help please let me know I can setup a Webex meeting with you.

**Comment by robbkidd** [comment]
@amimanda 

I can certainly get on a screen share with you to troubleshoot. You can find me more synchronously in the [Chef Community Slack](http://community-slack.chef.io/) for working out a time. I'm on the American east coast.

**Comment by robbkidd** [comment]
@amimanda Has there been any progress on fixing this? I'll be closing this issue in a couple days unless there is some more information to troubleshoot with.

**Comment by f0rkz** [comment]
Ran into this myself and discovered I had a copy of the cookbook (old version) somewhere else in my cookbook path. I deleted the old cookbook and the new cookbook uploaded no problem.
