### ISSUE TITLE
Link to all past and present chat venue archives

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1619]
With the move to Slack and [updating the Supermarket links pointing at IRC to Slack](https://github.com/chef/supermarket/issues/1603), we've removed links to the old IRC archive. Should we add those back in?

@nathenharvey What are your thoughts on continuing to maintain links in Supermarket to chat logs in what will be three different places—SlackArchive, BotBot for IRC, and GitHub for old stuff prior to 2013-08-08—based on date? That's starting to get weird.

```
> ack IRC app
app/controllers/irc_logs_controller.rb
5:  # Redirects to the botbot.me dashboard (list of IRC channels).
15:  # later (that is the first known day of botbot.me logging the IRC chat).
17:  # Redirects to the GitHub repo of IRC logs stored in the previous community

app/views/layouts/application.html.erb
47:            <li><%= link_to 'Botbot IRC Logs', 'https://botbot.me/freenode/chef', target: '_blank' %></li>

app/views/profile/edit.html.erb
35:              <%= f.label :irc_nickname, "IRC Nickname" %>
36:              <%= f.text_field :irc_nickname, placeholder: 'IRC Nickname', title: 'irc nickname' %>

app/views/users/_sidebar.html.erb
39:      <li class="has-tip" title="<%= posessivize(@user.name) %> IRC Nickname">
```

**Comment by tas50** [comment]
There is no slack archive system so I'm going to close this one out at this point.
