### ISSUE TITLE
csrf detected private supermarket

### ISSUE THREAD

**Issue by zstauffer** [chef/supermarket#1628]
I just finished setting up Chef Server, and private supermarket using the directions from https://docs.chef.io/install_chef_automate.html and https://docs.chef.io/install_supermarket.html. I finished the instructions down to the "Connect to the supermarket" section. I am able to navigate to my supermarket home page but when I hit the "Create Account" button I get a page that says "The page you were looking for does not exist" and am sent to the url https://mychefserver.com/signup?ref=community. When I try to put in the full url (https://mychefserver.com/auth/chef_oauth2/callback) I get a page that says "The associated provider returned a failure message." and I am sent to the url https://mychefserver.com/auth/failure?message=csrf_detected&strategy=chef_oauth2. I think the problem is with the self-signed cert but none of the suggestions I have found so far have resolved the issue. The contents of my /etc/opscode/chef-server.rb file are:

oc_id['applications'] ||= {
'supermarket' => {
'redirect_uri' => 'https://mychefserver,com/auth/chef_oauth2/callback'
}
}

**Comment by mohamednazar** [comment]
There is comma in your chef-server.rb file instead of . 
'https://mychefserver,com/auth/chef_oauth2/callback'

please check

**Comment by mohamednazar** [comment]
Have you done setting up Chef Automate and Private Super Market on AWS environment?

**Comment by mohamednazar** [comment]
I am having issue to setup private super market server on AWS Chef Automate. Can you please let me know how you completed it?
