### ISSUE TITLE
[QUESTION] Can the Chef Supermarket UI be used with Artifactory?

### ISSUE THREAD

**Issue by pantocrator27** [chef/supermarket#1637]
We are currently using Artifactory to proxy the Chef Supermarket and serve as our private supermarket.  Is it possible to use the Chef Supermarket UI with Artifactory?

**Comment by robbkidd** [comment]
> Is it possible to use the Chef Supermarket UI with Artifactory?

No. The Supermarket web UI is driven by content stored and managed within an instance of Supermarket itself.
