### ISSUE TITLE
quality metrics runs should be triggered by events other than cookbook upload

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1691]
If a user transfers a cookbook and selects that they want to add the current owner as a collaborator the collaborator quality metric isn't triggered. The addition of this new collaborator could potentially change the outcome of the metric.

When you remove a collaborator from a cookbook we don't trigger a rescore of the cookbook. I had a cookbook with 2 collaborators and I removed both, but the collaborators metric still passes when it should now fail.

Events that should trigger quality metric run:
* transfer ownership
* put up for adoption
* add a collaborator (maybe already implemented? see below)
* remove a collaborator

Quality metric runs currently get triggered by:
* [a cookbook upload](https://github.com/chef/supermarket/blob/13c950c9fdbd6ced308d4cd22837c9142023d9d0/src/supermarket/app/controllers/api/v1/cookbook_uploads_controller.rb#L59-L63).
* [a collaborator being added](https://github.com/chef/supermarket/blob/13c950c9fdbd6ced308d4cd22837c9142023d9d0/src/supermarket/app/controllers/collaborators_controller.rb#L43-L45)

**Comment by msys-sgarg** [comment]
We can close this issue since PR is merged
