### ISSUE TITLE
Celluloid is deprecated, git submodule missing, bundle install broken

### ISSUE THREAD

**Issue by rmoriz** [chef/supermarket#1754]
```
➜  supermarket git:(master) bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching https://github.com/rubysec/bundler-audit.git
Fetching https://github.com/celluloid/celluloid
Submodule 'culture' (http://github.com/celluloid/culture.git) registered for path 'culture'
Cloning into '/Users/rmoriz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/celluloid-0d192022ffff/culture'...
remote: Repository not found.
fatal: repository 'https://github.com/celluloid/culture.git/' not found
fatal: clone of 'http://github.com/celluloid/culture.git' into submodule path '/Users/rmoriz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/celluloid-0d192022ffff/culture' failed
Failed to clone 'culture'. Retry scheduled
```

Celluloid is unmaintained and its former maintainer decided to delete http://github.com/celluloid/culture from github. 

supermarket uses a hard coded ref of the `celluloid` repo that still contains a submodule reference to the now deleted submodule:

https://github.com/chef/supermarket/blob/master/src/supermarket/Gemfile#L17-L18

Looks like someone (Chef Software?) either needs to sponsor the Celluloid maintainer or remove the dependency: https://github.com/celluloid/celluloid/issues/779

**Comment by robbkidd** [comment]
A quick copy of some of what was said on #1755:

> Celluloid is a dependency of Sidetiq which is what Supermarket currently uses to handle scheduled background jobs in Sidekiq. Sidetiq's use of the Celluloid DSL breaks with this update.

> Sidetiq is also not maintained anymore. I believe the solution will be reassessing Supermarket's need for scheduled background jobs and, if determined that they are still needed, finding a replacement for scheduled jobs.

I am investigating alternatives.
