### ISSUE TITLE
How to edit the description below the "ABOUT TOOLS" section in private super market ???

### ISSUE THREAD

**Issue by saivv** [chef/supermarket#1800]
I am trying to edit the description below the "about tools" section our private super market to make it more clearer for our users in the organisation.

Is there any way I can edit Java scripts availabe on our server that are live on the site and 
can be changed  ??? Please help me out, thanks in advance!

**Comment by Stromweld** [comment]
@saivv looks like this line in a gemspec file should do it.
https://github.com/berkshelf/berkflow/blob/master/berkflow.gemspec#L11

**Comment by robbkidd** [comment]
@saivv Are you talking about the text that appears under "About Tools" on [the Tools directory page](https://supermarket.chef.io/tools-directory)? That text is hard-coded in [the tools directory view code](https://github.com/chef/supermarket/blob/0c18a9fa259cf660cb0e2420361592ae7c918068/src/supermarket/app/views/tools/directory.html.erb#L8-L9). Supermarket does not currently support a way to customize that per-install.

Do you think your intended edits to the description there might make it clearer to _any_ user in _any_ organization? Maybe your edits would be appropriate as an update to the text included in all installs. Can you share what your changes would be?

**Comment by robbkidd** [comment]
Closing this issue from inactivity. Feel free to reopen the issue if there is more information you can provide about the problem.
