### ISSUE TITLE
supermarket-ctl should have a version option

### ISSUE THREAD

**Issue by Xorima** [chef/supermarket#1805]
All other chef software supports the `version` flag, I would expect this to be consistent across all chef binaries

# Describe the problem
As a user I want to see the version of supermarket I am running

## Replication Case
run `supermarket-ctl version`

## Possible Solution
add in `version` flag

**Comment by robbkidd** [comment]
A `supermarket-ctl version` command would like a lot like [`chef-server-ctl version`](https://github.com/chef/chef-server/commit/eb063c0fd4ba3d56e8f85cb1c9abb8eb8b39b0e9) but in Supermarket's [`omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands`](https://github.com/chef/supermarket/tree/master/omnibus/cookbooks/omnibus-supermarket/files/default/ctl-commands).

I'm going to mark this as a decent first-time contribution. I'll help someone contribute this, if there is interest. I'm also willing to be told I'm deluded and that this is _not_ a good first issue.
