### ISSUE TITLE
Changelogs on supermarket render markdown comments

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1831]
Expeditor loves comments so this results in a pretty bad looking changelog:

See https://supermarket.chef.io/cookbooks/chef-sugar#changelog

**Comment by msys-sgarg** [comment]
When we talk about comments we mean this right ? In the changelog 

```
<!-- latest_release --> <!-- latest_release -->

<!-- release_rollup --> <!-- release_rollup -->

<!-- latest_stable_release -->

```

**Comment by msys-sgarg** [comment]
I am closing the issue Since PR is merged
