### ISSUE TITLE
Make deprecated cookbooks show up at the bottom of search

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1838]
# Describe the problem
Right now the deprecated vault cookbook shows up at the top of the list. We definetly don't want people using this. We should either hide this entirely or put it at the very bottom of the search results.

## Software Version
Currently deployed stable

## Replication Case
Search for vault.

**Comment by msys-sgarg** [comment]
Closing this issue, since the PR is merged https://github.com/chef/supermarket/pull/2058
