### ISSUE TITLE
installs with multiple web hosts throw unexpected CSRF errors

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1839]
# The problem

As of Supermarket 3.3.12, [the fix for actually reading in `secrets.json` during `supermarket-ctl reconfigure`](https://github.com/chef/supermarket/pull/1832) will cause **Supermarket installations with multiple web front-ends to throw cross-site scripting forgery errors for authenticated web UI interactions**. Comparing the contents of `secrets.json` on the front-end hosts will show that each has a different `secret_key_base` value. This causes each web front-end to distrust cookies written by any of the other front-ends.

## Some Background

Rails applications use a secret named `secret_key_base` as "the input secret to the application's key generator, which in turn is used to create all MessageVerifiers/MessageEncryptors, including the ones that sign and encrypt cookies." 

The command `supermarket-ctl reconfigure` will create a `secrets.json` file if one is not already present. In Supermarket versions up to 3.3.14, reconfigure creates a `secret_key_base` key, sets the value to a randomly generated hexadecimal string, and then "consumes" `secrets.json` into the node object. Once the `secrets.json` file was created, subsequent runs of `reconfigure` _entirely ignored it_ and never read those keys into the `reconfigure` run again (a bug fixed in #1832). As a result, all current Supermarket installations are setting `secret_key_base` in either `supermarket.rb` or `supermarket.json`. Left behind on every Supermarket web host is a `secrets.json` file with a uniquely created `secret_key_base`.

Configuration starts with `supermarket.rb`, is overridden by what is found in `supermarket.json`, which is overridden again by what is found in `secrets.json`. Now that Supermarket is paying attention to `secrets.json` in every `reconfigure` run, the previously unique-per-host secret is winning which causes each web host to distrust anything hashed or signed by the other web hosts.

## Software Version

Versions 3.3.12 - 3.3.14
 
## Replication Case

A Supermarket install:
* running 3.3.12 to 3.3.14
* with two or more web application hosts

Attempts to login will fail. The URL in the browser location will mention `csrf`. 

## Possible Solution(s)

1. Manage the contents of `secrets.json` with the wrapper cookbook (or whatever deployment automation is in use) that is installing Supermarket services. Either touch the file and leave it empty or write to it the key/value pair for `secret_key_base` to use across all web front-end hosts.
2. Code change to [the omnibus reconfigure logic that generates `secrets.json` if it doesn't exist](https://github.com/chef/supermarket/blob/03748bdad67c2b515b3fd838036d1c1caee4a96d/omnibus/cookbooks/omnibus-supermarket/libraries/config.rb#L49-L53). The built-up-so-far state of the node object is available and could write the `secret_key_base` key/value pair if it has already been set in `supermarket.rb` or `supermarket.json`.
3. Code change to the omnibus reconfigure logic to _not_ generate a `secrets.json` file. Default behavior without configuration by an administrator would prevent the web application from starting up because `secret_key_base` would not be set at all.
4. Code change to the omnibus reconfigure to rollback the fix made in #1832. Basically, go back to ignoring `secrets.json`. Or remove considering that file as a source of config values entirely since it has never truly been a part of an operational Supermarket install.

**Comment by teknofire** [comment]
Based on our conversation and looking through the code it seems like the right fix is option #2.  

If the user has configured `secret_key_base` it in supermarket.{rb|json} and `secrets.json` doesn't exist we should use that value and create a `secrets.json` file. Along with a message that the setting now exists in the new file and they will need to copy it to the other front-end Supermarket servers.

**Comment by teknofire** [comment]
One question that does come to mind though is what happens if the setting is in `supermarket.{rb|json}` and `secrets.json` but has a different value.  Should we print a message/fail the reconfigure with a message to the user that they need to fix it?

**Comment by robbkidd** [comment]
> [W]hat happens if the setting is in `supermarket.{rb|json}` and `secrets.json` but has different values. Should we fail the reconfigure with a message to the user that it needs to be fixed?

@teknofire: My first thought is to proceed with the override and use the value given in `secrets.json`. I don't think it's a failure, but maybe it warrants a warning to the administrators. So long as it's the same value in `secrets.json` for all web front ends, the actual value does not matter.
