### ISSUE TITLE
Deprecate foodcritic quality metric QM009 in favor of QM008

### ISSUE THREAD

**Issue by sam1el** [chef/supermarket#1842]
Supermarket is still using foodcritic as a metric which is no longer best practice. 

# Describe the problem
Foodcritic is essentially fully deprecated. We should be using cookstyle which is the best practice we give customers. 
I also feel this would help us to identify severely broken and deprecated cookbooks. 

## Software Version
This is specific to public supermarket

## Possible Solution
Replace QM009 with QM008 which are listed here.

https://github.com/chef-cookbooks/cookbook-quality-metrics-rfc/tree/master/quality-metrics

**Comment by sam1el** [comment]
I realize this isn't an easy undertaking. I am looking in to what I can do to assist currently

**Comment by tas50** [comment]
This is something I'd like to figure out how to do. I'm not sure if I'll be able to do it since I've never touched Rails, but this really needs to happen so we can fully deprecate Foodcritic.

**Comment by tas50** [comment]
This is covered in #2181
