### ISSUE TITLE
Use Content Security Policies to prevent against XSS

### ISSUE THREAD

**Issue by cattywampus** [chef/supermarket#1854]
# Describe the problem

A [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) is an HTTP response header that informs the client how to execute specific types of content, such as javascript and stylesheets. When websites whitelist specific sources for these kinds of resources browsers are able to protect users from potential vulnerabilities and attacks. 

After a security scan of our on-premise Chef Supermarket, it looks like CSP is currently not implemented. This is currently a LOW security finding so we aren't in a rush to resolve this, however, it would be great to have one less finding in our report.
 
## Software Version

Tested against the latest version of Chef Supermarket - 3.3.20

## Replication Case

* Inspect the HTTP response headers sent from the Chef Supermarket Webserver
* There is currently no `Content-Security-Policy` header being set

## Stacktrace

<details><summary>  </summary>
```
N/A
```
</details>

## Possible Solution

Ruby on Rails [added support](https://guides.rubyonrails.org/5_2_release_notes.html#content-security-policy) for Content Security Policies in Rails 5.2, however supermarket is still using 5.0. At the risk of Yak shaving, it might make more sense to upgrade Rails first and then implement a CSP solution within the construct / convention that Rails provides, since asset management is already managed by Rails.

**Comment by tas50** [comment]
This will ship in the next release
