### ISSUE TITLE
deprecation resolution: change over to form_with

### ISSUE THREAD

**Issue by robbkidd** [chef/supermarket#1869]
Over on #1867:

> Also I know `form_for` and `form_tag` have been soft-deprecated as of 5.1 for `form_with`. (i.e. it won't cry out at us but they [aren't mentioned in current documentation](https://guides.rubyonrails.org/form_helpers.html#using-form-for-and-form-tag). But there's no harm keeping them around for now.
>
> I only know that because [I got drafted into rewriting those docs](https://github.com/rails/rails/pull/33523)

**Comment by skkprogress** [comment]
Note: Use this ticket as a chance to audit and find all other deprecations that need to be addressed in the codebase
