### ISSUE TITLE
We should add the cookbook adoption policy/procedure to supermarket.chef.io

### ISSUE THREAD

**Issue by bennyvasquez** [chef/supermarket#1884]
Most folks that use Chef Supermarket on a regular basis don't interact with the github repo, and are unlikely to see our addition of the [cookbook adoption policy](https://github.com/chef/supermarket/blob/master/docs/cookbookadoptiononsupermarket.md). This would serve our community better if it existed somewhere on the [supermarket.chef.io](supermarket.chef.io) website. 

## Possible Solution
It should likely go [under documentation](https://supermarket.chef.io/documentation), but additional places may also be useful. For example, if we can have it programmatically display on cookbooks that haven't been updated in a while (assuming that we track the length of time since a cookbook was last updated).

**Comment by tas50** [comment]
This was done

**Comment by bennyvasquez** [comment]
It's in the repo, but not on the site yet. opening back up.

**Comment by tas50** [comment]
This shipped in 3.4.8 and ops has been requested to deploy it so I'm going to close this out now.
