### ISSUE TITLE
How do I publish a compliance profile to Chef Supermarket?

### ISSUE THREAD

**Issue by splatteredbits** [chef/supermarket#1889]
A Google search turns up nothing. I can create a tool in the Supermarket, but nowhere does it let me upload/publish it. 

I'm trying to figure out how to create custom Inspec resources that I can share across cookbooks. I'm trying to publish a compliance profile with my custom resource to an internal supermarket but can't find any documentation on how to do this.

**Comment by robbkidd** [comment]
Hi, @splatteredbits! Your searches are not turning up anything because Supermarket does not store and serve up InSpec profiles. Only cookbooks are handled as versioned artifacts. Other things like profiles, knife plugins, and such are "tools" and Supermarket only supports references to them.

**Comment by splatteredbits** [comment]
Ah. Then should [this section](https://docs.chef.io/inspec/profiles/#supermarket) be removed from the docs? It lists the Supermarket as an option for defining dependencies:

```
depends:
- name: supermarket-profile
  supermarket: supermarket-username/supermarket-profile
```

**Comment by robbkidd** [comment]
That _is_ a bit confusing. However, InSpec _can_ retrieve a profile through Supermarket, if the profile has been added as a tool and includes a reference to the profile's source repository. It's a sort of transitive look up.

**Comment by splatteredbits** [comment]
I'm assuming the profile would have to be in its own repository? That if a cookbook has an inspec resource in it that it wants to publish that wouldn't work?

**Comment by robbkidd** [comment]
🤔  I don't quite know what would happen in that case. Probably wouldn't work unless the profile content was at the root of the git repo. 😬
