### ISSUE TITLE
supermarket.chef.io api returning 500 errors for various packages

### ISSUE THREAD

**Issue by shaynagar1** [chef/supermarket#1891]
We have encountered the issue on both apache2@5.0.1 and ark@5.0.0 on various instances, however, the problem appears to be more widespread.

```
[2020-10-04T06:09:13-04:00] INFO: Installing zypper (0.4.0) from https://supermarket.getchef.com ([opscode] https://supermarket.chef.io:443/api/v1
06:09:14
  [2020-10-04T06:09:14-04:00] INFO: An unexpected error occurred retrieving 'ark' (5.0.0) from the cookbook site at 'https://supermarket.chef.io:443/api/v1'.
06:09:14
```

When I'm trying to curl straightly supermarket api I got 500.

```   
curl -i https://supermarket.chef.io:443/api/v1


HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Date: Sun, 04 Oct 2020 14:43:12 GMT
Server: nginx
X-Request-Id: 5974fbdc-7664-469c-9475-c92430dd7daa
X-Runtime: 0.009514
Content-Length: 182
Connection: keep-alive
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

Maybe it is related to the new release from 5 days ago [3.3.35](https://github.com/chef/supermarket/releases/tag/3.3.35)

**Comment by robbkidd** [comment]
@shaynagar1 Hi! Thanks for opening this issue. I am suspicious of at release now, too.

What commands are returning this error? What version(s) of what client(s) are you using?

**Comment by robbkidd** [comment]
I am not able to replicate with my current clients. With berkshelf 7.1.0 packaged within Chef Workstation 20.9.158:

```
» berks install
Resolving cookbook dependencies...
Fetching 'experimental-cookbook' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Using apt (3.0.0)
Using experimental-cookbook (0.6.6) from source at .
Using seven_zip (3.1.2)
Installing ark (5.0.0)
Installing zypper (0.4.0)
Installing windows (7.0.2)
```

**Comment by robbkidd** [comment]
@shaynagar1 Just for double-check, could you give your instances another go? Thanks to this and another reports, we discovered a degraded host in Supermarket's cluster that wasn't triggering any alarms (which we will get on remedying). That host was coughing up 500s and might have been the source of the behavior you saw.

As an aside, the URI path `/api/v1` will always return a 500 at the moment, though it really ought to be returning a 404. There is no route at that path. Add `cookbooks` and you'll have a good test route: `curl -i https://supermarket.chef.io:443/api/v1/cookbooks`

**Comment by shaynagar1** [comment]
@robbkidd Tnx a lot for your quick and detailed respond. I gave it another go at 7AM (Israel time) and now it seems that everything works as expected.

**Comment by robbkidd** [comment]
![It's working!](https://user-images.githubusercontent.com/517302/95095141-ac75f600-06f8-11eb-8534-0f4154f5c334.gif)

Thanks again for reporting, @shaynagar1!

**Comment by ssssSoulEater** [comment]
@robbkidd 
I met this failure today:
An unexpected error occurred retrieving 'ark' (5.0.0) from the cookbook site at 'https://supermarket.chef.io:443/api/v1'.

And when I run:
curl -i https://supermarket.chef.io:443/api/v1
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Date: Tue, 13 Oct 2020 03:08:10 GMT
Server: nginx
X-Request-Id: 6a59b98c-dc56-478d-ab66-5023d797761f
X-Runtime: 0.009527
Content-Length: 182
Connection: keep-alive

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by shaynagar1** [comment]
@robbkidd 
Hi again, I'm also getting the same error, This time we have encountered it with aws@7.2.2.
```
INFO: An unexpected error occurred retrieving 'aws' (7.2.2) from the cookbook site at 'https://supermarket.chef.io:443/api/v1'.
```
