### ISSUE TITLE
Quality metrics do not get updated in the public supermarket

### ISSUE THREAD

**Issue by axl89** [chef/supermarket#1899]
# Describe the problem
After uploading [a new cookbook](https://supermarket.chef.io/cookbooks/ovh_the_bastion) to the Chef Supermarket on November 28th, the quality metric section is still empty as of today:

![image](https://user-images.githubusercontent.com/939418/101071827-6e347000-359d-11eb-8839-71dabae38ef0.png)

I believe that the expected behavior should be for the quality metrics to be populated at some point.

## Software Version
- OS: Ubuntu 20.04.1 LTS
- ChefDK version: 4.12.0
  - Chef Infra Client version: 15.14.0
  - Chef InSpec version: 4.23.11
  - Test Kitchen version: 2.7.2
  - Foodcritic version: 16.3.0
  - Cookstyle version: 5.23.0

## Replication Case

I uploaded the cookbook with the `knife supermarket share` utlity, and no output error was shown, even with the verbose options activated.

## Stacktrace

<details><summary>  </summary>
None
</details>

## Possible Solution
I've already asked in the `#supermarket` channel of Chef's Slack community, and @tas50 suggested that this could be a bug.

**Comment by grubberr** [comment]
Don't work for me too :(

**Comment by msys-sgarg** [comment]
Hi, i see a url call is made for chef supermarket to retrieve quality metrics for a cookbook like this in the code - 

```
    URI.parse("#{ENV["FIERI_SUPERMARKET_ENDPOINT"]}/api/v1/cookbooks/#{cookbook_name}")
```

For the evaluation purpose. Can I get the result of this api call for any cookbook ....  may be `mysql` ? Or what is the value of of this environment variable `ENV["FIERI_SUPERMARKET_ENDPOINT"]` for live supermarket ? 

This is important for me to zero down the possibility whether the data is getting at all retrieved from this api call ? Or there are any issues in storing that on the application side .. ?

**Comment by msys-sgarg** [comment]
I need output for this query for the live application - `select * from quality_metrics where admin_only = false;` . if a quality metric is marked as admin_only its not displayed in UI by default.

**Comment by msys-sgarg** [comment]
Hi, please provide me an access so that I can move forward on this issue. Thanks

**Comment by btm** [comment]
@msys-sgarg That's data from a database in the production deployment, so I asked 
@bikashATprogress from the Platform Ops team to help, the reference number from him was PS-1825. Please touch base with him in a few days on slack if you don't hear from him.

**Comment by msys-sgarg** [comment]
Thanks @btm

**Comment by msys-sgarg** [comment]
https://chefio.slack.com/archives/C07JNP49J/p1624890994139500 - 

As per comment here in discussion, the issue was with nginx settings .. which was stopping sidekiq queue to get processed and jobs to update metrics were not running. Its fixed both in production and staging

**Comment by tas50** [comment]
This was resolved with a config change in production. Everything should be reporting again.
