### ISSUE TITLE
Upgrade to Chef Infra Client 16 (and then 17)

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1923]
We need to get on a supported release of Chef Infra Client. Upgrade to Chef Infra Client 16 and then on to 17.

**Comment by RajeshPaul38** [comment]
Chef infra client upgraded to version 17.5

![Screenshot 2021-09-30 at 7.34.04 PM.png](https://images.zenhubusercontent.com/60b7868792ea6cd3231262be/d9e41d8a-c9ef-4845-894b-82418a277a47)
