### ISSUE TITLE
Rename "handler" to "Chef Infra handler"

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1970]
At https://supermarket.chef.io/tools we nee to rename "handler" to "Chef Infra handler"

**Comment by msys-sgarg** [comment]
Do we need to rename the tool type to `Chef Infra Handler` which will require a database change ? Or is it just UI change on this page instead https://supermarket.chef.io/tools-directory ?

**Comment by tas50** [comment]
This is just the UI side of things.
