### ISSUE TITLE
Make sure server headers do not report nginx

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1978]
We don't want to disclose that we're running nginx in Supermarket. We should make sure we disable the server header entirely to avoid disclosing this information. There's a customer escalation for this here: https://github.com/chef/customer-bugs/issues/366

**Comment by skkprogress** [comment]
Will fixing this fix this one too? https://github.com/chef/customer-bugs/issues/415

**Comment by tas50** [comment]
I believe those are different

**Comment by RajeshPaul38** [comment]
@tas50 I've gone through the supermarket issue: https://app.zenhub.com/workspaces/sustaining-engineering-progress-60c9e8f0307f65000e50585a/issues/chef/customer-bugs/366

So is this ticket really about hiding the server header from the response headers or is it about not allowing the Host header in the request? Need clarity.

**Comment by tas50** [comment]
To recap our convo the issue here is nginx does not allow you to remove the "server" response from the headers. We need the headers more module to nuke this similar to how we're doing it in server:

https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/templates/default/nginx/nginx.conf.erb#L150

The problem there is this mostly becomes an omnibus build issue. We need to figure out how to get that module compiled into nginx in our build. In server we use openresty and it comes bundled as part of openresty.

**Comment by RajeshPaul38** [comment]
Openrestry has only 8-9% market share and the rest is of nginx i.e. 92%. Hence sceptical of it's long term support and and development in future. @tas50 

![Screenshot 2021-08-16 at 5.38.14 PM.png](https://images.zenhubusercontent.com/60b7868792ea6cd3231262be/df25b859-6bb0-4ce8-a6d6-99a492cb1794)

**Comment by RajeshPaul38** [comment]
Would try to find other alternatives too.

**Comment by tas50** [comment]
Yeah I'm not suggesting we move to openresty. Just saying that it gives us this same module we will need to delete the headers

**Comment by RajeshPaul38** [comment]
Had success using openresty. Have successfully done omnibus build in ec2. Running on buildkite now:
https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/158#74283f19-274d-4782-8170-c699dd8ca205

Will raise PR post success of the buildkite build.

**Comment by RajeshPaul38** [comment]
Had successful buildkite build with changed inspec testcases: https://buildkite.com/chef/chef-supermarket-master-omnibus-adhoc/builds/159#55140c15-b091-451f-b4f6-0ab507c0a262

Raising PR: https://github.com/chef/supermarket/pull/2161
