### ISSUE TITLE
Evaluate brakeman identified security issues

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2016]
This repo is now being scanned by Brakeman for potential rails security vulnerabilities. We need to evaluate the issues raised by Brakeman and determine what needs to be resolved and what needs to be ignored via the scanner config.

See results here:
https://github.com/chef/supermarket/security/code-scanning

**Comment by RajeshPaul38** [comment]
Running brakeman gem in local and fixing the errors which are real vulnerabilities. Also added methods. to ignore list if not a real vulnerability.

**Comment by RajeshPaul38** [comment]
PR: https://github.com/chef/supermarket/pull/2095
