### ISSUE TITLE
Update the development documentation for 2021

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2025]
We need to ensure the development documentation is accurate and the process is as streamlined as possible. Validate the current documentation and update it as necessary.

An example of the kind of changes we'll probably make: https://github.com/chef/supermarket/pull/1885

**Comment by dheerajd-msys** [comment]
PR https://github.com/chef/supermarket/pull/2039 has some README updates.

**Comment by btm** [comment]
There's a significant amount of internal documentation (some newer than others) here: https://chefio.atlassian.net/wiki/spaces/COMMUNE/pages/22347778/Supermarket

**Comment by dheerajd-msys** [comment]
Relevent PRs https://github.com/chef/supermarket/pull/2059 & https://github.com/chef/supermarket/pull/2062
