### ISSUE TITLE
Get permissions to zenhub

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2042]
@skkprogress commented on [Mon Jul 05 2021](https://github.com/chef/chef/issues/11778)

---

@skkprogress commented on [Mon Jul 05 2021](https://github.com/chef/chef/issues/11778#issuecomment-874088865)

1. Creating tickets
2. Moving tickets
3. Creating/Closing sprints
4. Adding milestones
5. Ticket assignment

- [ ] Dheeraj

- [ ] Sabyasachi

- [ ] Rajesh

**Comment by btm** [comment]
This should for everyone now.
