### ISSUE TITLE
Supermarket profile doesn't display correctly with a large number of collaborations

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2139]
If you have too many cookbooks you collaborate with the content displays off screen and shifts all the other content in a very strange way. The screenshot below is from the very top of the browser window. Notice where my profile pic is rendering.

Firefox 91 on macOS

![image](https://user-images.githubusercontent.com/1015200/129403059-76a33d2d-d487-4ae2-b9de-80f17eb05d4a.png)

**Comment by msys-sgarg** [comment]
Closing the issue since PR is merged
