### ISSUE TITLE
"Remove Myself as a Collaborator" in profile needs confirmation

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2140]
Currently in your profile you can click "Remove Myself as a Collaborator" and it removes you without any sort of confirmation. We need a modal to confirm if the user really wants to do this.

"Are you sure you want to remove yourself as a collaborator from the cookbook FOO? You will not be able to add yourself back without the help of the cookbook owner."

yes/no

**Comment by msys-sgarg** [comment]
closing this issue as the PR is merged
