### ISSUE TITLE
Replace IRC with Slack username in Supermarket profiles

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2150]
We no longer maintain an IRC channel as a community and we long ago moved to Slack. We should update the profile to allow users to set their Slack handle instead of the IRC name.

## Removal of Legacy fields:

- Profile pages like this https://supermarket.chef.io/users/tas50 do not list IRC usernames
- Profile edit page https://supermarket.chef.io/profile/edit does not include IRC username
- Existing data in the database should also be removed

## Support for Chef Community Slack Username:

- Profile pages like this https://supermarket.chef.io/users/tas50 list a Chef Community Slack username
- Profile edit page https://supermarket.chef.io/profile/edit allows you to set a Chef Community Slack username

**Comment by RajeshPaul38** [comment]
I have a few questions @tas50 

- in slack there is user id instead of username e.g. it's **U0235EKCNKG** for me. Is this what is expected ?

- Another concern is, what should be the link for the slack user id/name. For me the link is: https://app.slack.com/client/T03GRS9QS/D023W4MQFRV/user_profile/U0235EKCNKG . But this can't be derived I believe.

**Comment by RajeshPaul38** [comment]
@tas50 can you help with the above query. It's blocked without having a clear idea on what is expected here. Please let us know..

**Comment by RajeshPaul38** [comment]
Subtasks

- [ ] Create migration to add column slack_username and remove irc_username

- [ ] Update the user form to add slack username and remove irc username field

- [ ] Display the value of slack username in user show page

**Comment by tas50** [comment]
I think for now we'll have to settle with just allowing the user to input their username. We'll probably want to see in the future if we can link out to Slack itself and connect the supermarket profile to the slack profile, but that's out the scope today.

**Comment by RajeshPaul38** [comment]
Ok, have implemented the same in the linked PR @tas50
