### ISSUE TITLE
Require TLS 1.2 or later

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2151]
We need to update the default TLS setup for supermarket to require TLS 1.2 or later by default.

Note: We will need to communicate this change to Ops so they can draft a plan to enable 1/1.1 via attributes and then turn it off later.

**Comment by RajeshPaul38** [comment]
Good document for the deprecation of TLS v1/1.1: https://www.digicert.com/blog/depreciating-tls-1-0-and-1-1

Going to support 1.2 and 1.3 as of now.

Here are the release timeline for the above 2 versions:

- TLS 1.2 – released in 2008.
- TLS 1.3 – released in 2018.

**Comment by tas50** [comment]
We don't actually support 1.3 since we're on Openssl 1.0.2 for FIPS compliance.

**Comment by RajeshPaul38** [comment]
Ok, will only keep only 1.2 as of now untill 1.3 is supported. Making the changes.
