### ISSUE TITLE
Links at bottom of Supermarket page are now dead

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2155]
### Chef Supermarket Version

The links at the bottom of the current builds are now dead. These were updated to point to the progress URLs, but now they're hitting incorrect chef.io URLs.

![image](https://user-images.githubusercontent.com/1015200/129804332-6fce2e80-9154-4f15-a122-c4408681806e.png)

The 3 on the right side are dead links now

**Comment by msys-sgarg** [comment]
Closing this issue since the
