### ISSUE TITLE
Audit telemetrics

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2159]
As a product owner, I would like to have a working telemetrics system, so that I can understand how supermarket is being used and make fixes if needed

- [ ] Does existing google analytics integration work

- [ ] Report on what events are captured

- [ ] Links to existing dashboards

**Comment by saghoshprogress** [comment]
@skkprogress Please let us know the google account for the supermarket google analytics.

**Comment by tas50** [comment]
Google analytics ships off by default
