### ISSUE TITLE
Reduce automatic email responses to cookbook update emails

### ISSUE THREAD

**Issue by btm** [chef/supermarket#2169]
Supermarket sends email updates to followers of a cookbook when it is updated. The [mysql cookbook](https://supermarket.chef.io/cookbooks/mysql) currently has 781 followers.

Most (all?) email auto-responders do not recognize this as an automated email and will respond to these, e.g. a vacation autoresponder in Outlook letting someone know when you'll be back. This creates a lot of noise for the cookbook maintainer.

There are various headers that can be added to outgoing emails to indicate they are automated notifications that will prevent auto-responders from replying to them. Unfortunately there isn't a single agreed upon header, but it is a common enough problem that identifying a couple headers to add should present an easy reduction in emails.

https://www.arp242.net/autoreply.html

I would consider adding these two headers to emails autogenerated by Supermarket:
```
Auto-Submitted: auto-generated
X-Auto-Response-Suppress: OOF
```

I looked at a recent cookbook update email that I received from the public Supermarket, and it contained these headers (most of these were added by intermediary email servers). I'm adding them for informational purposes only in case someone was curious of the same thing.

```
ARC-Authentication-Results:
ARC-Message-Signature:
ARC-Seal:
Authentication-Results:
Authentication-Results-Original:
Content-Type:
Date:
DKIM-Signature:
Feedback-ID:
From:
Message-ID:
Mime-Version:
Received:
Received-SPF:
Return-Path:
Subject:
To:
X-EOPAttributedMessage:
X-EOPTenantAttributedMessage:
X-Forefront-Antispam-Report:
X-MC-Unique:
X-Microsoft-Antispam:
X-Microsoft-Antispam-Mailbox-Delivery:
X-Microsoft-Antispam-Message-Info:
X-Mimecast-Spam-Score:
X-MS-Exchange-CrossTenant-AuthAs:
X-MS-Exchange-CrossTenant-AuthSource:
X-MS-Exchange-CrossTenant-FromEntityHeader:
X-MS-Exchange-CrossTenant-Id:
X-MS-Exchange-CrossTenant-Network-Message-Id:
X-MS-Exchange-CrossTenant-OriginalArrivalTime:
X-MS-Exchange-ForwardingLoop:
X-MS-Exchange-Organization-AuthAs:
X-MS-Exchange-Organization-AuthSource:
X-MS-Exchange-Organization-ExpirationInterval:
X-MS-Exchange-Organization-ExpirationIntervalReason:
X-MS-Exchange-Organization-ExpirationStartTime:
X-MS-Exchange-Organization-ExpirationStartTimeReason:
X-MS-Exchange-Organization-MessageDirectionality:
X-MS-Exchange-Organization-Network-Message-Id:
X-MS-Exchange-Organization-SCL:
X-MS-Exchange-Processed-By-BccFoldering:
X-MS-Exchange-Transport-CrossTenantHeadersStamped:
X-MS-Exchange-Transport-EndToEndLatency:
X-MS-Exchange-Transport-Forked:
X-MS-Office365-Filtering-Correlation-Id:
X-MS-Oob-TLC-OOBClassifiers:
X-MS-PublicTrafficType:
X-MS-TrafficTypeDiagnostic:
X-SES-Outgoing:
```

**Comment by tas50** [comment]
Shipped in 4.0
