### ISSUE TITLE
Move from Foodcritic for quality metrics to Cookstyle

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2181]
## Summary

```
As an operator
I want to see the most up-to-date quality evaluation of cookbooks on Supermarket
So that they will function as expected in my infrastructure
```

I order to give more useful insight into the quality of a cookbook we should move from the deprecated Foodcritic gem for quality metrics to Cookstyle.

## High Level Deliverable

Modernize the quality tab: https://supermarket.chef.io/cookbooks/transmission#quality

All references to Foodcritic are replaced with Cookstyle and when uploading a new cookbook it is scanned by Cookstyle with the results represented on the quality tab.

## Acceptance Criteria

- Foodcritic is no longer a dependency in Supermarket
- The 'Foodcritic Metric ' in the Quality cookbook tab is replaced with 'Cookstyle Metric'
- New cookbooks are scanned with Cookstyle
- The scans are limited to the `Chef/Deprecations, `Chef/Correctness`, `Chef/Sharing`, `Chef/RedundantCode`, and `Chef/Modernize` departments
- The output shows the version of cookstyle used and the departments scanned with similar to the output in the current Foodcritic scans
- Migrate existing cookbooks to new quality metric

## Outside the scope of this issue

- Breaking out departments into their own quality metrics
- Changing the weight of the metric
- Storing the output in JSON directly in the DB
- Exposing this data in new ways in the API

For now this is just a 1:1 replacement of the Foodcritic functionality.

**Comment by saghoshprogress** [comment]
Steps: 

[] Installation

[] Change all the food-critic logic. 

[] Change all the specs.

[] UI change Food-critic Metric to cook-style.

[] Modify the quality metrics task for re-evaluation.

[] Remove all the Food-critic references.

-- 
Testing
[] Load prod data and check the difference and adjust accordingly if required.
