### ISSUE TITLE
Update cookbook details page supported platforms text

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2187]
The cookbook pages (ex https://supermarket.chef.io/cookbooks/mysql) have a heading "Platforms" which should be "Supported Platforms".

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1015200/130695532-cea44b0c-fe68-44e1-b3e8-aa54b346ff9f.png">

**Comment by RajeshPaul38** [comment]
Here is the SS of the changed text.
![Screenshot 2021-09-15 at 2.49.12 PM.png](https://images.zenhubusercontent.com/60b7868792ea6cd3231262be/502126b9-abc3-4395-8125-43438e79a6b1)

**Comment by dheerajd-msys** [comment]
Closing in support of https://github.com/chef/supermarket/pull/2231
