### ISSUE TITLE
Allow adding a reason to cookbooks when deprecated

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2193]
Right now when you deprecate a cookbook you either provide a replacement cookbook or nothing. We need to be able to provide a reason that we can then display in the deprecation warning. We'd use this for our cookbooks when we deprecate them because the tech is dated or the functionality is built in

### Update the deprecation dialog

![image](https://user-images.githubusercontent.com/1015200/131046732-571a38ec-c64d-4bad-871a-180f1e9cfdde.png)

1. Between the two sentences currently there add a "Deprecation Reason" field.
2. Move the deprecate button to its own at the bottom instead of being part of the pull-down

### Add the ability to update deprecation reasons

In the current manage cookbook pull down:

![image](https://user-images.githubusercontent.com/1015200/131046732-571a38ec-c64d-4bad-871a-180f1e9cfdde.png)

1. Add an "Update Deprecation Reason" option that loads the current text and lets you update it.

### Update deprecation text

Update the cookbook page text displayed with the deprecation:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/1015200/131047024-b1cb736b-dc0e-41cc-8cb4-97eabae97574.png">

1. Add "Author provided reason for deprecation: NEWLINE THEN REASON"

### Update e-mails

![image](https://user-images.githubusercontent.com/1015200/131047279-70387c65-7de9-4ad0-a870-efeafc1840dc.png)

1. Add "Author provided reason for deprecation: NEWLINE THEN REASON"

**Comment by sanga1794** [comment]
closing https://github.com/chef/supermarket/issues/2193 via https://github.com/chef/supermarket/pull/2359.
