### ISSUE TITLE
Release Supermarket 4.x

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2206]
We have a HUGE amount of new functionality and fixes in supermarket main branch right now that we need to ship to customers:

https://github.com/chef/supermarket/wiki/Pending-Release-Notes

Let's get this out the door, but first we need to validate the builds function as expected:

- [x]  Installs work and Supermarket is functional post install

- [x] Upgrades from 3.4.8 -> 4.x work and Supermarket is functional post upgrade 

- [x] Users can login using Infra Server users and view their profile

- [x] Cookbooks can be uploaded via knife

- [x] Cookbooks can be downloaded via `chef install` command from a Policyfile

- [x] Quality metrics are run on all uploaded cookbooks

If there's any other potential validation steps let's get them added here or in a dev doc.

**Comment by RajeshPaul38** [comment]
testing 4.0.14

**Comment by RajeshPaul38** [comment]
**Testing on ubuntu 20.04.2 LTS**

- Successfully built supermarket with omnibus

- Successfully installed supermarket package

- Successfully reconfigured supermarket

- I'm able to see the supermarket homepage in the ec2 instance IP: https://3.138.182.189/

**Comment by tas50** [comment]
Let's take this as an opportunity to come up with a testing doc, which can later be turned into an automated process within Umbrella. There may be something already within the /docs directory or the wiki, but if not we should create a doc for validating the builds prior to release.

**Comment by RajeshPaul38** [comment]
Was facing some challenge connecting supermarket with oc-id due to the public IP not being used as FQDN.

Initially the fqdn was the private DNS which was: **ip-172-31-25-225.us-east-2.compute.internal**

I had to set the hostname to the public IP address which was: 3.138.182.189
The command used is as follows:
```
sudo hostnamectl set-hostname 3.138.182.189
```

Had to set the same IP in the redirect url in chef server oc-id applications as follows:
```
"redirect_uri": "https://3.138.182.189/auth/chef_oauth2/callback"
```

Now it's able to authorize supermarket with oc-id. But the only issue remains is that it's saying the certificate in supermarket is self signed and hence not setting the authorization token in cookie. Will check what can be done.

**Comment by RajeshPaul38** [comment]
> Let's take this as an opportunity to come up with a testing doc, which can later be turned into an automated process within Umbrella. There may be something already within the /docs directory or the wiki, but if not we should create a doc for validating the builds prior to release.

sure @tas50 . I'm sharing all the steps I'm following to resolve any issues. Will convert it to a doc once the complete process is successful.

**Comment by RajeshPaul38** [comment]
Now as the self signed certificate issue is resolved we move to the next step.

- We need to install chef-client in our supermarket server to connect to chef-server as per the following instructions:

  - Get the <user>.pem and <org-validator>.pem file from your chef server into supermarket server through scp command. You will mostly find these 2 pemfiles in the /tmp directory in the chef-server host.
  - To install chef client in supermarket instance do the following:
    - ssh into the supermarket ec2 instance.
    - ```wget https://packages.chef.io/files/stable/chef-workstation/20.6.62/debian/10/chef-workstation_20.6.62-1_amd64.deb```
    - ```sudo dpkg -i chef-workstation*.deb```
  - Now create a chef repository in the home directory (e.g. `/home/ubuntu`) your supermarket instance as follows:
    - `chef generate repo chef-repo`
    - This will create a chef repository where you can generate your cookbooks that you want to push into chef server
    - For pushing any cookbook you need to first authorize your chef client with chef server with the previously copied <user>.pem and <org-validator>.pem
  - Inside the chef repo you need to configure your chef server credentials as follows:
    - Create a directory .chef inside the chef-repo.
    - Copy the `<user>.pem` and `<org-validator>.pem` to the `.chef` directory. Need to mention these 2 pemfiles in the following step.
    - Create a new file inside chef-repo with: ```vim .chef/config.rb``` and add the following content and replace the placeholders ( e.g. `<placeholder>`): 

    ```
    current_dir = File.dirname(__FILE__)
    log_level                :info
    log_location             STDOUT
    node_name                '<chef-server username>'
    client_key               "<chef-server username>.pem"
    validation_client_name   '<chef-server organization name>-validator'
    validation_key           "<chef-server organization name>-validator.pem"
    chef_server_url          'https://<chef-server IP>/organizations/ORGNAME'
    cache_type               'BasicFile'
    cache_options( :path => "#{ENV['HOME']}/.chef/checksums" )
    cookbook_path            ["#{current_dir}/../cookbooks"]
    ```
    - Now your chef client is configured to connect to the chef server.
    - Next step is to download the certificate of supermarket server in to the supermarket instance. This will make sure when you use supermarket API it doesn't throw an error saying that it's a self signed certificate. Downloading the certificate into trusted certificates will bypass this error of self signed certificate. Run the following command:
      - `knife ssl fetch https://<supermarket server public IP address>`
      - You can notice that inside the `.chef` directory the certificate has been downloaded in the `trusted_certs` directory in the name of the `<supermarket server IP address>.crt`
    - Now the setup is complete to do 2 things i.e. validating supermarket server certificate and being able to connect to the chef-server. You shold now be able to push cookbooks to chef-server using supermarket service API as follows:
    - Inside the chef-repo go to the `cookbooks` directory.
    - Run `chef generate cookbook <cookbook-name>`. This will generate a cookbook directory as per the name given in the command.
    - To push the generated cookbook run the following command:
      - `knife supermarket share <cookbook-name> -m https://<supermarket server IP> -o ~/chef-repo/cookbooks/ -V`
      - If the above command succeeds then that means that your cookbook is pushed through supermarket to the chef-server
    - To verify whether the cookbook is pushed you can go to your supermarket url in your browser and then go to manage profile and you should be able to see the cookbook listed in that page. Here is the url to reach this page: `https://<supermarket IP>/users/<chef-server username>`.

**Comment by RajeshPaul38** [comment]
### Cookbook Download
Able to download the cookbook archive with the following command:
`knife supermarket download <cookbook_name> -m https://<supermarket IP>`

**Comment by RajeshPaul38** [comment]
### Cookbook Install
I was able to install a cookbook from chef server using the command from supermarket instance:
`knife supermarket download <cookbook_name> -m https://<supermarket IP>`

To validate whether the installation is working fine or not I first deleted the specific cookbook from my chef repo where from I pushed the cookbook. Then after installing the same cookbook from chef server the same cookbook was put back into the cookbooks directory inside my chef-repo.

**Comment by RajeshPaul38** [comment]
### Cookbook Unshare/Delete

I was able to unshare/delete a shared cookbook from chef server using the command:
`knife supermarket unshare <cookbook_name> -m https://<supermarket IP>`

**Comment by RajeshPaul38** [comment]
So all the checkpoints have passed. Pls let me know the next step. @tas50

**Comment by tas50** [comment]
Thanks for taking this on. Let's get these steps documented so we can automate this in the umbrella pipeline in the future.

**Comment by RajeshPaul38** [comment]
Sure @tas50 . WIll be preparing the dev-doc and will raise a PR.
