### ISSUE TITLE
Update 4.0 based changes in the docs

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2207]
Check the release notes at https://github.com/chef/supermarket/wiki/Pending-Release-Notes and determine what items here require updates to the chef-web-docs repo

**Comment by msys-sgarg** [comment]
#Updated Omniauth version to 2.0
https://github.com/chef/supermarket/issues/1903

#View cookbookbooks in sorted order by deprecated flag
https://github.com/chef/supermarket/issues/1838

#All the icla/ccla configurations are removed
https://github.com/chef/supermarket/issues/2152

**Comment by RajeshPaul38** [comment]
**Fixed insecure redirections**
**Changed cookie serializer from :hybrid to :json as hybrid serializer has security issues**
https://github.com/chef/supermarket/issues/2016

**Hide nginx server header from API response for supermarket**
https://github.com/chef/supermarket/issues/1978

**Added slack username and removed irc nickname from user profile**
https://github.com/chef/supermarket/issues/2150

**Automated DB migration step in test env in github pipeline**
https://github.com/chef/supermarket/issues/2173

**CONTRIBUTION.md filename check made case insensitive for cookbook quality metric**
**Corrected github URL pattern REGEX to filter out non-github URLs**
https://github.com/chef/supermarket/issues/1837

**Comment by dheerajd-msys** [comment]
Updated Redis to 6.2.5
https://github.com/chef/supermarket/issues/1952

Supermarket packages are now produced for SLES 12 and 15
https://github.com/chef/supermarket/issues/1957

Ubuntu FIPS Support
https://github.com/chef/supermarket/issues/1956

Remove provisioning driver from tools directory
https://github.com/chef/supermarket/issues/1968

Updates nginx to 1.20.1
https://github.com/chef/supermarket/issues/1953

Delete the incomplete habitat plan
https://github.com/chef/supermarket/issues/1961

**Comment by saghoshprogress** [comment]
1) Update the ruby version from 2.6 to 2.7.4 and rails version from 5 to 6.1.2
https://github.com/chef/supermarket/pull/2078

**Comment by tas50** [comment]
I think most of these changes won't trigger necessary changes don't the docs site. Mostly we just need to review what docs are there and see if there's anywhere changes are necessary. Text updates, platform updates, or screenshot updates.
