### ISSUE TITLE
Handle no supported platforms in cookbook view better

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2250]
If no supported platforms are set we currently show a question mark icon with a hover-over.  We should just show the text "None specified" if nothing is specified.

![Screen Shot 2021-09-24 at 7 32 23 AM](https://user-images.githubusercontent.com/1015200/134693962-bd945f33-b7af-4880-9b10-dcd2715b48f3.png)

**Comment by sanga1794** [comment]
closing https://github.com/chef/supermarket/issues/2250 via https://github.com/chef/supermarket/pull/2359.
