### ISSUE TITLE
Make the default install tab  in the cookbook page Policyfile

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2252]
Right now we show the Berkshelf tab by default. We want to push people to Policyfiles and to help out there it should be the default tab. Policyfiles should be the first tab

![image](https://user-images.githubusercontent.com/1015200/134696615-35735bd7-9089-42af-9217-74d65c92df44.png)

**Comment by dheerajd-msys** [comment]
Closing in favour of #2335
