### ISSUE TITLE
Add banner about maintenance window

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2292]
The supermarket is set to be migrated into a newer server on Nov 9th. We need to turn on the banner on supermarket website to announce this and warn for potential downtime. Content:

> PSA: We are upgrading the infrastructure that Supermarket runs on and make it greater at serving your needs. Kindly expect a downtime on Nov 9th 2021 when we shift things around. You can keep tab on the [status here](https://status.chef.io/)

**Comment by msys-sgarg** [comment]
I think we can close this issue since the banner changes are merged
