### ISSUE TITLE
Investigate setting Permissions-Policy HTTP headers

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2298]
Investigate setting Permissions-Policy in Supermarket. This is possible in Rails 6.1, but it may need to be done in Nginx. We should probably disable camera and payment to start since those are 100% not used by Supermarket.

https://blog.saeloun.com/2019/10/01/rails-6-1-adds-http-feature-policy.html

**Comment by RajeshPaul38** [comment]
similar requirement in this PR: https://github.com/chef/chef-manage/pull/1227
