### ISSUE TITLE
Testing on new servers

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2339]
**Context: ** Supermarket.chef.io is being pushed into a new server on Dec 1. All existing services are expected to work as is and this is intended to be a lift and shift. 
**Acceptance criteria: ** Perform tests on UAT environment https://supermarket-staging2.chef.io/ and ensure to compile a list of issues caught

**Comment by saghoshprogress** [comment]
We will pick this one before the release

**Comment by pratixha** [comment]
Releasing Supermarket v4.1.28 is on URL https://supermarket2.chef.io which i'm testing currently.

**Comment by pratixha** [comment]
### Commands :- on https://supermarket.chef.io and https://supermarket2.chef.io 
knife supermarket install cookbook
 knife supermarket download cookbook 
knife supermarket unshare cookbook/versions/0.1.0 -m https://supermarket.chef.io 
knife supermarket share cookbook -m https://supermarket.chef.io 
knife ssl fetch https://supermarket.chef.io/ 
knife supermarket download cookbook_name -m https://supermarket2.chef.io
### bugs and enhancements via versions :- 
https://docs.chef.io/release_notes_supermarket/?v=4.2.89 
https://docs.chef.io/release_notes_supermarket/?v=4.2.82 
https://docs.chef.io/release_notes_supermarket/?v=4.1.28
https://docs.chef.io/release_notes_supermarket/?v=4.0.21
