### ISSUE TITLE
Merge dependabot PRs

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2358]
@RajeshPaul38 commented on [Tue Nov 09 2021](https://github.com/chef/chef/issues/12262)

Merge dependabot PRs:
https://github.com/chef/supermarket/pull/2346/commits
https://github.com/chef/supermarket/pull/2345/commits
https://github.com/chef/supermarket/pull/2344/commits
https://github.com/chef/supermarket/pull/2343/commits
https://github.com/chef/supermarket/pull/2319/commits
https://github.com/chef/supermarket/pull/1935/commits

**Comment by dheerajd-msys** [comment]
@tas50 above PRs are merged and closed

**Comment by dheerajd-msys** [comment]
Closing as this is not required
