### ISSUE TITLE
omnibus installer contains build-id files in RPM on CentOS8/RHEL8

### ISSUE THREAD

**Issue by haidangwa** [chef/supermarket#2450]
### Chef Supermarket Version

[What version of Chef Supermarket? Any plugins? Are you using Chef Server? What versions?]
4.0.21 and 4.1.28

### Platform Details

[Operating system distribution and release version. Cloud provider and instance type if running in the cloud. Total/Free RAM and disk space. Is this running in a container?]
CentOS 8 and RHEL8

### Configuration

[Private OR Hosted Supermarket, Provide details of changes from the default]
Private Supermarket installed via omnibus RPM; also using `chef_supermarket` resource from the chef-ingredient cookbook.

### Scenario

[What you are trying to achieve and you can't?]
I ran into this today trying to install Supermarket 4.1.28 and 4.0.21 onto a RHEL 8 Test Kitchen instance. Supermarket
3.4.8, however, doesn't exhibit this problem.

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of supermarket-4.1.28-1.el8.x86_64 conflicts with file from package chef-16.17.18-1.el8.x86_64
```

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of supermarket-4.0.21-1.el8.x86_64 conflicts with file from package chef-16.17.18-1.el8.x86_64
```

It also doesn't matter if I'm using Chef Infra Client 15, 16, or 17. They all fail similarly.

### Steps to Reproduce

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
In a recipe, use the `chef_supermarket` resource from the chef-ingredient cookbook to install Supermarket 4.0.21 or 4.1.28 on CentOS 8 or RHEL8 RPM.

### Expected Result

[What are you expecting to happen as the consequence of above reproduction steps?]
These 4.x versions should install on Centos 8 / RHEL8, but they fail

### Actual Result

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of supermarket-4.1.28-1.el8.x86_64 conflicts with file from package chef-16.17.18-1.el8.x86_64
```

```
Error: Transaction test error:
  file /usr/lib/.build-id/ff/ed13d7b76a61d3dbc3744d5f4557d1dfca2ed3 from install of supermarket-4.0.21-1.el8.x86_64 conflicts with file from package chef-16.17.18-1.el8.x86_64
```

Might be related to https://github.com/chef/omnibus/issues/933

**Comment by tas50** [comment]
We've fixed this on main and it'll go out with Supermarket 4.2
