### ISSUE TITLE
Cookbook recommendations

### ISSUE THREAD

**Issue by sethvargo** [chef/supermarket#247]
Migrated from: https://projects.invisionapp.com/share/VMOMTJ36#/screens/16758975/comments/10359085

Is there interest/benefit in having cookbooks recommendations based off of the currently-view cookbook (like Amazon or Google recommendations).

**Comment by nellshamrell** [comment]
Thanks again, @sethvargo!  We are not currently working on this, but will keep it in mind, it would work especially well with Community Cookbook Quality Metrics.  We will be working on the Quality Metrics feature next quarter :)
