### ISSUE TITLE
Dex integration

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2491]
**Context: **
Dex is an identity service that uses OpenID Connect to drive authentication for other apps. 
Dex acts as a portal to other identity providers through “connectors.” This lets Dex defer authentication to LDAP servers, SAML providers, or established identity providers like GitHub, Google, and Active Directory.

**Acceptance criteria:**
Supermarket app should integrate with Dex to login using Automate's login

**Comment by dheerajd-msys** [comment]
OpenIDConnect Reference : https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

**Comment by dheerajd-msys** [comment]
Reference :  https://dexidp.io/docs/getting-started/#building-the-dex-binary
