### ISSUE TITLE
Archlinux AUR as a model of a good community.

### ISSUE THREAD

**Issue by miah** [chef/supermarket#32]
Archlinux (teh best linux ;) has a community repository for user packages. Its very similar in concept to the Chef Community site. [Here's an example for a piece of software we're all used before.](https://aur.archlinux.org/packages/chef/)

So, take a look at those features

 - description
 - upstream url
 - category
 - license
 - original submitter
 - current maintainer
 - votes
 - creation time
 - modification time
 - complete list of external dependencies
 - a list to show which external packages require this package
 - original sources url

Pretty much everything you need to know about a package.

Additionally as a non-authenticated user, you can:

 - download a tarball of the raw package
 - view the raw metadata

If you authenticate, you get more available actions:

 - flag package as out of date
 - vote for package
 - subscribe to  new comments

Take a look at the [User Guidelines](https://wiki.archlinux.org/index.php/AUR_User_Guidelines), and the [Trusted User Guidelines](https://wiki.archlinux.org/index.php/AUR_Trusted_User_Guidelines). The difference between the two is that trusted users get more privilege in the community and have the ability to move things around.

The 'flag package as out of date' is the important thing here. A user may stop maintaining a package for any number of reasons. We don't want that package to name-squat and force users to fork and resubmit under a new name. So, users can flag the package as out of date. The maintainer of the package is notified and if after some time does not take action you can then mail a list and get TU's to take action.

So, now that I've duplicated some amount of the AUR docs, I urge you to go read them. I think it could work out as a great model for the new community site. The AUR docs are available under the [GNU FDL](https://www.gnu.org/copyleft/fdl.html).

:see_no_evil: :hear_no_evil: :speak_no_evil:

**Comment by nellshamrell** [comment]
Thanks again so much, @miah!  Many of these items have been considered and implemented.  I'm going to close this issue for now, but if you have more suggestions or things you want to see please let us know!
