### ISSUE TITLE
Allow the /universe API endpoint to be filtered

### ISSUE THREAD

**Issue by raskchanky** [chef/supermarket#504]
Modify the `/universe` API endpoint to accept cookbook names as parameters and return information for only those cookbooks.

See the comment from @danielsdeleo here https://github.com/opscode/supermarket/issues/33#issuecomment-43687500 for more details.

**Comment by nellshamrell** [comment]
Thank you for the great discussion everyone!  We are not going to implement this at this time, but will keep it in mind if the request comes up again.
