### ISSUE TITLE
Request: Autocomplete with metadata view

### ISSUE THREAD

**Issue by perplexes** [chef/supermarket#517]
Autocomplete is a really great instant feedback to what you're typing and also aids in discovery by helping you modify your search terms to things that look interesting. There have been many times where I've started typing into Chrome's "searchcation" (or is it "lerch") bar and it recommended some more terms to drop on my query like "scandal".

It'd be great in this autocomplete view to see the number of downloads and to weight by relevancy/popularity.

**Comment by nellshamrell** [comment]
We have added a drop down with search suggestions on the cookbook/tool bar.  Going to close this.
