### ISSUE TITLE
Cannot authenticate locally

### ISSUE THREAD

**Issue by sethvargo** [chef/supermarket#550]
I'm running a local instance of supermarket and I got:

![screen shot 2014-07-07 at 12 53 56 am](https://cloud.githubusercontent.com/assets/408570/3491483/d7a93f4e-0592-11e4-8245-d3ee58460137.png)

How does one run in local development? Is there a way to bypass oauth for local purposes? Otherwise, I'm not sure how I can register my local application with oc-id.

The linked URL (https://id.opscode.com/id/oauth/applications/) on the configuring wiki page also shows me a 404.

**Comment by miketheman** [comment]
For reference, I hit this today when trying to work on supermarket locally. The CONFIGURING.md file still tells me what to set up, and how to create keys, etc.
None of that worked, got the same error message from the Real ID service.

While the addition of a configurable CHEF_OAUTH2_URL exists, there's no clear method for setting up a local oc-id service, or how to "get going" as it were.

Any ideas, knowledge would be helpful.

**Comment by smith** [comment]
@miketheman as of Enterprise Chef 11.2 and Chef server 12, oc-id is included with Chef server, so to run your own oc-id service you just need to be running your own Chef server.

CONFIGURING.md doesn't make this clear at all and should be fixed.
