### ISSUE TITLE
team support for managing cookbooks

### ISSUE THREAD

**Issue by prometheanfire** [chef/supermarket#658]
I'd like to see teams able to be created and managed.

This will help us manage the users on more then one cookbook at a time (we plan on managing a few cookbooks) as people move around.

This would be for ongoing cookbook user management, just just a one time thing.

**Comment by nellshamrell** [comment]
This is now on the Supermarket Q3 roadmap

**Comment by nellshamrell** [comment]
The pull request for this feature is complete and is now being reviewed:
https://github.com/chef/supermarket/pull/1151

**Comment by nellshamrell** [comment]
This was released in Supermarket v.2.2.1

See this blog post for instructions/information:

https://www.chef.io/blog/2015/12/18/collaborator-groups-on-supermarket/

**Comment by jeffbyrnes** [comment]
Came across this long after it was released for private Supermarket; was it ever enabled for the public one? Seems like not, from what I can tell.

**Comment by robbkidd** [comment]
It is not enabled for the public Supermarket.
