### ISSUE TITLE
Supermarket Mirror

### ISSUE THREAD

**Issue by cwebberOps** [chef/supermarket#775]
I have heard a lot about supermarket mirrors in various forms. The problem is, I am not sure what that would look like. We should figure out what people want out of a mirror and start making that a thing.

**Comment by nathenharvey** [comment]
It might be best to start by leveraging the existing infrastructure to handle the synchronization.  "Follow" each cookbook that you're interested in mirroring from supermarket.chef.io.  When there are updates kick off a script that downloads the updated cookbook and uploads it to your own Supermarket.

It would be a bit of a hack but would also allow you to validate the efficacy of the idea.

**Comment by jzohrab** [comment]
We're considering creating an internal supermarket, which will be composed of a fully private supermarket and a mirror of the public supermarket.

Private supermarket: our own internal work, never to be published
Public supermarket: as-is full mirror to give devs access to all things in the community (good and bad) while getting around proxy issues as described by @berniedurfee.

There are a few reasons for the separation:
* private cookbooks may accidentally have same name as a new public cookbook (may be what @echohack means when referring to namespacing)
* ppl may want things from public supermarket, but we'd like to have a sharp contrast between our private work and community work
* we can apply a pipeline/quality gate to our private supermarket, but leave the public one as-is

@echohack solution 1+3 would suffice for this setup.

**Comment by berniedurfee-ge** [comment]
@jzohrab We've since built a Cookbook repo tool (with mirroring), which we're using internally for custom cookbooks as well as mirroring cookbooks. Sort of a Supermarket Lite, hence the name...

https://electric-it.github.io/minimart/

**Comment by nellshamrell** [comment]
For the time being, you should use https://electric-it.github.io/minimart/ as a Cookbook mirroring tool, though we will revisit this in the future.  Thanks for the input, all!
