### ISSUE TITLE
Add links to chef and chef-dev mail lists under Resources

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/supermarket#807]
"Join the Mailing List" shouldn't point to the chef-supermarket google group. It should point to the chef mailing list and maybe even the chef-dev mailing list.

http://lists.opscode.com/sympa/info/chef

http://lists.opscode.com/sympa/info/chef-dev

**Comment by nellshamrell** [comment]
Thanks so much!  We're going to leave it pointing the the chef-supermarket google group for the time being.
