### ISSUE TITLE
Move the content for the Resource "Getting Started with Chef and Cookbooks" somewhere else

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/supermarket#809]
That content needs to be moved out of the old wiki probably to the docs site and the link in Supermarket updated.

https://wiki.opscode.com/display/ChefCN/Creating+New+Cookbooks

**Comment by cmluciano** [comment]
Is this still an issue? I see a "share your cookbooks" link now but it actually points to the command to share.

**Comment by smith** [comment]
This was fixed in #970. Thanks for the reminder!
