### ISSUE TITLE
Github Markdown Style for Readme?

### ISSUE THREAD

**Issue by rmoriz** [chef/supermarket#819]
Hi,

follow-up of https://twitter.com/cwebber/status/515505527720120320

How about using the CSS that github uses to display README.MD in supermarket?

e.g.

https://supermarket.getchef.com/cookbooks/jenkins
vs.
https://github.com/opscode-cookbooks/jenkins#jenkins-cookbook

I prefer the GitHub-style - maybe because I'm used too but I think the readability is higher (and it has syntax highlighting)

**Comment by nellshamrell** [comment]
Thanks for the suggestion!  We are not going to move forward with this for now, but thank you again!
