### ISSUE TITLE
search tags

### ISSUE THREAD

**Issue by rbowlby** [chef/supermarket#822]
A search term of sshd does not currently return the openssh cookbook that's widely used. Instead it returns the sshd cookbook as the first result.

Perhaps tags/keywords within the supermarket would allow the openssh cookbook to rightfully be listed in the results. Just a suggestion so as to not have noobs accidentally using less than standard cookbooks where better ones may exist.

**Comment by nellshamrell** [comment]
Hi @rbowlby - thanks so much for this suggestion!  We are addressing this in Q1 with the Quality Metrics feature for cookbooks on Supermarket, so I'm going to go ahead and close this out.
