### ISSUE TITLE
Supermarket Branding (Behind the Firewall / Good Defaults)

### ISSUE THREAD

**Issue by echohack** [chef/supermarket#830]
When you create a Supermarket server, by default, it is covered with the same branding, coloring, and style as the public Supermarket. This isn't an ideal situation for deploying your own Supermarket server internally because it's massively confusing to users. Users "behind the firewall" want to be assured that they are on their own private Supermarket, and not the public Supermarket.

In addition, many large enterprises have IP constraints where they *have* to put their own branding on the UI of their internal servers.

This issue covers the following:

1. Good defaults for branding when deploying Supermarket out of the box, that are different from the public Supermarket.
2. Create the ability so that you can provide branding for your own private Supermarket.
3. Abstract out the public Supermarket branding so it can be applied in the same way that a private Supermarket would apply their branding. (This way we eat our own dogfood for the public site).

**Comment by jzohrab** [comment]
A first shot at this: https://github.com/chef/supermarket/pull/1111.  Feedback welcome.

**Comment by nellshamrell** [comment]
#1111 was indeed merged, so I'm going to close this.  Thanks!
