### ISSUE TITLE
Error when performing a cookbook search

### ISSUE THREAD

**Issue by tfitch** [chef/supermarket#861]
My customer with a private install of Supermarket noticed this error when trying to do a search of their Supermarket install.

The version they're running is from the commit sha: 4c1250aa1217e5bb9009d0853b86251d173d8338

I didn't see any commit messages since that checkin that appeared to be search related, so I'm suspecting the issue still exists.
## Info from customer is as follows.

Getting a supermarket exception when performing a cookbook search.

E, [2014-10-01T17:06:47.224885 #1483] ERROR -- : PG::UndefinedFunction: ERROR: operator does not exist: text % unknown 
LINE 1: ...'))) OR ((coalesce("cookbooks"."name"::text, '')) % 'tcserve... 
^ 
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. 
: SELECT COUNT(count_column) FROM (SELECT 1 AS count_column FROM "cookbooks" LEFT OUTER JOIN (SELECT "cookbooks"."id" AS id, string_agg("accounts"."username"::text, ' ') AS pg_search_890324e94e76623fc009c7 FROM "cookbooks" INNER JOIN "users" ON "users"."id" = "cookbooks"."user_id" INNER JOIN "accounts" ON "accounts"."user_id" = "users"."id" AND "accounts"."provider" = 'chef_oauth2' GROUP BY "cookbooks"."id") pg_search_7594026fb1aac53c17f9d1 ON pg_search_7594026fb1aac53c17f9d1.id (http://pg_search_7594026fb1aac53c17f9d1.id/) = "cookbooks"."id" LEFT OUTER JOIN (SELECT "cookbooks"."id" AS id, string_agg("cookbook_versions"."description"::text, ' ') AS pg_search_81e075c5b33729084863f3 FROM "cookbooks" INNER JOIN "cookbook_versions" ON "cookbook_versions"."cookbook_id" = "cookbooks"."id" GROUP BY "cookbooks"."id") pg_search_3ef819e0b0185d9b7c77b6 ON pg_search_3ef819e0b0185d9b7c77b6.id (http://pg_search_3ef819e0b0185d9b7c77b6.id/) = "cookbooks"."id" WHERE (((setweight(to_tsvector('english', coalesce(pg_search_7594026fb1aac53c17f9d1.pg_search_890324e94e76623fc009c7::text, '')), 'B') || setweight(to_tsvector('english', coalesce(pg_search_3ef819e0b0185d9b7c77b6.pg_search_81e075c5b33729084863f3::text, '')), 'C')) @@ (to_tsquery('english', ''' ' || 'tcserver' || ' ''' || ':_'))) OR ((coalesce("cookbooks"."name"::text, '')) % 'tcserver')) LIMIT 10 OFFSET 0) subquery_for_count 
E, [2014-10-01T17:06:47.517949 #1483] ERROR -- : *_ [Raven] Unable to record event with remote Sentry server (Raven::Error - Unknown transport scheme '') 
E, [2014-10-01T17:06:47.518246 #1483] ERROR -- : *\* [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/client.rb:77:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/client.rb:77:in) `transport' 
E, [2014-10-01T17:06:47.518337 #1483] ERROR -- : ** [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/client.rb:36:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/client.rb:36:in)`send' 
E, [2014-10-01T17:06:47.518423 #1483] ERROR -- : *\* [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:69:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:69:in) `send' 
E, [2014-10-01T17:06:47.518509 #1483] ERROR -- : ** [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:107:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:107:in)`block in capture_exception' 
E, [2014-10-01T17:06:47.518586 #1483] ERROR -- : *\* [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:128:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:128:in) `send_or_skip' 
E, [2014-10-01T17:06:47.518654 #1483] ERROR -- : ** [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:101:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/base.rb:101:in)`capture_exception' 
E, [2014-10-01T17:06:47.518723 #1483] ERROR -- : *\* [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/rack.rb:22:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/rack.rb:22:in) `capture_exception' 
E, [2014-10-01T17:06:47.518793 #1483] ERROR -- : ** [Raven] /srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/rails/middleware/debug_exceptions_catcher.rb:10:in (http://srv/supermarket/shared/bundle/ruby/gems/sentry-raven-0.8.0/lib/raven/rails/middleware/debug_exceptions_catcher.rb:10:in)`render_exception_with_raven' 
E, [2014-10-01T17:06:47.518860 #1483] ERROR -- : *\* [Raven] /srv/supermarket/shared/bundle/ruby/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:27:in (http://srv/supermarket/shared/bundle/ruby/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:27:in) `rescue in call' 
E, [2014-10-01T17:06:47.518933 #1483] ERROR -- : ** [Raven] /srv/supermarket/shared/bundle/ruby/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in (http://srv/supermarket/shared/bundle/ruby/gems/actionpack-4.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in)`call' 
E, [2014-10-01T17:06:47.519005 #1483] ERROR -- : *\* [Raven] /srv/supermarket/shared/bundle/ruby/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in (http://srv/supermarket/shared/bundle/ruby/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in) `call' 
F, [2014-10-01T17:06:47.523747 #1483] FATAL -- : 
ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR: operator does not exist: text % unknown 
LINE 1: ...'))) OR ((coalesce("cookbooks"."name"::text, '')) % 'tcserve... 
^ 
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. 
: SELECT COUNT(count_column) FROM (SELECT 1 AS count_column FROM "cookbooks" LEFT OUTER JOIN (SELECT "cookbooks"."id" AS id, string_agg("accounts"."username"::text, ' ') AS pg_search_890324e94e76623fc009c7 FROM "cookbooks" INNER JOIN "users" ON "users"."id" = "cookbooks"."user_id" INNER JOIN "accounts" ON "accounts"."user_id" = "users"."id" AND "accounts"."provider" = 'chef_oauth2' GROUP BY "cookbooks"."id") pg_search_7594026fb1aac53c17f9d1 ON pg_search_7594026fb1aac53c17f9d1.id (http://pg_search_7594026fb1aac53c17f9d1.id/) = "cookbooks"."id" LEFT OUTER JOIN (SELECT "cookbooks"."id" AS id, string_agg("cookbook_versions"."description"::text, ' ') AS pg_search_81e075c5b33729084863f3 FROM "cookbooks" INNER JOIN "cookbook_versions" ON "cookbook_versions"."cookbook_id" = "cookbooks"."id" GROUP BY "cookbooks"."id") pg_search_3ef819e0b0185d9b7c77b6 ON pg_search_3ef819e0b0185d9b7c77b6.id (http://pg_search_3ef819e0b0185d9b7c77b6.id/) = "cookbooks"."id" WHERE (((setweight(to_tsvector('english', coalesce(pg_search_7594026fb1aac53c17f9d1.pg_search_890324e94e76623fc009c7::text, '')), 'B') || setweight(to_tsvector('english', coalesce(pg_search_3ef819e0b0185d9b7c77b6.pg_search_81e075c5b33729084863f3::text, '')), 'C')) @@ (to_tsquery('english', ''' ' || 'tcserver' || ' ''' || ':*'))) OR ((coalesce("cookbooks"."name"::text, '')) % 'tcserver')) LIMIT 10 OFFSET 0) subquery_for_count): 
app/controllers/api/v1/cookbooks_controller.rb:75:in (http://app/controllers/api/v1/cookbooks_controller.rb:75:in)`search'

**Comment by iroller** [comment]
I just fixed the same issue in my setup. I installed supermarket using the latest version of community cookbook.

Here's what it shows after chef-run run for supermarket database:
```
postgres@sm-01:~$ echo '\dx' | psql supermarket_production
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
```

And here's the global output:
```
postgres@sm-01:~$ echo '\dx' | psql
                                    List of installed extensions
  Name   | Version |   Schema   |                            Description
---------+---------+------------+-------------------------------------------------------------------
 pg_trgm | 1.1     | public     | text similarity measurement and index searching based on trigrams
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```


So community cookbooks installs the extension but doesn't make it available for supermarket db.
Tto fix the issue I had to run the following command:
```
postgres@sm-01:~$ psql supermarket_production -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm'
CREATE EXTENSION
```

Now posgres extension is available for supermarket database and the issue with the search is gone:
```
postgres@sm-01:~$ echo '\dx' | psql
                                    List of installed extensions
  Name   | Version |   Schema   |                            Description
---------+---------+------------+-------------------------------------------------------------------
 pg_trgm | 1.1     | public     | text similarity measurement and index searching based on trigrams
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```
