### ISSUE TITLE
Display Version Information

### ISSUE THREAD

**Issue by smith** [chef/supermarket#863]
Once we have omnibus packaging, we should have a place where we display the current running version of supermarket (which we can get at build time or from the version manifest), the changelog (by rendering CHANGELOG.md into Markdown), and the version manifest (installed in /opt/supermarket/version-manifest.txt), and maybe the LICENSE too.

Probably should show the version in the footer somewhere and have a link that goes to the changelog and further version information.

**Comment by cmluciano** [comment]
Looking into this now. Where does the version-manifest come from? Is this in a specific repo?

**Comment by smith** [comment]
@cmluciano when building the an omnibus package it drops this text file in /opt/supermarket/version.manifest.txt. It looks like this: https://gist.github.com/smith/9f7c5b3370aa52751329

**Comment by nellshamrell** [comment]
Would be good to have a /version endpoint along with /status

**Comment by robbkidd** [comment]
I did a quick spike on a `/changelog` endpoint as the easiest to implement given the presence of the CHANGELOG.md at the root of the web application.

Displaying the Supermarket version in a `/version` endpoint and `version` in the status JSON response is more complicated, but not awful.

Despite the outputs of my spike being largely shippable, I suggest we wait on the implementation until after our effort to unify supermarket-related repos.

On using the information in `/opt/supermarket/version-manifest.txt`—the versions of the dependency components included in an omnibus package—I am :-1: to displaying the contents to all users for the same reasons that it is recommended that banner information/server tokens be disabled in web servers.

**Comment by tas50** [comment]
I'm going to close this out. For security reasons we've been asked by customers not to disclose server releases so this is problematic.
