### ISSUE TITLE
Embedded Fonts

### ISSUE THREAD

**Issue by smith** [chef/supermarket#864]
We serve the Google Fonts (Montserrat) and Font Awesome from CDNs. If you're viewing an on-premises install and those CDN locations aren't reachable, those fonts don't get served. The Montserrat falls back to Helvetica, which is okay-ish, but the Font Awesome won't show up at all.

Both of these have methods by which you can download the css/woff/ttf assets and embed them within your project.

**Comment by nellshamrell** [comment]
Thank you so much for the suggestion!  We're not going to move forward with it at this time, but will keep it in mind!
