### ISSUE TITLE
Access control for cookbook namespaces

### ISSUE THREAD

**Issue by kisoku** [chef/supermarket#865]
This came up in conversation with @cwebberOps today. 

We would like to run a private supermarket internally to take advantage of the supermarket's universe endpoint and would like to ensure that certain well known cookbooks from the community cannot superceded by results from our supermarket. 

Here's an example.

We have decided internally to only permit the use of the community postgresql cookbook, we do not want any cookbooks named 'postgresql' to be published on our internal supermarket.

**Comment by nathenharvey** [comment]
Two years on ... how are you handling this today?  Is this still a concern?

**Comment by cwebberOps** [comment]
@nathenharvey I am sure it is still something that some orgs would like... but given the lack of any other requests, I would say close it out.
