### ISSUE TITLE
supermarket-ctl console command

### ISSUE THREAD

**Issue by smith** [chef/supermarket#885]
As a system administrator of a Supermarket instance, I want to be able to use a Rails console on a live instance to inspect the state.

This can be accomplished by making a ctl-command that effectively does `PATH=/opt/supermarket/embedded/bin:$PATH /opt/supermarket/embedded/service/supermarket/bin rails console production`.

We should also enable Pry (and pry-remote if possible) in production so the console uses Pry instead of IRB.

**Comment by nellshamrell** [comment]
Just submitted this as a pull request to omnibus-supermarket https://github.com/chef/omnibus-supermarket/pull/40
