### ISSUE TITLE
Disabled services do not show up in `supermarket-ctl status`

### ISSUE THREAD

**Issue by smith** [chef/supermarket#890]
They show as disabled with `supermarket-ctl service-list`, but just don't show up with `supermarket-ctl status`. They should show up like:

```
redis disabled
```

When `redis.enable.false` is set instead of just not being there.

**Comment by nellshamrell** [comment]
Hi @smith!

Thanks for reporting this.  Unfortunately, this appears to be an issue with [omnibus-ctl](https://github.com/chef/omnibus-ctl), rather than with omnibus-supermarket.  I am transferring this issue over there.
