### ISSUE TITLE
Cookbook badges

### ISSUE THREAD

**Issue by smith** [chef/supermarket#892]
As a user of a cookbook, I would like to see the latest version that's been uploaded to Supermarket in that cookbook's documentation in a place like the GitHub README.

As a publisher of a cookbook, I would like to tell my users the same information.

Could be something like what NPM does: 

[![NPM version](https://badge.fury.io/js/chef.png)](http://badge.fury.io/js/chef)

Or something like what Clojars does:

[![Clojars Project](http://clojars.org/enfocus/latest-version.svg)](http://clojars.org/enfocus)

and show the Berks/Librarian command to use.

Or some combination of those.

**Comment by dhoer** [comment]
@smith http://shields.io mentioned above does what I wanted and I am implementing it (e.g., https://github.com/dhoer/chef-selenium2)
Thanks

**Comment by nellshamrell** [comment]
Thanks so much for this input!  We are not working on this at this time, but will keep it in mind!
