### ISSUE TITLE
Foodcritic false alarms

### ISSUE THREAD

**Issue by dpetzel** [chef/supermarket#906]
Sorry if this is the wrong place for this, but I noticed that after uploading a new cookbook, I see foodcritic errors about a missing metadata.rb

Example: https://supermarket.getchef.com/cookbooks/consul_kv#foodcritic 

```
FC031: Cookbook without metadata file: /tmp/cook/e9e2dd386c1eeea455b8c82e/consul_kv/metadata.rb:1
FC045: Consider setting cookbook name in metadata: /tmp/cook/e9e2dd386c1eeea455b8c82e/consul_kv/metadata.rb:1
```

This cookbook does actually have a metadata.rb and it has a name attribute define, so something seems amiss here.

**Comment by someara** [comment]
Also, it shouldn't be supermarket's place to be doing CI style checks on artifacts uploaded to it.
The foodcritic checks should be removed completely
