### ISSUE TITLE
An Artifact?

### ISSUE THREAD

**Issue by cwebberOps** [chef/supermarket#930]
On the Supermarket, are the cookbooks artifacts? My gut answer to this question is yes, but once I start to add additional context, it gets way fuzzier.

First, a bit of backstory... Version 3.2.3 of stove only uploads a metadata.json and does not upload a metadata.rb. The logic as to why is sound, assuming the cookbook is an artifact, you shouldn't need to, or want to execute arbitrary code on your system. And for Berkshelf, this worked fine. But for others, this resulted in two issues: 

1. Foodcritic, run by Fieri, now shows a violation because the metadata.rb is missing. (as an aside, this is easy to address by just telling foodcritic not to care about that specific rule.)
2. `knife cookbook site install` is now broken when a cookbook that doesn't have a metadata.rb is being installed directly or as part of the dependency chain.

More of the specifics of this discussion can be found in https://github.com/opscode/chef/pull/2345.

So for me, this discussion really revolves around a more central question. How do we test quality of a cookbook if it is "just" an artifact?

I see basically two approaches to this problem:
1. In order to get quality ratings for your cookbook, you have to provide a source URL and we then slurp that down and run tests, etc.
2. Run the quality tests against the artifact and know that there will be folks that disagree with that approach.

Each of these approaches has a bit more discussion involved, but I am trying to get an idea what direction to head. What are your thoughts?

**Comment by alexmanly** [comment]
+1 to having Supermarket enforce that uploaded code has both metadata.rb and metadata.json.  It breaks the workflow of downloading cookbooks from public supermarket and then uploading them to a private supermarket for those customer that want to contain all packages/automation within the firewall.

**Comment by nellshamrell** [comment]
Thank you everyone for this discussion!  This will probably continue into the next year and should be addressed with an RFC, we will definitely keep this issue in mind.  Thank you so much for the input!
