### ISSUE TITLE
Google visibility / SEO / Domain changes

### ISSUE THREAD

**Issue by rmoriz** [chef/supermarket#931]
Hi,

IMHO Supermarket isn't ranked on google the way it should be, e.g. google for something unique like "ssh_known_hosts".

I see two issues:

1. duplicate content, e.g. http://cookbooks.opscode.com/tools?type=chef_tool and  https://supermarket.chef.io/tools?type=chef_tool

  => solution: 301 redirects to the official address

2.  missing canonical tag in html
https://www.mattcutts.com/blog/canonical-link-tag/

**Comment by nellshamrell** [comment]
@rmoriz thanks again for bringing this to our attention.  We checked this morning and searching for ssh_known_hosts on Google results in the cookbook's Github repo as #1 and the supermarket entry at #2, so are going to go ahead and close this issue.
