### ISSUE TITLE
README Markdown: Use a SSL image proxy

### ISSUE THREAD

**Issue by zuazo** [chef/supermarket#947]
I think using a image proxy like [camo](https://github.com/atmos/camo) is a better solution than forcing `https://` and breaking non-HTTPS images:

* Linking external images should be considered insecure because allows user tracking.
* Usually having all images cached and linking to the same domain reduces page load time considerably.
* Allows image links without HTTPS support: some badge providers like [inch-ci](http://inch-ci.org/) do not support HTTPS.

There is a [cookbook for `camo`](https://supermarket.chef.io/cookbooks/camo) that perhaps could be used for this.

### More information

https://help.github.com/articles/why-do-my-images-have-strange-urls/:
> GitHub uses an open-source project called Camo to provide a proxy for images hosted on GitHub. A proxy is an intermediate server that provides anonymity for users. It helps protect your privacy by preventing browser information to be leaked to third-parties that may be snooping in. If a user hosts an image on another server and links to it on GitHub, users viewing that image have no guarantee that their browser information (and more) isn't being sent elsewhere.
> [...]
> Camo also ensures that all resources are being served through HTTPS and are secure. Furthermore, we host and cache these images on a CDN, so they are served blazing fast.

https://github.com/blog/1766-proxying-user-images:
> A while back, we started proxying all non-https images to avoid mixed-content warnings using a custom node server called camo. We’re making a small change today and proxying HTTPS images as well.
> 
> Proxying these images will help protect your privacy: your browser information won't be leaked to other third party services. Since we're also routing images through our CDN, you should also see faster overall load times across GitHub, as well as fewer broken images in the future.

### Related issues

* [README Markdown: image links without HTTPS support are broken #941](#941)
* [Attempt to prevent security warnings when using HTTPS #528](#528)
* [Produce protocol-relative Markdown images #571](#571)

**Comment by nellshamrell** [comment]
Thank you so much for the input!  We are not going to move forward with camo at this time, but thank you again and have a wonderful holiday and new year!
