### ISSUE TITLE
supermarket_instance should support specifying version

### ISSUE THREAD

**Issue by cwebberOps** [chef/supermarket#948]
supermarket_instance should allow you to specify the version of the supermarket package you want.

**Comment by drag00n** [comment]
I'd like to help out with this, but I'm uncertain what supermarket package is referring to. Is this the cookbook version or the [omnibus-supermarket](https://github.com/opscode/omnibus-supermarket) package? If the latter, is this relying on specifying a github release?

**Comment by nellshamrell** [comment]
@cwebberOps I think this has already been addressed sometime in 2015...but if you are still seeing this or would like us to further address, please feel free to re-open this issue.
