### ISSUE TITLE
supermarket_instance should allow you to disable repo management

### ISSUE THREAD

**Issue by cwebberOps** [chef/supermarket#949]
In many environments, it is common that external repos are not used. We should allow for the repo management to be disabled, allowing it to be a separate concern.

**Comment by kirtfitzpatrick** [comment]
@cwebberOps What do you mean by this?

**Comment by cwebberOps** [comment]
@kirtfitzpatrick So in https://github.com/opscode-cookbooks/supermarket/blob/master/libraries/provider_supermarket_instance.rb#L42-L53 we setup the package cloud repos. The idea behind this issue is that if we are in an org where they use internal package repos and just copy the appropriate packages into those repos, we should be able to turn off adding the package cloud repos.

**Comment by nellshamrell** [comment]
Closing this, as that cookbook is no longer used.  @cwebberOps if this is missing from omnibus supermarket and you would like to see it added or have more input, feel free to open this up again :)
