### ISSUE TITLE
Supermarket user partially created if Chef user does not have email address

### ISSUE THREAD

**Issue by mcallb** [chef/supermarket#956]
When a user without an email address on the Chef server logs on to private supermarket via oAuth, the user is authorized without error. When the user tries to login to supermarket an error is generated. 

"We are sorry, but something went wrong."

NOTE: We are using LDAP integration with Chef Enterprise 11.12.2.

Steps to reproduce issue:

Create a domain user in Active Directory without an email address
Login as this user to the Chef server and assign it to an organization
This generates an error but the user is created “An error occurred, please try again”
Login to private supermarket
The user is authorized without error
Login again to private supermarket
This generates an error “We are sorry but something went wrong”

The following is logged to production.log

F, [2014-12-19T01:13:26.699677 #11496] FATAL -- :
NoMethodError (undefined method `assign_attributes' for nil:NilClass):
  app/models/user.rb:341:in `find_or_create_from_chef_oauth'
  app/controllers/sessions_controller.rb:19:in `create’

In the supermarket database, the user is added to the accounts table but there is no corresponding entry in the users table. Email is a required field.

psql> \d+ users

email              | character varying(255)      | not null default ''::character varying             | extended

**Comment by nellshamrell** [comment]
@mcallb Thank you for reporting this and sorry for the ultra long delay before addressing this.  According to the current Chef documentation https://docs.chef.io/server_ldap.html it looks like we now require an email address for an LDAP user.  If you see this again, please feel free to open this issue back up and we will take another look.  Thank you!
