### ISSUE TITLE
Logic gap when rails and postgres run on separate hosts (omnibus)

### ISSUE THREAD

**Issue by leftathome** [chef/supermarket#957]
So I've got the omnibus install (1.5.0-alpha1) set up on my app node, which runs the rails and nginx components with all other components disabled, and I've got a database node that runs only the postgres component, all other components disabled (in supermarket.json).

My expectation is that the omnibus-supermarket cookbook will do one of two things here to set up the database:

* The app node will, armed with the proper remote DB credentials, provision the database and schema remotely.
* The database node will provision the database and schema, and maybe it'll be up to me to set up accounts and passwords and then get that data back over to the app node, whatever, I'm okay with that.  And the app node will just log in, maybe run a migration or two and generally have a good time.

It looks like the cookbook tries to do things the first way, but the underlying enterprise cookbook uses createdb and assumes you're creating schema on the db host all the time.  SAD TIMES.

Anyway, I know there's a strong vision for the omnibus-supermarket cookbook and modifying that enterprise cookbook looks like it'd potentially impact a bunch of other Chef server components, but I thought I'd at least raise this issue as an example of omnibus component gaps.

P.S.  Still a big fan of omnibus-supermarket, having experienced the alternative.  Thank you so much for all the omnibusification work you've done.

**Comment by leftathome** [comment]
cc @irvingpop at his request...

**Comment by nellshamrell** [comment]
This was addressed in https://github.com/chef/omnibus-supermarket/pull/23

@leftathome - if there is more you would like to see, let us know.  Closing this for now.
