### ISSUE TITLE
Production Rails app troubleshooting (omnibus)

### ISSUE THREAD

**Issue by leftathome** [chef/supermarket#958]
I seem to be having trouble uploading cookbooks to my new multi-node Supermarket install.  Pretty sure it's my Paperclip / S3 configuration.  But this issue isn't about that!  It's a _meta_ issue.

Because when I supermarket-ctl tail, I only see a 500 error on upload from nginx and nothing unusual for rails.  I know how to take a Sawz-All to a Rails app, crank up log levels and do other nasty things in the name of debugging, so I'll start doing that, but in the meantime I'm wondering if this is the intended troubleshooting path for omnibus users?

**Comment by smith** [comment]
Does #940 help at all? Not sure if that needs to be merged or if more work needs to be done on there.

**Comment by leftathome** [comment]
Yep, #940 is a step in the right direction -- I've basically added the same stanza internally until I finished troubleshooting - turns out cookbook uploads were failing because the local cookbook upload directory didn't exist, and when I switched on S3 it turns out I was being an idiot and not using the right bucket name...

However, I do think the most correct thing to do is probably to log to stdout and have your stdout logger route that to either a local file (default) or a remote syslog server.  Splunkers and Logstashers and the-same-thing-but-SaaSers should be able to leverage that on larger installs while smaller-scale deployments and localdev still has a local log file.

**Comment by nellshamrell** [comment]
@leftathome hello!  I'm going through some older outstanding issues.  Is this still an issue for you?
