### ISSUE TITLE
Easier user discoverability

### ISSUE THREAD

**Issue by leftathome** [chef/supermarket#961]
In all my tire-kicking leading up to launching Supermarket internally, I've noticed that it seems to be relatively difficult to look at what other people are doing as people.  You can find people through their cookbooks and tools without too much trouble, and you can search for users in certain cases where it makes sense to do so, but there's nothing like a user directory.  I've found having a user directory / activity feed in GitHub Enterprise to be a good way of finding people who are working on stuff that's similar to mine or just new people in general working on interesting things.

Was not implementing this an intentional Supermarket design decision (i.e. to put the cookbooks and tools front and center)?  Is this one of those things that only makes sense behind the firewall?  Should it be implemented behind a feature toggle?

Also, I'm sorry, I really will limit myself to opening two issues per day in 2015 (with an exception for extraordinary circumstances). :)

**Comment by smith** [comment]
I think the only reason that what you're talking about isn't a feature is because it was never really discussed or prioritized. Sounds like it would be a useful thing.

**Comment by nellshamrell** [comment]
Thanks for the input @leftathome - I think this is covered in the request in #894.  However, if there is more you would like to see, please feel free to re-open this :)
