### ISSUE TITLE
Feature:  Serve from private S3 buckets

### ISSUE THREAD

**Issue by leftathome** [chef/supermarket#964]
Longtime readers of my issues know that I'm trying to set up a reasonably enterprise-y private Supermarket.  At the moment I've got it serving cookbooks out of a private S3 bucket.  Amazon best practice says this is fine.  Only if I'm going to do it, I should be using signed/expiring URLs.

The way I've implemented this is that I'm configuring the S3 variables except for the CloudFront URL...

... and I've had to make one teeny tiny face-smashingly easy change in the CookbookVersions controller.

Instead of using Paperclip's url method in the redirect_to, I change it to expiring_url(15) ( == number of seconds the URL is valid before expiring).  I don't know if this would break if I fell back to local storage.

The other two ways I can think of to implement this would be:

* Use Rails to proxy S3 by downloading the tarball and send_data'ing it (with nginx/varnish-friendly headers) to the client.  The only plus I can think of to this implementation is if I have Supermarket cookbook consumers who are in a totally firewalled environment where they can't hit S3...
* CloudFront (but ... how to make this private?).

**Comment by leftathome** [comment]
Oh, also, some additional reading on expiring URLs in Paperclip:

https://github.com/thoughtbot/paperclip/wiki/Restricting-Access-to-Objects-Stored-on-Amazon-S3

**Comment by leftathome** [comment]
Update!  Apparently expiring_url handling in Paperclip v4.2.0 (as used in Supermarket 1.5.x releases) didn't take into account that Fog handles expiring URL generation differently.  I'm going to try upgrading to v4.2.1 on my internal fork and see if that resolves some issues I've been having where cookbook download URLs are throwing 403 errors.  It seems to be random per CookbookVersion (but consistent on the ones that are affected)...

**Comment by leftathome** [comment]
Update update: Yeah, that didn't help at all.  I should check commit diffs before getting excited about reading release notes.

However!  I did find something that fixed my issue - I added a fog API call to connection.sync_clock.  I've suspected that the temporary URL being generated was being generated with an expiration date in the past.  This is either down to bad time zone handling or some really weird environment configuration somewhere in omnibus-supermarket or the supermarket app itself.  So I'm mentioning it here first.  (No one else on the Google-indexed Internet seems to be having this problem at the moment.)

For the record, I patched Paperclip::Storage::Fog#directory to run connection.sync_clock() before returning directory info.  It seemed like the right place, though I suppose one could argue it should be done during connection setup.

Anyway, the cookbook versions that weren't downloading are now downloading properly, Berkshelf is happy, we're fine here.  How are you?

**Comment by nellshamrell** [comment]
Glad to here things are fine for you now.  Any objection to us closing this issue?

**Comment by nellshamrell** [comment]
This is also an issue for other customers:

Biggest concern - that paperclip uploads everything as public unless you tell it not to.  Supermarket is not telling it not to.
  - urls need to not be public

**Comment by leftathome** [comment]
I think I forgot to mention that I added `s3_permissions: :private` to the paperclip initializer to do that on my fork.  If I were contributing the fix to OSS, I would roll that up into the omnibus-supermarket cookbook as an attribute that gets exposed as an environment variable for the app.

I repeatedly verified during initial testing that file permissions in the resulting S3 bucket stayed private, so I believe this modest change is doing the right thing...

**Comment by nellshamrell** [comment]
Agreed, I'll get that cooked up!  Thanks so much for the insight!

**Comment by nellshamrell** [comment]
I've coded a fix for this, but need to test it on an actual S3 instance before I submit the pull request.  It's getting a bit late in the day on Friday to do this, but I will start the testing on Monday morning.

**Comment by nellshamrell** [comment]
Still working on this, will give an update at EOD

**Comment by nellshamrell** [comment]
I've submitted a pull request with a fix.  Once that is reviewed, we'll do a release ASAP.
