### ISSUE TITLE
Allow using the X-Forwarded-For instead of remote-addr in nginx logs

### ISSUE THREAD

**Issue by smith** [chef/supermarket#969]
In the nginx configuration (https://github.com/opscode/omnibus-supermarket/blob/b7c93027039315a4e29361edc5fd1ef9816ab336/cookbooks/omnibus-supermarket/templates/default/rails.nginx.conf.erb#L13) remote-addr is used, which works fine, except if you're behind a load balancer, in which case you'll be getting the LB address instead of the address of the originating request.

Allow a configuration option to let you use the X-Forwarded-For header address instead.

See also opscode/opscode-omnibus#459.

**Comment by nellshamrell** [comment]
Similar #984

**Comment by nellshamrell** [comment]
This was fixed with the release of Supermarket 2.0
