### ISSUE TITLE
add link somewhere to list of curry-managed repositories

### ISSUE THREAD

**Issue by juliandunn** [chef/supermarket#975]
As a Supermarket admin,
I would like to see what repositories are being checked for a CLA,
So that I don't have to dig through HipChat history to remember that the link is https://supermarket.chef.io/curry/repositories

**Comment by bcobb** [comment]
https://github.com/chef/supermarket/blob/7cba5b63f4d99c5d174c6d11b90314c59aec532a/app/views/application/_appheader.html.erb#L31-L35 makes me think that you should be seeing the link when you hover over your username in the header.

**Comment by juliandunn** [comment]
You are right! But that label is confusing - I never clicked on it because I thought it was to show the cookbooks that I personally was following.

**Comment by kirtfitzpatrick** [comment]
What should that label be?

**Comment by juliandunn** [comment]
is this not already closed by #978?
