### ISSUE TITLE
Feature: Search for cookbooks based on supported platform

### ISSUE THREAD

**Issue by andrewelizondo** [chef/supermarket#980]
Use case: As a new user I'd like to be able to access the supermarket and filter/search for cookbooks that are supported on the platform I'm managing. e.g. show me all of the cookbooks that claim to support windows

**Comment by jtimberman** [comment]
This would be a great feature. Potential problem is that the metadata `supports` doesn't do anything else anywhere so many people don't use it. But hey maybe then they'd start!

**Comment by tuahk** [comment]
I also think this would be a very useful feature so I'd liked to tackle this one.
