### ISSUE TITLE
Inverse dependency search

### ISSUE THREAD

**Issue by rmoriz** [chef/supermarket#981]
I would love to be able to search the supermarket for all cookbooks that depend on $cookbook.

Use case:

You have a cookbook naming conflict (e.g. due to some popular community cookbooks like "rbenv" or "postgresql" which are different from the ones on supermarket). You would like to be able to generate a blacklist of cookbooks that you won't be able to use, because they depend on the "official" "rbenv" or "postgresql" cookbooks.

**Comment by becha2** [comment]
When you select on a certain cookbook and look at its dependencies, you can see a list of contingent cookbooks. These should all be cookbooks that depend on that specific cookbook. I think it would be redundant to implement a search function for this.
