### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by amaltson** [chef/supermarket#983]
Looking at the way the [GitHub Omniauth is configured in supermarket](https://github.com/chef/supermarket/blob/66d58ed75b907ef8b28b0dfbfc41979c7d129582/config/initializers/omniauth.rb#L18-L22), it doesn't look like there's support for GitHub Enterprise. Looking at the OmniAuth docs, it looks like [GitHub Enterprise support is built in](https://github.com/intridea/omniauth-github#github-enterprise-usage). Any chance we can add in a few more environment variables to enable Enterprise support (I'll try to send a PR myself if I can).

**Comment by kirtfitzpatrick** [comment]
Since GitHub integration is primarily for CLA's or open source contributions, i.e. public github, there isn't much reason to integrate with Enterprise GitHub at this time.

**Comment by kirtfitzpatrick** [comment]
Since github integration exists for CLA's for open source contributions and therefore the public github.com, there isn't a compelling reason to integrate with Enterprise Github at this time.

**Comment by amaltson** [comment]
Yeah that makes sense. I noticed that auth just delegates to the Chef
Server, whereas I thought the GitHub integration let you log into
supermarket with GitHub.
