### ISSUE TITLE
Deploy without S3

### ISSUE THREAD

**Issue by amaltson** [chef/supermarket#984]
At our company we aren't allowed to use any cloud services and I noticed in the [configuring supermaket for production docs](https://github.com/chef/supermarket/blob/master/docs/CONFIGURING.md) it mentions S3 buckets. If I don't put in an S3 key, does supermarket just use the local file system?

**Comment by smith** [comment]
Yes that's correct. See #886 and #964 for more discussion. If you're running a single app server instance, you should be fine. If you're trying to run multiple app server instances, you'll need to ensure the filesystem location to which cookbooks are uploaded is on some kind of shared storage that all app server nodes can access.

**Comment by amaltson** [comment]
Perfect, thanks @smith!
