### ISSUE TITLE
Cannot converge supermarket cookbook behind a restrictive firewall

### ISSUE THREAD

**Issue by jf647** [chef/supermarket#985]
The supermarket cookbook depends on the packagecloud cookbook using the 'github' location.

Berks turns this into a URL that uses the 'git' protocol, which is generally not something that corporate firewalls let out.

Publicly distributed cookbooks should only use the 'git' location with a protocol that is generally known to be accessible through a proxy (i.e. https)

**Comment by jtimberman** [comment]
WIP

**Comment by pburkholder** [comment]
https://github.com/opscode-cookbooks/supermarket/pull/83 Does this help, since it's the cookbook, not the project in question here?

**Comment by jtimberman** [comment]
Yes, this is the cookbook, so we'll use the PR not this issue.

**Comment by jtimberman** [comment]
https://github.com/opscode-cookbooks/supermarket/pull/83 is merged.
