### ISSUE TITLE
See all cookbooks available for adoption

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#987]
As a user, I would like to be able to see a list of all cookbooks available for adoption

**Comment by nellshamrell** [comment]
Looks like someone is interested in working on this :) https://twitter.com/dpnl87/status/574982805857378304

**Comment by dpnl87** [comment]
After some struggles setting op the development environment I'm now looking at this.

**Comment by btm** [comment]
@dpnl87 that'd be awesome. let us know if you have any questions.

**Comment by dpnl87** [comment]
The logic changes are done. I can fetch all the cookbooks for adoption from the database. The biggest challenge I currently have is where to display the data.

**Comment by smith** [comment]
@dpnl87 Probably the best place to put a link would be somewhere on https://supermarket.chef.io/cookbooks-directory.

I'm assuming you have some kind of model scope that you can use a parameter to filter by, so you could use a URL like https://supermarket.chef.io/cookbooks?order=recently_updated but use something like https://supermarket.chef.io/cookbooks?adoptable=1 or something.

Feel free to open a PR and label it "[WIP]" if you don't think it's ready to ship and we can discuss it further. Thanks for working on it!

**Comment by kavitasa** [comment]
Hey @dpnl87 and @smith, I didn't realize someone was working on this. I worked on this last week & the only thing left was a little styling. It's been a busy week & I haven't finished that part, but I'll create a PR in case someone wants to take a look. If @dpnl87 has more done, then no worries if you decide to go with his work.

**Comment by kavitasa** [comment]
See issue #1031

**Comment by dpnl87** [comment]
@kavitasa You have done more work than I have so please continue on with your nice work! I'm sure there are other tickets I can find :smiley:

**Comment by cmluciano** [comment]
I think this can be marked as done via #1031

**Comment by btm** [comment]
woot!

https://supermarket.chef.io/available_for_adoption
