### ISSUE TITLE
Correct the nginx X-Forwarded-Proto lines so that rails request.protocol is right in cookbook

### ISSUE THREAD

**Issue by ccrebolder** [chef/supermarket#994]
Would it be possible to implement [this](https://github.com/chef/omnibus-supermarket/pull/10) change in the cookbook?

**Comment by kirtfitzpatrick** [comment]
Committed here:

https://github.com/opscode-cookbooks/supermarket/commit/49a2dc192cc3883e8a1c8bbd11ad24b34b22222e
