### ISSUE TITLE
Cookbook adoption emails should fill in reply to

### ISSUE THREAD

**Issue by cwebberOps** [chef/supermarket#998]
When you get an email for a cookbook that is up for adoption, we should fill in the reply-to so you can just reply instead of creating a new email.

**Comment by cmluciano** [comment]
I'm guessing this could be done with a
```
default from: "blah@example".com
```

**Comment by cwebberOps** [comment]
I think because we are using an external mail service we have to actually set a reply-to header instead of a from header.

**Comment by cmluciano** [comment]
![image](https://cloud.githubusercontent.com/assets/4790487/6825231/60fac754-d2cf-11e4-9ba2-619eaed57ec6.png)

Indeed

**Comment by nellshamrell** [comment]
We're not going to implement this at this time, but thank you so much for the feedback!
